create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique check (char_length(email) between 3 and 320),
  locale text not null default 'en',
  category_slug text,
  source_url text,
  status text not null default 'subscribed'
    check (status in ('subscribed', 'unsubscribed')),
  consent_at timestamptz not null default now(),
  unsubscribed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.newsletter_subscribers enable row level security;

revoke all on table public.newsletter_subscribers from anon, authenticated;
revoke all on sequence public.newsletter_subscribers_id_seq from anon, authenticated;

grant select, insert, update, delete on table public.newsletter_subscribers to service_role;
grant usage, select on sequence public.newsletter_subscribers_id_seq to service_role;

create index if not exists newsletter_subscribers_status_created_idx
  on public.newsletter_subscribers (status, created_at desc);
