import type { BenefitsCopy } from './WhyChooseAutorellPage'
import type { PublicLocale } from '@/lib/public-i18n'

type ConstructionCopy = Pick<BenefitsCopy, 'metaTitle' | 'metaDescription' | 'eyebrow' | 'title' | 'intro' | 'primaryCta' | 'proof' | 'stepsTitle' | 'steps' | 'seoTitle' | 'seoText' | 'faqTitle' | 'faqs'>

const copy: Record<PublicLocale, ConstructionCopy> = {
  sv: {
    metaTitle: 'Sälj entreprenadmaskiner gratis online | Autorell',
    metaDescription: 'Annonsera grävmaskiner, hjullastare och annan entreprenadmaskin gratis i 5 dagar och nå köpare på Autorell.',
    eyebrow: 'SÄLJ MASKINER PÅ AUTORELL',
    title: 'Sälj maskiner gratis',
    intro: 'Skapa en tydlig annons för grävmaskiner, hjullastare och andra maskiner och nå köpare som söker rätt utrustning.',
    primaryCta: 'Kom igång gratis',
    proof: 'Gratis grundannons i 5 dagar. Betala bara för längre publicering eller extra synlighet.',
    stepsTitle: 'Tre enkla steg till en publicerad maskinannons',
    steps: [
      { title: 'Lägg in maskinen', text: 'Fyll i maskintyp, modell, drifttimmar, pris, plats och bilder i ett tydligt flöde.' },
      { title: 'Publicera gratis', text: 'Din grundannons är gratis i 5 dagar. Förläng bara när du behöver det.' },
      { title: 'Nå rätt köpare', text: 'Köpare hittar maskinen via sök, kategori och marknad och kontaktar dig direkt.' },
    ],
    seoTitle: 'Byggd för att maskiner ska hittas',
    seoText: 'Autorell gör det enkelt att annonsera grävmaskiner, hjullastare, dumprar, kranar och andra maskiner med rätt tekniska data och bilder.',
    faqTitle: 'Vanliga frågor om att sälja entreprenadmaskiner',
    faqs: [
      { question: 'Är det gratis att annonsera en entreprenadmaskin?', answer: 'Ja. Grundannonsen är gratis i 5 dagar. Du betalar bara om du vill annonsera längre eller öka synligheten.' },
      { question: 'Vilka maskiner kan jag annonsera?', answer: 'Du kan annonsera bland annat grävmaskiner, hjullastare, dumprar, kranar och andra entreprenadmaskiner.' },
      { question: 'Vilka uppgifter bör jag lägga till?', answer: 'Lägg till maskintyp, modell, drifttimmar, arbetsvikt, utrustning, pris, plats och tydliga bilder.' },
    ],
  },
  en: {
    metaTitle: 'Sell Construction Machinery Free Online | Autorell', metaDescription: 'List excavators, loaders and construction machinery free for 5 days and reach serious buyers on Autorell.', eyebrow: 'SELL CONSTRUCTION MACHINERY ON AUTORELL', title: 'Sell construction machinery for free', intro: 'Create a clear listing for excavators, loaders and other machines and reach buyers looking for the right equipment.', primaryCta: 'Get started for free', proof: 'Free core listing for 5 days. Pay only for longer publishing or extra visibility.', stepsTitle: 'Three simple steps to a published machinery listing', steps: [{ title: 'Add the machine', text: 'Enter machine type, model, hours, price, location and images in one clear flow.' }, { title: 'Publish for free', text: 'Your core listing is free for 5 days. Extend it only when you need to.' }, { title: 'Reach the right buyer', text: 'Buyers find the machine through search, category and market pages and contact you directly.' }], seoTitle: 'Built to help construction machinery get found', seoText: 'Autorell makes it easy to list excavators, loaders, dumpers, cranes and other construction equipment with useful technical data and images.', faqTitle: 'Common questions about selling construction machinery', faqs: [{ question: 'Is it free to list construction machinery?', answer: 'Yes. The core listing is free for 5 days. Pay only for longer publishing or more visibility.' }, { question: 'Which machines can I list?', answer: 'List excavators, wheel loaders, dumpers, cranes and other construction machinery.' }, { question: 'Which details should I add?', answer: 'Add machine type, model, hours, weight, equipment, price, location and clear images.' }],
  },
  de: { metaTitle: 'Baumaschinen kostenlos online verkaufen | Autorell', metaDescription: 'Inserieren Sie Bagger, Radlader und Baumaschinen 5 Tage kostenlos und erreichen Sie passende Käufer auf Autorell.', eyebrow: 'BAUMASCHINEN AUF AUTORELL VERKAUFEN', title: 'Baumaschinen kostenlos verkaufen', intro: 'Erstellen Sie ein klares Inserat für Bagger, Radlader und andere Maschinen und erreichen Sie passende Käufer.', primaryCta: 'Kostenlos starten', proof: 'Basisinserat 5 Tage kostenlos. Zahlen Sie nur für längere Laufzeit oder mehr Sichtbarkeit.', stepsTitle: 'Drei einfache Schritte zum Maschineninserat', steps: [{ title: 'Maschine eintragen', text: 'Ergänzen Sie Maschinentyp, Modell, Stunden, Preis, Standort und Bilder.' }, { title: 'Kostenlos veröffentlichen', text: 'Das Basisinserat ist 5 Tage kostenlos. Verlängern Sie nur bei Bedarf.' }, { title: 'Passende Käufer erreichen', text: 'Käufer finden die Maschine über Suche, Kategorie und Markt und kontaktieren Sie direkt.' }], seoTitle: 'Baumaschinen sichtbar machen', seoText: 'Inserieren Sie Bagger, Radlader, Dumper, Krane und weitere Baumaschinen mit technischen Daten und Bildern.', faqTitle: 'Fragen zum Verkauf von Baumaschinen', faqs: [{ question: 'Ist das Inserieren kostenlos?', answer: 'Ja. Das Basisinserat ist 5 Tage kostenlos.' }, { question: 'Welche Maschinen kann ich verkaufen?', answer: 'Bagger, Radlader, Dumper, Krane und weitere Baumaschinen.' }, { question: 'Welche Angaben sind wichtig?', answer: 'Maschinentyp, Modell, Betriebsstunden, Gewicht, Ausstattung, Preis, Standort und Bilder.' }] },
  at: { metaTitle: 'Baumaschinen in Österreich kostenlos verkaufen | Autorell', metaDescription: 'Inserieren Sie Bagger, Radlader und Baumaschinen 5 Tage kostenlos und erreichen Sie Käufer in Österreich auf Autorell.', eyebrow: 'BAUMASCHINEN AUF AUTORELL VERKAUFEN', title: 'Baumaschinen kostenlos verkaufen', intro: 'Erstellen Sie ein klares Inserat für Bagger, Radlader und andere Maschinen und erreichen Sie passende Käufer.', primaryCta: 'Kostenlos starten', proof: 'Basisinserat 5 Tage kostenlos. Zahlen Sie nur für längere Laufzeit oder mehr Sichtbarkeit.', stepsTitle: 'Drei einfache Schritte zum Maschineninserat', steps: [{ title: 'Maschine eintragen', text: 'Ergänzen Sie Maschinentyp, Modell, Stunden, Preis, Standort und Bilder.' }, { title: 'Kostenlos veröffentlichen', text: 'Das Basisinserat ist 5 Tage kostenlos. Verlängern Sie nur bei Bedarf.' }, { title: 'Passende Käufer erreichen', text: 'Käufer finden die Maschine über Suche, Kategorie und Markt und kontaktieren Sie direkt.' }], seoTitle: 'Baumaschinen sichtbar machen', seoText: 'Inserieren Sie Bagger, Radlader, Dumper, Krane und weitere Baumaschinen mit technischen Daten und Bildern.', faqTitle: 'Fragen zum Verkauf von Baumaschinen', faqs: [{ question: 'Ist das Inserieren kostenlos?', answer: 'Ja. Das Basisinserat ist 5 Tage kostenlos.' }, { question: 'Welche Maschinen kann ich verkaufen?', answer: 'Bagger, Radlader, Dumper, Krane und weitere Baumaschinen.' }, { question: 'Welche Angaben sind wichtig?', answer: 'Maschinentyp, Modell, Betriebsstunden, Gewicht, Ausstattung, Preis, Standort und Bilder.' }] },
  fr: { metaTitle: 'Vendre des engins de chantier gratuitement | Autorell', metaDescription: 'Publiez pelles, chargeuses et engins de chantier gratuitement pendant 5 jours et trouvez des acheteurs sérieux.', eyebrow: 'VENDEZ VOS ENGINS SUR AUTORELL', title: 'Vendez vos engins de chantier gratuitement', intro: 'Créez une annonce claire pour vos pelles, chargeuses et autres machines et touchez les bons acheteurs.', primaryCta: 'Commencer gratuitement', proof: 'Annonce de base gratuite pendant 5 jours. Payez uniquement pour prolonger ou gagner en visibilité.', stepsTitle: 'Trois étapes simples pour publier votre machine', steps: [{ title: 'Ajoutez la machine', text: 'Saisissez le type, le modèle, les heures, le prix, le lieu et les photos.' }, { title: 'Publiez gratuitement', text: 'L’annonce de base est gratuite pendant 5 jours.' }, { title: 'Trouvez le bon acheteur', text: 'Les acheteurs trouvent votre machine par recherche, catégorie et marché.' }], seoTitle: 'Des engins de chantier faciles à trouver', seoText: 'Publiez pelles, chargeuses, tombereaux, grues et autres engins avec leurs données techniques et leurs photos.', faqTitle: 'Questions sur la vente d’engins de chantier', faqs: [{ question: 'La publication est-elle gratuite ?', answer: 'Oui. L’annonce de base est gratuite pendant 5 jours.' }, { question: 'Quels engins puis-je vendre ?', answer: 'Pelles, chargeuses, tombereaux, grues et autres engins de chantier.' }, { question: 'Quelles informations ajouter ?', answer: 'Type, modèle, heures, poids, équipement, prix, lieu et photos.' }] },
  be: { metaTitle: 'Bouwmachines gratis online verkopen | Autorell', metaDescription: 'Plaats graafmachines, laders en bouwmachines 5 dagen gratis en bereik gerichte kopers op Autorell.', eyebrow: 'BOUWMACHINES VERKOPEN OP AUTORELL', title: 'Bouwmachines gratis verkopen', intro: 'Maak een duidelijke advertentie voor graafmachines, laders en andere machines en bereik de juiste kopers.', primaryCta: 'Gratis starten', proof: 'De basisadvertentie is 5 dagen gratis. Betaal alleen voor langer publiceren of extra zichtbaarheid.', stepsTitle: 'Drie eenvoudige stappen naar een machineadvertentie', steps: [{ title: 'Voeg de machine toe', text: 'Vul type, model, uren, prijs, locatie en foto’s in.' }, { title: 'Gratis publiceren', text: 'De basisadvertentie is 5 dagen gratis.' }, { title: 'Bereik de juiste koper', text: 'Kopers vinden je machine via zoeken, categorie en markt.' }], seoTitle: 'Bouwmachines beter vindbaar', seoText: 'Plaats graafmachines, laders, dumpers, kranen en andere bouwmachines met technische gegevens en foto’s.', faqTitle: 'Veelgestelde vragen over bouwmachines verkopen', faqs: [{ question: 'Is plaatsen gratis?', answer: 'Ja. De basisadvertentie is 5 dagen gratis.' }, { question: 'Welke machines kan ik plaatsen?', answer: 'Graafmachines, laders, dumpers, kranen en andere bouwmachines.' }, { question: 'Welke gegevens zijn belangrijk?', answer: 'Type, model, uren, gewicht, uitrusting, prijs, locatie en foto’s.' }] },
  es: { metaTitle: 'Vender maquinaria de construcción gratis | Autorell', metaDescription: 'Publica excavadoras, cargadoras y maquinaria gratis durante 5 días y llega a compradores serios en Autorell.', eyebrow: 'VENDE MAQUINARIA EN AUTORELL', title: 'Vende maquinaria de construcción gratis', intro: 'Crea un anuncio claro para excavadoras, cargadoras y otras máquinas y llega a compradores interesados.', primaryCta: 'Empezar gratis', proof: 'Anuncio básico gratis durante 5 días. Paga solo por más tiempo o visibilidad.', stepsTitle: 'Tres pasos para publicar tu maquinaria', steps: [{ title: 'Añade la máquina', text: 'Introduce tipo, modelo, horas, precio, ubicación y fotos.' }, { title: 'Publica gratis', text: 'El anuncio básico es gratis durante 5 días.' }, { title: 'Llega al comprador adecuado', text: 'Los compradores encuentran tu máquina por búsqueda, categoría y mercado.' }], seoTitle: 'Maquinaria de construcción fácil de encontrar', seoText: 'Publica excavadoras, cargadoras, dúmperes, grúas y otras máquinas con datos técnicos y fotos.', faqTitle: 'Preguntas sobre vender maquinaria de construcción', faqs: [{ question: '¿Publicar es gratis?', answer: 'Sí. El anuncio básico es gratis durante 5 días.' }, { question: '¿Qué máquinas puedo vender?', answer: 'Excavadoras, cargadoras, dúmperes, grúas y otras máquinas.' }, { question: '¿Qué datos debo añadir?', answer: 'Tipo, modelo, horas, peso, equipamiento, precio, ubicación y fotos.' }] },
  it: { metaTitle: 'Vendere macchine edili gratis online | Autorell', metaDescription: 'Pubblica escavatori, pale e macchine da cantiere gratis per 5 giorni e raggiungi acquirenti interessati.', eyebrow: 'VENDI MACCHINE EDILI SU AUTORELL', title: 'Vendi macchine edili gratis', intro: 'Crea un annuncio chiaro per escavatori, pale e altre macchine e raggiungi gli acquirenti giusti.', primaryCta: 'Inizia gratis', proof: 'Annuncio base gratuito per 5 giorni. Paghi solo per più tempo o visibilità.', stepsTitle: 'Tre semplici passaggi per pubblicare una macchina', steps: [{ title: 'Inserisci la macchina', text: 'Aggiungi tipo, modello, ore, prezzo, posizione e foto.' }, { title: 'Pubblica gratis', text: 'L’annuncio base è gratuito per 5 giorni.' }, { title: 'Raggiungi l’acquirente giusto', text: 'Gli acquirenti trovano la macchina tramite ricerca, categoria e mercato.' }], seoTitle: 'Macchine edili facili da trovare', seoText: 'Pubblica escavatori, pale, dumper, gru e altre macchine con dati tecnici e foto.', faqTitle: 'Domande sulla vendita di macchine edili', faqs: [{ question: 'Pubblicare è gratuito?', answer: 'Sì. L’annuncio base è gratuito per 5 giorni.' }, { question: 'Quali macchine posso vendere?', answer: 'Escavatori, pale, dumper, gru e altre macchine edili.' }, { question: 'Quali dati devo inserire?', answer: 'Tipo, modello, ore, peso, dotazione, prezzo, posizione e foto.' }] },
  nl: { metaTitle: 'Bouwmachines gratis online verkopen | Autorell', metaDescription: 'Plaats graafmachines, laders en bouwmachines 5 dagen gratis en bereik serieuze kopers op Autorell.', eyebrow: 'BOUWMACHINES VERKOPEN OP AUTORELL', title: 'Bouwmachines gratis verkopen', intro: 'Maak een duidelijke advertentie voor graafmachines, laders en andere machines en bereik de juiste kopers.', primaryCta: 'Gratis starten', proof: 'De basisadvertentie is 5 dagen gratis. Betaal alleen voor langer publiceren of extra zichtbaarheid.', stepsTitle: 'Drie eenvoudige stappen naar een machineadvertentie', steps: [{ title: 'Voeg de machine toe', text: 'Vul type, model, uren, prijs, locatie en foto’s in.' }, { title: 'Gratis publiceren', text: 'De basisadvertentie is 5 dagen gratis.' }, { title: 'Bereik de juiste koper', text: 'Kopers vinden je machine via zoeken, categorie en markt.' }], seoTitle: 'Bouwmachines beter vindbaar', seoText: 'Plaats graafmachines, laders, dumpers, kranen en andere bouwmachines met technische gegevens en foto’s.', faqTitle: 'Veelgestelde vragen over bouwmachines verkopen', faqs: [{ question: 'Is plaatsen gratis?', answer: 'Ja. De basisadvertentie is 5 dagen gratis.' }, { question: 'Welke machines kan ik plaatsen?', answer: 'Graafmachines, laders, dumpers, kranen en andere bouwmachines.' }, { question: 'Welke gegevens zijn belangrijk?', answer: 'Type, model, uren, gewicht, uitrusting, prijs, locatie en foto’s.' }] },
  pl: { metaTitle: 'Sprzedaj maszyny budowlane za darmo | Autorell', metaDescription: 'Dodaj koparki, ładowarki i maszyny budowlane za darmo na 5 dni i dotrzyj do zainteresowanych kupujących.', eyebrow: 'SPRZEDAJ MASZYNY BUDOWLANE W AUTORELL', title: 'Sprzedaj maszyny budowlane za darmo', intro: 'Utwórz przejrzyste ogłoszenie koparki, ładowarki lub innej maszyny i dotrzyj do właściwych kupujących.', primaryCta: 'Zacznij za darmo', proof: 'Podstawowe ogłoszenie jest bezpłatne przez 5 dni. Płacisz tylko za dłuższą publikację lub większą widoczność.', stepsTitle: 'Trzy proste kroki do publikacji maszyny', steps: [{ title: 'Dodaj maszynę', text: 'Wpisz typ, model, godziny pracy, cenę, lokalizację i zdjęcia.' }, { title: 'Opublikuj za darmo', text: 'Podstawowe ogłoszenie jest bezpłatne przez 5 dni.' }, { title: 'Dotrzyj do kupujących', text: 'Kupujący znajdą maszynę przez wyszukiwanie, kategorię i rynek.' }], seoTitle: 'Maszyny budowlane łatwe do znalezienia', seoText: 'Dodaj koparki, ładowarki, wywrotki, dźwigi i inne maszyny z danymi technicznymi i zdjęciami.', faqTitle: 'Pytania o sprzedaż maszyn budowlanych', faqs: [{ question: 'Czy publikacja jest bezpłatna?', answer: 'Tak. Podstawowe ogłoszenie jest bezpłatne przez 5 dni.' }, { question: 'Jakie maszyny mogę sprzedać?', answer: 'Koparki, ładowarki, wywrotki, dźwigi i inne maszyny.' }, { question: 'Jakie dane dodać?', answer: 'Typ, model, godziny, masa, wyposażenie, cena, lokalizacja i zdjęcia.' }] },
  da: { metaTitle: 'Sælg entreprenørmaskiner gratis online | Autorell', metaDescription: 'Annoncér gravemaskiner, læssere og entreprenørmaskiner gratis i 5 dage og nå seriøse købere på Autorell.', eyebrow: 'SÆLG ENTREPRENØRMASKINER PÅ AUTORELL', title: 'Sælg entreprenørmaskiner gratis', intro: 'Opret en tydelig annonce for gravemaskiner, læssere og andre maskiner og nå de rigtige købere.', primaryCta: 'Kom i gang gratis', proof: 'Grundannoncen er gratis i 5 dage. Betal kun for længere annoncering eller ekstra synlighed.', stepsTitle: 'Tre enkle trin til en maskinannonce', steps: [{ title: 'Tilføj maskinen', text: 'Indtast type, model, timer, pris, placering og billeder.' }, { title: 'Udgiv gratis', text: 'Grundannoncen er gratis i 5 dage.' }, { title: 'Nå den rigtige køber', text: 'Købere finder maskinen via søgning, kategori og marked.' }], seoTitle: 'Gør entreprenørmaskiner synlige', seoText: 'Annoncér gravemaskiner, læssere, dumpere, kraner og andre maskiner med tekniske data og billeder.', faqTitle: 'Spørgsmål om salg af entreprenørmaskiner', faqs: [{ question: 'Er det gratis at annoncere?', answer: 'Ja. Grundannoncen er gratis i 5 dage.' }, { question: 'Hvilke maskiner kan jeg sælge?', answer: 'Gravemaskiner, læssere, dumpere, kraner og andre maskiner.' }, { question: 'Hvilke oplysninger er vigtige?', answer: 'Type, model, timer, vægt, udstyr, pris, placering og billeder.' }] },
  fi: { metaTitle: 'Myy rakennuskoneet ilmaiseksi verkossa | Autorell', metaDescription: 'Lisää kaivinkoneet, kuormaajat ja rakennuskoneet ilmaiseksi 5 päiväksi ja tavoita ostajat Autorellissa.', eyebrow: 'MYY RAKENNUSKONEET AUTORELLISSA', title: 'Myy rakennuskoneet ilmaiseksi', intro: 'Luo selkeä ilmoitus kaivinkoneesta, kuormaajasta tai muusta koneesta ja tavoita oikeat ostajat.', primaryCta: 'Aloita ilmaiseksi', proof: 'Perusilmoitus on ilmainen 5 päivän ajan. Maksat vain pidemmästä näkyvyydestä.', stepsTitle: 'Kolme helppoa vaihetta koneen ilmoittamiseen', steps: [{ title: 'Lisää kone', text: 'Syötä tyyppi, malli, käyttötunnit, hinta, sijainti ja kuvat.' }, { title: 'Julkaise ilmaiseksi', text: 'Perusilmoitus on ilmainen 5 päivän ajan.' }, { title: 'Tavoita ostajat', text: 'Ostajat löytävät koneen haun, kategorian ja markkinan kautta.' }], seoTitle: 'Rakennuskoneet löytyvät helposti', seoText: 'Ilmoita kaivinkoneet, kuormaajat, dumpperit, nosturit ja muut koneet teknisine tietoineen ja kuvineen.', faqTitle: 'Usein kysyttyä rakennuskoneiden myynnistä', faqs: [{ question: 'Onko ilmoittaminen ilmaista?', answer: 'Kyllä. Perusilmoitus on ilmainen 5 päivän ajan.' }, { question: 'Mitä koneita voin myydä?', answer: 'Kaivinkoneita, kuormaajia, dumppe­reita, nostureita ja muita koneita.' }, { question: 'Mitä tietoja kannattaa lisätä?', answer: 'Tyyppi, malli, käyttötunnit, paino, varusteet, hinta, sijainti ja kuvat.' }] },
}

export function getConstructionBenefitsCopy(locale: PublicLocale): ConstructionCopy {
  return copy[locale] || copy.en
}
