import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const catalog = readFileSync(new URL('../lib/billing/product-catalog.ts', import.meta.url), 'utf8')
const checkout = readFileSync(new URL('../app/api/account/listing-checkout/route.ts', import.meta.url), 'utf8')
const webhook = readFileSync(new URL('../app/api/stripe/webhook/route.ts', import.meta.url), 'utf8')
const fulfillment = readFileSync(new URL('../lib/billing/fulfillment.ts', import.meta.url), 'utf8')
const billingEmail = readFileSync(new URL('../lib/email/business-billing.ts', import.meta.url), 'utf8')
const billingCron = readFileSync(new URL('../app/api/cron/business-billing/route.ts', import.meta.url), 'utf8')
const businessInvoiceTerms = readFileSync(new URL('../lib/billing/business-invoice-terms.ts', import.meta.url), 'utf8')
const vercelConfig = readFileSync(new URL('../vercel.json', import.meta.url), 'utf8')
const search = readFileSync(new URL('../lib/marketplace-search-v2.ts', import.meta.url), 'utf8')
const publicData = readFileSync(new URL('../lib/marketplace-public-data.ts', import.meta.url), 'utf8')
const migration = readFileSync(new URL('../supabase/migrations/20260712153000_billing_catalog_orders_and_visibility.sql', import.meta.url), 'utf8')
const quotaMigration = readFileSync(new URL('../supabase/migrations/20260715162000_business_listing_usage_quota.sql', import.meta.url), 'utf8')
const emailMigration = readFileSync(new URL('../supabase/migrations/20260715173500_business_billing_email_deliveries.sql', import.meta.url), 'utf8')
const businessLimits = readFileSync(new URL('../lib/billing/business-limits.ts', import.meta.url), 'utf8')
const businessEntitlement = readFileSync(new URL('../lib/billing/business-entitlement.ts', import.meta.url), 'utf8')
const businessAccountScope = readFileSync(new URL('../lib/billing/business-account-scope.ts', import.meta.url), 'utf8')
const listingRoute = readFileSync(new URL('../app/api/account/listings/route.ts', import.meta.url), 'utf8')
const proxy = readFileSync(new URL('../proxy.ts', import.meta.url), 'utf8')
const home = readFileSync(new URL('../app/components/BusinessMarketplaceHome.tsx', import.meta.url), 'utf8')
const countryFlag = readFileSync(new URL('../app/components/CountryFlag.tsx', import.meta.url), 'utf8')
const publicHeader = readFileSync(new URL('../app/components/PublicHeader.tsx', import.meta.url), 'utf8')
const nextConfig = readFileSync(new URL('../next.config.ts', import.meta.url), 'utf8')
const businessPlanChooser = readFileSync(new URL('../app/konto/business/subscription/BusinessPlanChooser.tsx', import.meta.url), 'utf8')
const newListingForm = readFileSync(new URL('../app/konto/annonser/ny/NewListingForm.tsx', import.meta.url), 'utf8')
const accountListingsPage = readFileSync(new URL('../app/konto/annonser/page.tsx', import.meta.url), 'utf8')
const accountListingsFilters = readFileSync(new URL('../app/konto/annonser/ListingsFilters.tsx', import.meta.url), 'utf8')
const accountListingsI18n = readFileSync(new URL('../lib/account-listings-i18n.ts', import.meta.url), 'utf8')
const listingStatusActions = readFileSync(new URL('../app/konto/annonser/ListingStatusActions.tsx', import.meta.url), 'utf8')
const businessSubscriptionPlans = readFileSync(new URL('../lib/business-subscription-plans.ts', import.meta.url), 'utf8')
const pricingPage = readFileSync(new URL('../app/components/PricingPage.tsx', import.meta.url), 'utf8')
const accountPage = readFileSync(new URL('../app/konto/page.tsx', import.meta.url), 'utf8')
const loginPage = readFileSync(new URL('../app/login/page.tsx', import.meta.url), 'utf8')
const authModal = readFileSync(new URL('../app/components/AuthModal.tsx', import.meta.url), 'utf8')
const emailCodeAuth = readFileSync(new URL('../app/components/EmailCodeAuth.tsx', import.meta.url), 'utf8')
const emailCodeVerifyApi = readFileSync(new URL('../app/api/auth/email-code/verify/route.ts', import.meta.url), 'utf8')
const marketCatchall = readFileSync(new URL('../app/[market]/[...slug]/page.tsx', import.meta.url), 'utf8')
const companyPortal = readFileSync(new URL('../lib/company-portal.tsx', import.meta.url), 'utf8')
const companyOverview = readFileSync(new URL('../app/account/company/page.tsx', import.meta.url), 'utf8')
const companyImport = readFileSync(new URL('../app/account/company/import/page.tsx', import.meta.url), 'utf8')
const companyImportClient = readFileSync(new URL('../app/account/company/import/CompanyImportClient.tsx', import.meta.url), 'utf8')
const companyImportParser = readFileSync(new URL('../lib/company-listing-import.ts', import.meta.url), 'utf8')
const companyImportPreviewApi = readFileSync(new URL('../app/api/account/company/import/preview/route.ts', import.meta.url), 'utf8')
const companyImportApi = readFileSync(new URL('../app/api/account/company/import/route.ts', import.meta.url), 'utf8')
const companyImportLimits = readFileSync(new URL('../lib/company-import-limits.ts', import.meta.url), 'utf8')
const companyAnalytics = readFileSync(new URL('../app/account/company/analytics/page.tsx', import.meta.url), 'utf8')
const companyTeam = readFileSync(new URL('../app/account/company/team/page.tsx', import.meta.url), 'utf8')
const companyTeamInviteApi = readFileSync(new URL('../app/api/account/company/team/invitations/route.ts', import.meta.url), 'utf8')
const companyTeamAcceptApi = readFileSync(new URL('../app/api/account/company/team/accept/route.ts', import.meta.url), 'utf8')
const companyTeamPublicAcceptPage = readFileSync(new URL('../app/company/team/accept/page.tsx', import.meta.url), 'utf8')
const businessTeam = readFileSync(new URL('../lib/business-team.ts', import.meta.url), 'utf8')
const companyTeamAcceptance = readFileSync(new URL('../lib/company-team-acceptance.ts', import.meta.url), 'utf8')
const teamMigration = readFileSync(new URL('../supabase/migrations/20260715200000_business_team_invitations.sql', import.meta.url), 'utf8')

test('market currencies follow URL market requirements', () => {
  for (const [market, currency] of Object.entries({
    se: 'sek',
    dk: 'dkk',
    pl: 'pln',
    de: 'eur',
    fr: 'eur',
    it: 'eur',
    es: 'eur',
    nl: 'eur',
    be: 'eur',
    at: 'eur',
    fi: 'eur',
  })) {
    assert.match(catalog, new RegExp(`${market}: '${currency}'`))
  }
})

test('pricing copy is explicit for every public locale and keeps the five-day free period', () => {
  assert.match(pricingPage, /const copyByLocale: Record<PublicLocale, PricingCopy>/)
  for (const locale of ['sv', 'en', 'de', 'at', 'be', 'fr', 'es', 'it', 'pl', 'nl', 'fi', 'da']) {
    assert.match(pricingPage, new RegExp(`\\n  ${locale}:`))
  }
  assert.match(pricingPage, /startText: '5 days, standard placement\.'/)
  assert.match(pricingPage, /startText: '5 dagar, standardplacering\.'/)
  assert.match(catalog, /listingProduct\(typedCategory, 'start', 5,/)
  assert.doesNotMatch(catalog, /listingProduct\(typedCategory, 'start', 7,/)
  assert.match(checkout, /product\.durationDays \|\| 5/)
  assert.doesNotMatch(checkout, /product\.durationDays \|\| 7/)
})

test('catalog contains required private listing package prices', () => {
  assert.match(catalog, /cars:[\s\S]*standard: \{ sek: 9900, eur: 899, dkk: 6900, pln: 3900 \}/)
  assert.match(catalog, /cars:[\s\S]*premium: \{ sek: 19900, eur: 1799, dkk: 13900, pln: 7900 \}/)
  assert.match(catalog, /construction:[\s\S]*standard: \{ sek: 29900, eur: 2599, dkk: 19900, pln: 11900 \}/)
  assert.match(catalog, /construction:[\s\S]*premium: \{ sek: 69900, eur: 5999, dkk: 47900, pln: 27900 \}/)
})

test('checkout uses server-side catalog/database price lookup and rejects client pricing', () => {
  assert.match(checkout, /resolveBillingPrice\(product, market\)/)
  assert.doesNotMatch(checkout, /body\.amount|body\.currency/)
  assert.match(checkout, /Product does not match listing category/)
  assert.match(checkout, /Free listings do not use Stripe checkout/)
  assert.match(checkout, /price_data/)
  assert.match(checkout, /unit_amount: price\.amountMinor/)
})

test('checkout returns a JSON configuration error instead of a raw server crash', () => {
  assert.match(checkout, /Could not create Stripe checkout session/)
  assert.match(checkout, /Missing STRIPE_SECRET_KEY/)
  assert.match(checkout, /Stripe checkout is not configured for this environment/)
  assert.match(checkout, /\{ status: 503 \}/)
})

test('checkout sessions use Autorell branding and product copy', () => {
  assert.match(checkout, /branding_settings: checkoutBranding/)
  assert.match(checkout, /submit_type: product\.billingType === 'payment' \? 'pay' : undefined/)
  assert.doesNotMatch(checkout, /submit_type: 'pay'/)
  assert.match(checkout, /display_name: 'Autorell'/)
  assert.match(checkout, /button_color: '#0866ff'/)
  assert.match(checkout, /icon: \{[\s\S]*favicon-96\.png/)
  assert.match(checkout, /url: 'https:\/\/www\.autorell\.com\/autorell-logo-primary\.png'/)
  assert.doesNotMatch(checkout, /autorell-brand-logo-color\.png/)
  assert.doesNotMatch(checkout, /autorell-brand-mark-color\.png/)
  assert.doesNotMatch(checkout, /images: \[checkoutBranding\.logo\.url\]/)
  assert.doesNotMatch(checkout, /images: \[checkoutProduct\.imageUrl\]/)
  assert.match(checkout, /billing_address_collection: 'auto'/)
  assert.match(checkout, /customer_creation: product\.billingType === 'payment' \? 'if_required' : undefined/)
  assert.match(checkout, /name: checkoutProduct\.name/)
  assert.match(checkout, /description: checkoutProduct\.description/)
  assert.match(checkout, /checkoutProductCopy\(locale\)/)
  assert.match(checkout, /premiumListing: 'Premiumannons'/)
  assert.match(checkout, /categories: \{ cars: 'Bil'/)
  assert.match(checkout, /standardDescription: 'publicering p.+ Autorells europeiska fordonsmarknad\.'/)
  assert.match(checkout, /premiumListing: 'Premiumanzeige'/)
  assert.match(checkout, /premiumListing: 'Annonce premium'/)
  assert.match(checkout, /premiumListing: 'Anuncio premium'/)
  assert.match(checkout, /premiumListing: 'Premium-ilmoitus'/)
  assert.match(checkout, /standardSubmit: 'Annonsen publiceras automatiskt/)
  assert.doesNotMatch(checkout, /const t = \(value: string\) => translatePublic\(locale, value\)/)
  assert.match(checkout, /name: `\$\{packageLabel\} .+ \$\{categoryLabel\}`/)
  assert.match(checkout, /name: `\$\{copy\.topPlacement\} .+ \$\{days\}`/)
  assert.match(checkout, /name: `\$\{copy\.business\} .+ \$\{capitalize\(plan\)\}`/)
  assert.match(checkout, /checkoutSecurityCopy\(locale\)/)
  assert.match(checkout, /TLS\/SSL/)
  assert.match(checkout, /Autorell never sees or stores your card number/)
  assert.match(checkout, /custom_text: \{[\s\S]*submitText/)
  assert.match(checkout, /after_submit: \{[\s\S]*afterSubmitText/)
  assert.match(checkout, /locale: stripeLocaleForCheckout\(checkoutLocale, market\)/)
  assert.match(checkout, /localizePublicHref\(checkoutLocale/)
})

test('paid account flows show localized Stripe trust messaging before checkout', () => {
  for (const source of [newListingForm, listingStatusActions, businessPlanChooser]) {
    assert.match(source, /TLS\/SSL/)
    assert.match(source, /Stripe/)
    assert.match(source, /Autorell/)
    assert.match(source, /ShieldCheck/)
  }
  for (const locale of ['sv', 'en', 'de', 'fr', 'es', 'it', 'nl', 'pl', 'fi', 'da']) {
    assert.match(newListingForm, new RegExp(`${locale}: \\{[\\s\\S]*Stripe`))
    assert.match(listingStatusActions, new RegExp(`${locale}: \\{[\\s\\S]*Stripe`))
    assert.match(businessPlanChooser, new RegExp(`${locale}: \\{[\\s\\S]*Stripe`))
  }
})

test('account listing management uses active URL market for paid packages and localized copy', () => {
  assert.match(accountListingsPage, /const requestPathname = requestHeaders\.get\('x-autorell-pathname'\)/)
  assert.match(accountListingsPage, /const companyMode = \/\\\/account\\\/company\\\/listings/)
  assert.match(accountListingsPage, /requestHeaders\.get\('x-autorell-market'\)/)
  assert.match(accountListingsPage, /const billingMarket = normalizeBillingMarket/)
  assert.match(accountListingsPage, /const markets = \[billingMarket\]/)
  assert.match(accountListingsPage, /market=\{billingMarket\}/)
  assert.match(accountListingsPage, /packageOptions\(listing, locale, priceMap, billingMarket\)/)
  assert.match(accountListingsPage, /marketingOptions\(listing, locale, priceMap, billingMarket\)/)
  assert.doesNotMatch(accountListingsPage, /market=\{listing\.country_code\.toLowerCase\(\)\}/)
  assert.doesNotMatch(accountListingsPage, /const market = normalizeBillingMarket\(listing\.country_code\)/)
  assert.match(accountListingsPage, /accountListingObject\(locale/)
  assert.match(accountListingsPage, /billingMarketForLocale/)
  assert.match(accountListingsFilters, /accountListingText\(locale/)
  assert.doesNotMatch(accountListingsFilters, /tabLabels\[tab\]\[isSwedish/)
  for (const [locale, title] of Object.entries({
    de: 'Meine Anzeigen',
    fr: 'Mes annonces',
    es: 'Mis anuncios',
    it: 'I miei annunci',
    nl: 'Mijn advertenties',
    pl: 'Moje ogłoszenia',
    fi: 'Omat ilmoitukset',
    da: 'Mine annoncer',
  })) {
    assert.match(accountListingsI18n, new RegExp(`${locale}: \\{[\\s\\S]*${title}`))
  }
  assert.match(accountListingsI18n, /'Search your listings': 'Zoek in je advertenties'/)
  assert.match(accountListingsI18n, /'Awaiting payment': 'Wacht op betaling'/)
  assert.match(accountListingsI18n, /Filters: 'Filters'/)
})

test('business subscriptions support Stripe invoice terms for B2B customers', () => {
  assert.match(businessPlanChooser, /billingMethod: BillingMethod = 'card'/)
  assert.match(businessSubscriptionPlans, /invoice30: 'Invoice 14 days'/)
  assert.match(businessPlanChooser, /invoiceUrl/)
  assert.match(checkout, /billingMethod = body\.billingMethod === 'invoice' \? 'invoice' : 'card'/)
  assert.match(checkout, /billingMethod === 'invoice' && profile\.account_type !== 'business'/)
  assert.match(checkout, /Faktura kan bara användas av företagskonton\./)
  assert.match(checkout, /collection_method: 'send_invoice'/)
  assert.match(businessInvoiceTerms, /BUSINESS_INVOICE_DAYS_UNTIL_DUE = 14/)
  assert.match(checkout, /days_until_due: BUSINESS_INVOICE_DAYS_UNTIL_DUE/)
  assert.match(checkout, /payment_method_types: \['customer_balance'\]/)
  assert.match(checkout, /type: 'eu_bank_transfer'/)
  assert.match(checkout, /bankTransferEnabled/)
  assert.match(checkout, /finalizeInvoice/)
  assert.match(checkout, /sendInvoice/)
  assert.match(checkout, /invoiceEmail/)
  assert.doesNotMatch(checkout, /price: price\.stripePriceId/)
  assert.match(checkout, /stripe\.products\.create\(\{[\s\S]*name: checkoutProduct\.name/)
  assert.match(checkout, /product: stripeProduct\.id/)
  assert.match(checkout, /business_onboarding_status: 'active'/)
  assert.match(webhook, /case 'invoice\.sent':/)
  assert.match(webhook, /upsertBusinessInvoice/)
  assert.match(webhook, /!isInvoiceEvent && object\.status/)
  assert.match(fulfillment, /payment_status: 'paid'/)
})

test('business subscription billing emails cover welcome, invoice, reminders and blocking', () => {
  assert.match(emailMigration, /business_email_deliveries/)
  assert.match(emailMigration, /delivery_key text not null unique/)
  assert.match(emailMigration, /add column if not exists due_at/)
  assert.match(billingEmail, /new Resend/)
  assert.match(billingEmail, /Idempotency-Key/)
  assert.match(billingEmail, /welcomeSubject: \(plan: string\) => `Welcome to Autorell/)
  assert.match(billingEmail, /invoice_ready/)
  assert.match(billingEmail, /payment_receipt/)
  assert.match(billingEmail, /payment_failed/)
  assert.match(billingEmail, /invoice_reminder/)
  assert.match(billingEmail, /account_blocked/)
  assert.match(billingEmail, /cancellation_scheduled/)
  assert.match(checkout, /sendBusinessBillingEmail/)
  assert.match(checkout, /business-welcome-\$\{subscription\.id\}/)
  assert.match(checkout, /business-invoice-ready-\$\{latestInvoice\.id\}/)
  assert.match(fulfillment, /sendBusinessBillingEmail/)
  assert.match(webhook, /business-invoice-ready-\$\{invoice\.id\}/)
  assert.match(webhook, /business-payment-receipt-\$\{invoice\.id\}/)
  assert.match(webhook, /business-payment-failed-\$\{invoice\.id\}/)
  assert.match(billingCron, /CRON_SECRET/)
  assert.match(billingCron, /business-invoice-reminder-\$\{daysLeft\}-\$\{invoice\.stripe_invoice_id\}/)
  assert.match(billingCron, /business-account-blocked-\$\{invoice\.stripe_invoice_id\}/)
  assert.match(billingCron, /status: 'unpaid'/)
  assert.match(billingCron, /payment_status: 'failed'/)
  assert.match(businessLimits, /WARNING_SUBSCRIPTION_STATUSES = new Set\(\['past_due', 'unpaid'\]\)/)
  assert.match(vercelConfig, /"path": "\/api\/cron\/business-billing"/)
})

test('business subscription cards expose five tiered plans with Free kept listing-only', () => {
  assert.match(businessSubscriptionPlans, /key: 'free'/)
  assert.match(businessSubscriptionPlans, /key: 'starter'/)
  assert.match(businessSubscriptionPlans, /key: 'growth'/)
  assert.match(businessSubscriptionPlans, /key: 'professional'/)
  assert.match(businessSubscriptionPlans, /key: 'enterprise'/)
  assert.match(businessSubscriptionPlans, /No company page|Company page/)
  assert.match(businessSubscriptionPlans, /Company page Basic/)
  assert.match(businessSubscriptionPlans, /Company page Plus/)
  assert.match(businessSubscriptionPlans, /Company page Pro/)
  assert.match(businessSubscriptionPlans, /Team accounts/)
  assert.match(businessSubscriptionPlans, /10 team accounts/)
  assert.match(businessSubscriptionPlans, /50\+ team accounts/)
  assert.match(businessSubscriptionPlans, /Reports and export/)
  assert.match(businessSubscriptionPlans, /invoice30: 'Invoice 14 days'/)
  assert.match(businessSubscriptionPlans, /invoiceCreated: 'The invoice has been created and sent to'/)
  assert.match(businessSubscriptionPlans, /annual: 'Annual - save 15%'/)
  assert.match(businessPlanChooser, /current[\s\S]*border-\[#0866ff\]/)
  assert.match(catalog, /subscriptionProduct\('starter', 25,[\s\S]*\}, 'year'\)/)
  assert.match(catalog, /subscriptionProduct\('growth', 100,[\s\S]*\}, 'year'\)/)
  assert.match(catalog, /subscriptionProduct\('professional', 500,[\s\S]*\}, 'year'\)/)
  assert.doesNotMatch(businessPlanChooser, /Sparkles/)
  assert.doesNotMatch(businessPlanChooser, /#10b981|#15803d|text-\[#15803d\]|bg-\[#10b981\]/)
  assert.match(pricingPage, /businessSubscriptionPlans/)
  assert.match(pricingPage, /PublicBusinessPlanCard/)
  assert.match(pricingPage, /billingPeriod === 'annual'/)
  assert.match(pricingPage, /businessCopy\.annual/)
  assert.match(pricingPage, /feature\.included \? <Check/)
  assert.doesNotMatch(pricingPage, /invoice30|payCard|onChoose|listing-checkout/)
  assert.match(pricingPage, /src="\/autorell-pricing-phone-hero\.png"/)
  assert.doesNotMatch(pricingPage, /linear-gradient\(90deg,rgba\(255,255,255/)
  assert.match(pricingPage, /bg-\[#0866ff\][^"]*text-white/)
  assert.match(pricingPage, /hover:border-\[#0866ff\][^"]*hover:text-\[#0866ff\]/)
  assert.match(publicHeader, /isBusinessAccount[\s\S]*account\/company\/subscription/)
  assert.match(accountPage, /profile\.account_type === 'business'[\s\S]*redirectBusinessAccountFromLegacyAccount/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/saved-listings'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/saved-searches'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/payments'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/profile'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/settings'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/support'\)/)
  assert.match(marketCatchall, /slugPath === 'account\/profile'/)
  assert.match(marketCatchall, /slugPath === 'account\/settings'/)
  assert.match(marketCatchall, /slugPath === 'account\/support'/)
  assert.doesNotMatch(accountPage, /title: copy\.plan/)
})

test('business users have a dedicated company portal with localized account routes', () => {
  assert.match(companyPortal, /export async function getCompanyPortalContext/)
  assert.match(companyPortal, /profile\?\.account_type !== 'business'/)
  assert.match(companyPortal, /redirect\(localizePublicHref\(locale, '\/account'\)\)/)
  assert.match(companyPortal, /getAccountListingSummary/)
  assert.match(companyPortal, /resolveBusinessAccountScope\(user\.id, admin\)/)
  assert.match(companyPortal, /\.eq\('user_id', scope\.subscriptionUserId\)/)
  assert.match(companyPortal, /getAccountListingSummary\(admin, scope\.listingOwnerUserIds\)/)
  assert.match(companyPortal, /href: '\/account\/company'/)
  assert.match(companyPortal, /href: '\/account\/company\/listings'/)
  assert.match(companyPortal, /href: '\/account\/company\/listings\/create'/)
  assert.match(companyPortal, /href: '\/account\/company\/import', icon: Upload/)
  assert.match(companyPortal, /href: '\/account\/company\/analytics', icon: BarChart3/)
  assert.match(companyPortal, /href: '\/account\/company\/team'[\s\S]*requiredPlan: 'Growth'/)
  assert.match(companyPortal, /href: '\/account\/company\/subscription'/)
  assert.match(companyPortal, /href: '\/account\/company\/profile'/)
  assert.match(companyPortal, /href: '\/account\/company\/settings'/)
  assert.match(companyPortal, /href: '\/account\/company\/support'/)
  assert.match(companyPortal, /planAllows\(plan, item\.requiredPlan\)/)
  assert.match(companyOverview, /summary\.counts\.active/)
  assert.match(companyOverview, /context\.subscription\?\.active_listing_limit/)
  assert.match(companyOverview, /summary\.totalViews/)
  assert.match(companyImport, /companyImportLimitsForPlan\(context\.subscription\?\.plan_key \|\| 'free'\)/)
  assert.match(companyImportClient, /\/templates\/autorell-business-import\.csv/)
  assert.match(companyAnalytics, /getSellerInsights/)
  assert.match(companyTeam, /LockedFeature[\s\S]*requiredPlan="Growth"/)
  assert.match(companyTeam, /getCompanyTeamOverview/)
  assert.match(companyTeam, /TeamInviteForm/)
  assert.match(marketCatchall, /slugPath === 'account\/company'/)
  assert.match(marketCatchall, /slugPath === 'account\/company\/listings'/)
  assert.match(marketCatchall, /slugPath === 'account\/company\/team\/accept'/)
  assert.match(marketCatchall, /slugPath === 'account\/company\/subscription\/cancel'/)
  assert.match(publicHeader, /isBusinessAccount/)
  assert.match(publicHeader, /\/account\/company\/subscription/)
  assert.match(publicHeader, /\/account\/company\/listings/)
  assert.match(accountPage, /localizePublicHref\(locale, '\/account\/company'\)/)
  assert.match(accountPage, /redirect\(localizePublicHref\(locale, '\/account\/company'\)\)/)
})

test('company team invitations are server-side, seat-limited and token accepted', () => {
  assert.match(teamMigration, /create table if not exists public\.marketplace_company_invitations/)
  assert.match(teamMigration, /token_hash text not null unique/)
  assert.match(teamMigration, /enable row level security/)
  assert.match(teamMigration, /revoke all on public\.marketplace_company_invitations from anon, authenticated/)
  assert.match(businessTeam, /growth: 10/)
  assert.match(businessTeam, /professional: 50/)
  assert.match(businessTeam, /createTeamInvitationToken/)
  assert.match(businessTeam, /hashTeamInvitationToken/)
  assert.match(businessTeam, /sendCompanyTeamInvitationEmail/)
  assert.match(companyTeamInviteApi, /profile\.account_type !== 'business'/)
  assert.match(companyTeamInviteApi, /\['growth', 'professional', 'enterprise'\]\.includes\(planKey\)/)
  assert.match(companyTeamInviteApi, /team\.remainingSeats <= 0/)
  assert.match(companyTeamInviteApi, /token_hash: tokenHash/)
  assert.match(companyTeamInviteApi, /sendCompanyTeamInvitationEmail/)
  assert.doesNotMatch(companyTeamInviteApi, /body\.companyId|body\.planKey|body\.seatLimit/)
  assert.match(businessTeam, /\/company\/team\/accept\?token=/)
  assert.doesNotMatch(businessTeam, /\/account\/company\/team\/accept\?token=/)
  assert.match(companyTeamPublicAcceptPage, /account\/company\/team\/accept\/page/)
  assert.match(marketCatchall, /slugPath === 'company\/team\/accept'/)
  assert.match(loginPage, /safeReturnPath/)
  assert.match(loginPage, /redirect\(`\/\?\$\{params\.toString\(\)\}`\)/)
  assert.match(authModal, /\/api\/auth\/email-code\/request/)
  assert.match(authModal, /\/api\/auth\/email-code\/verify/)
  assert.match(emailCodeAuth, /params\.get\('next'\)/)
  assert.match(emailCodeVerifyApi, /marketplace_company_invitations/)
  assert.match(emailCodeVerifyApi, /requested\.includes\('\/company\/team\/accept'\)/)
  assert.match(emailCodeVerifyApi, /accountType === 'business' \? `\$\{prefix\}\/account\/company`/)
  assert.match(companyTeamAcceptApi, /acceptCompanyTeamInvitationForUser/)
  assert.match(companyTeamAcceptance, /hashTeamInvitationToken\(token\)/)
  assert.match(companyTeamAcceptApi, /user\.email/)
  assert.doesNotMatch(companyTeamAcceptApi, /Skapa Autorell-konto med samma/)
  assert.match(companyTeamAcceptance, /from\('marketplace_company_members'\)[\s\S]*upsert\(\{/)
  assert.match(companyTeamAcceptance, /from\('marketplace_profiles'\)[\s\S]*insert\(\{[\s\S]*user_id: input\.userId/)
  assert.match(companyTeamAcceptance, /business_onboarding_status: 'active'/)
  assert.match(companyTeamAcceptance, /status: 'accepted'/)
})

test('company CSV import is server-side, plan-scoped and quota reserved per draft', () => {
  assert.match(companyImport, /CompanyImportClient/)
  assert.match(companyImport, /companyImportLimitsForPlan/)
  assert.match(companyImportClient, /\/api\/account\/company\/import\/preview/)
  assert.match(companyImportClient, /\/api\/account\/company\/import/)
  assert.match(companyImport, /Import as drafts/)
  assert.match(companyImportParser, /COMPANY_IMPORT_MAX_ROWS = 250/)
  assert.match(companyImportParser, /COMPANY_IMPORT_HEADERS/)
  assert.match(companyImportParser, /parseCsv/)
  assert.match(companyImportParser, /euCountryCodes\.has/)
  assert.match(companyImportParser, /isSupportedCurrency/)
  assert.match(companyImportPreviewApi, /requireBusinessListingEntitlement\(userId\)/)
  assert.match(companyImportPreviewApi, /companyImportLimitsForPlan\(entitlement\.planKey\)/)
  assert.match(companyImportApi, /requireBusinessListingEntitlement\(userId\)/)
  assert.match(companyImportApi, /companyImportLimitsForPlan\(entitlement\.planKey\)/)
  assert.match(companyImportLimits, /free:[\s\S]*maxRows: 10/)
  assert.match(companyImportLimits, /growth:[\s\S]*maxRows: 250/)
  assert.match(companyImportLimits, /enterprise:[\s\S]*maxRows: 1000/)
  assert.match(companyImportApi, /reserveBusinessListingQuota\(user\.id\)/)
  assert.match(companyImportApi, /attachBusinessListingQuotaReservation\(openReservationKey, listing\.id\)/)
  assert.match(companyImportApi, /releaseBusinessListingQuotaReservation\(openReservationKey\)/)
  assert.match(companyImportApi, /status: 'draft'/)
  assert.match(companyImportApi, /event_type: 'company_import_draft_created'/)
  assert.doesNotMatch(companyImportApi, /body\.companyId|body\.planKey|body\.limit|activeListingLimit: body/)
})

test('webhook handling is signature verified and idempotent', () => {
  assert.match(webhook, /request\.headers\.get\('stripe-signature'\)/)
  assert.match(webhook, /process\.env\.STRIPE_WEBHOOK_SECRET/)
  assert.match(webhook, /constructEvent\(/)
  assert.match(webhook, /stripe_webhook_events/)
  assert.match(webhook, /duplicate/)
  assert.match(migration, /stripe_event_id text primary key/)
  assert.match(fulfillment, /Stripe session metadata mismatch/)
  assert.match(fulfillment, /session\.amount_total !== order\.amount_minor/)
  assert.match(fulfillment, /session\.currency[\s\S]*order\.currency/)
})

test('premium fulfillment starts 30-day listing and 7-day boost only when publishable', () => {
  assert.match(fulfillment, /product\.package === 'premium'/)
  assert.match(fulfillment, /product\.includedBoostDays/)
  assert.match(fulfillment, /pending_review/)
  assert.match(catalog, /listingProduct\(typedCategory, 'premium', 30, prices\.premium, 7\)/)
})

test('top placement sorting uses active boost window before normal listings', () => {
  assert.match(search, /searchPublishedWithSponsoredBlock/)
  assert.match(search, /applyActiveTopPlacementFilter/)
  assert.match(search, /\.eq\('boost_status', 'active'\)/)
  assert.match(search, /\.gt\('boost_expires_at', now\)/)
  assert.match(search, /applyNotActiveTopPlacementFilter/)
})

test('featured listings have active-window queries for home and category UI', () => {
  assert.match(publicData, /getFeaturedMarketplaceHomeListings/)
  assert.match(publicData, /getFeaturedMarketplaceCategoryListings/)
  assert.match(publicData, /\.eq\('featured_status', 'active'\)/)
  assert.match(publicData, /\.gt\('featured_expires_at', now\)/)
})

test('home listing cards follow marketplace split-card metadata without mobile carousel widths', () => {
  assert.match(home, /showCountryChip: boolean/)
  assert.match(home, /headline: string/)
  assert.match(home, /versionLabel: string \| null/)
  assert.match(home, /detailItems: string\[\]/)
  assert.match(home, /sellerDetailLabel: string/)
  assert.match(home, /<SavedListingButton/)
  assert.match(home, /buildHomeListingHeadline\(listing\)/)
  assert.match(home, /buildHomeListingVersionLabel\(listing, headline\)/)
  assert.match(home, /item\.detailItems\.join\('\s\| '\)/)
  assert.match(home, /aspect-\[4\/3\] overflow-hidden bg-\[#eef3f8\]/)
  assert.match(home, /showDotsOnMobile\s*\n/)
  assert.match(home, /homeSellerTypeLabel\(locale, listing\.seller_type\)/)
  assert.match(home, /shouldShowListingCountryChip\(listing\.country_code, marketCountryCode\)/)
  assert.match(home, /translateListingVehicleValue\(locale, listing\.fuel_type\)/)
  assert.match(home, /offer_type\?: string \| null/)
  assert.doesNotMatch(home, /w-\[76vw\] max-w-\[280px\]/)
  assert.doesNotMatch(home, /<article className="group relative w-\[76vw\]/)
  assert.doesNotMatch(home, /item\.specChips\.map/)
  assert.doesNotMatch(home, /const offerBadge = homeListingOfferBadge/)
})

test('refresh credits are protected by RPC atomic locks and cooldown', () => {
  assert.match(migration, /for update;/)
  assert.match(migration, /last_refreshed_at > now\(\) - p_cooldown/)
  assert.match(migration, /refresh_credits = refresh_credits - 1/)
  assert.match(migration, /sort_refreshed_at = now\(\)/)
  assert.doesNotMatch(migration, /created_at = now\(\)/)
})

test('client cannot update payment-controlled fields through normal authenticated grants', () => {
  assert.match(migration, /revoke update \([\s\S]*boost_status[\s\S]*featured_status[\s\S]*premium_badge_expires_at[\s\S]*\) on public\.marketplace_listings from authenticated/)
  assert.match(migration, /revoke all on function public\.increment_refresh_credits/)
  assert.match(migration, /grant execute on function public\.increment_refresh_credits[\s\S]*to service_role/)
})

test('business listing limits are enforced through a monthly database quota ledger', () => {
  assert.match(businessLimits, /starter: 25/)
  assert.match(businessLimits, /growth: 100/)
  assert.match(businessLimits, /professional: 500/)
  assert.match(businessAccountScope, /marketplace_companies'[\s\S]*created_by/)
  assert.match(businessAccountScope, /marketplace_company_members'[\s\S]*select\('user_id'\)/)
  assert.match(businessAccountScope, /subscriptionUserId = String\(company\?\.created_by \|\| userId\)/)
  assert.match(businessAccountScope, /listingOwnerUserIds = Array\.from\(new Set/)
  assert.match(businessEntitlement, /resolveBusinessAccountScope\(userId, admin\)/)
  assert.match(businessEntitlement, /\.eq\('user_id', scope\.subscriptionUserId\)/)
  assert.match(businessEntitlement, /\.in\('seller_user_id', userIds\.length \? userIds/)
  assert.match(quotaMigration, /create table if not exists public\.business_listing_usage_ledger/)
  assert.match(quotaMigration, /reserve_business_listing_quota/)
  assert.match(quotaMigration, /for update;/)
  assert.match(quotaMigration, /period_start/)
  assert.match(quotaMigration, /period_end/)
  assert.match(quotaMigration, /event_type in \('reserved', 'released'\)/)
  assert.match(quotaMigration, /grant execute on function public\.reserve_business_listing_quota[\s\S]*to service_role/)
  assert.match(businessLimits, /reserveBusinessListingQuota/)
  assert.match(businessLimits, /resolveBusinessAccountScope\(userId, admin\)/)
  assert.match(businessLimits, /p_user_id: scope\.subscriptionUserId/)
  assert.match(businessLimits, /\.in\('seller_user_id', scope\.listingOwnerUserIds\.length \? scope\.listingOwnerUserIds/)
  assert.match(businessLimits, /attachBusinessListingQuotaReservation/)
  assert.match(businessLimits, /releaseBusinessListingQuotaReservation/)
  assert.match(listingRoute, /reserveBusinessListingQuota\(user\.id\)/)
  assert.match(listingRoute, /attachBusinessListingQuotaReservation\(quotaReservation\.reservationKey, listing\.id\)/)
  assert.doesNotMatch(listingRoute, /import \{ checkBusinessListingPublicationLimit \}/)
})

test('canonical English pricing routes do not redirect to themselves', () => {
  assert.match(proxy, /isPublicLanguage\(targetMarket \|\| ''\) &&\s*targetMarket !== 'en'/)
  assert.match(proxy, /targetMarket === 'sv' \? 'se' : targetMarket/)
  assert.doesNotMatch(proxy, /targetMarket === 'en' \? pathname/)
})

test('EU home sections and browser-only header state hydrate deterministically', () => {
  assert.match(home, /const homeListingCategories: MarketplaceCategorySlug\[\] = \[/)
  assert.match(home, /HomeListingCategorySwitcher categories=\{homeListingCategories\}/)
  assert.match(home, /localListingSectionsByCategory\.get\(category\)\?\.latest/)
  assert.match(home, /localListingSectionsByCategory\.get\(category\)\?\.top/)
  assert.match(home, /key=\{section\.id\}/)
  assert.match(home, /getPublishedMarketplaceHomeListings\(localMarketCode, 'top', 17, category\)/)
  assert.match(home, /getPublishedMarketplaceHomeListings\(localMarketCode, 'latest', 17, category\)/)
  assert.match(home, /const visibleItems = section\.items\.slice\(0, 16\)/)
  assert.match(home, /homeLoadMoreListingsLabel\(locale\)/)
  assert.match(home, /grid grid-cols-2 gap-3 sm:gap-4 lg:grid-cols-4 lg:gap-5/)
  assert.match(home, /index >= 8 \? 'max-sm:hidden' : ''/)
  assert.doesNotMatch(home, /mt-5 flex snap-x gap-4 overflow-x-auto/)
  assert.match(countryFlag, /\.toFixed\(4\)/)
  assert.match(publicHeader, /useState<HeaderAccount>\(emptyHeaderAccount\)/)
  assert.match(publicHeader, /useState\(true\)/)
})

test('content security policy allows the MapLibre blob worker', () => {
  assert.match(nextConfig, /worker-src 'self' blob:/)
})

