import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const catalog = readFileSync(new URL('../lib/billing/product-catalog.ts', import.meta.url), 'utf8')
const checkout = readFileSync(new URL('../app/api/account/listing-checkout/route.ts', import.meta.url), 'utf8')
const webhook = readFileSync(new URL('../app/api/stripe/webhook/route.ts', import.meta.url), 'utf8')
const fulfillment = readFileSync(new URL('../lib/billing/fulfillment.ts', import.meta.url), 'utf8')
const billingEmail = readFileSync(new URL('../lib/email/business-billing.ts', import.meta.url), 'utf8')
const billingCron = readFileSync(new URL('../app/api/cron/business-billing/route.ts', import.meta.url), 'utf8')
const vercelConfig = readFileSync(new URL('../vercel.json', import.meta.url), 'utf8')
const search = readFileSync(new URL('../lib/marketplace-search-v2.ts', import.meta.url), 'utf8')
const publicData = readFileSync(new URL('../lib/marketplace-public-data.ts', import.meta.url), 'utf8')
const migration = readFileSync(new URL('../supabase/migrations/20260712153000_billing_catalog_orders_and_visibility.sql', import.meta.url), 'utf8')
const quotaMigration = readFileSync(new URL('../supabase/migrations/20260715162000_business_listing_usage_quota.sql', import.meta.url), 'utf8')
const emailMigration = readFileSync(new URL('../supabase/migrations/20260715173500_business_billing_email_deliveries.sql', import.meta.url), 'utf8')
const businessLimits = readFileSync(new URL('../lib/billing/business-limits.ts', import.meta.url), 'utf8')
const businessEntitlement = readFileSync(new URL('../lib/billing/business-entitlement.ts', import.meta.url), 'utf8')
const businessAccountScope = readFileSync(new URL('../lib/billing/business-account-scope.ts', import.meta.url), 'utf8')
const listingRoute = readFileSync(new URL('../app/api/account/listings/route.ts', import.meta.url), 'utf8')
const proxy = readFileSync(new URL('../proxy.ts', import.meta.url), 'utf8')
const home = readFileSync(new URL('../app/components/BusinessMarketplaceHome.tsx', import.meta.url), 'utf8')
const countryFlag = readFileSync(new URL('../app/components/CountryFlag.tsx', import.meta.url), 'utf8')
const publicHeader = readFileSync(new URL('../app/components/PublicHeader.tsx', import.meta.url), 'utf8')
const nextConfig = readFileSync(new URL('../next.config.ts', import.meta.url), 'utf8')
const businessPlanChooser = readFileSync(new URL('../app/konto/business/subscription/BusinessPlanChooser.tsx', import.meta.url), 'utf8')
const accountPage = readFileSync(new URL('../app/konto/page.tsx', import.meta.url), 'utf8')
const loginPage = readFileSync(new URL('../app/login/page.tsx', import.meta.url), 'utf8')
const authModal = readFileSync(new URL('../app/components/AuthModal.tsx', import.meta.url), 'utf8')
const emailCodeAuth = readFileSync(new URL('../app/components/EmailCodeAuth.tsx', import.meta.url), 'utf8')
const emailCodeVerifyApi = readFileSync(new URL('../app/api/auth/email-code/verify/route.ts', import.meta.url), 'utf8')
const marketCatchall = readFileSync(new URL('../app/[market]/[...slug]/page.tsx', import.meta.url), 'utf8')
const companyPortal = readFileSync(new URL('../lib/company-portal.tsx', import.meta.url), 'utf8')
const companyOverview = readFileSync(new URL('../app/account/company/page.tsx', import.meta.url), 'utf8')
const companyImport = readFileSync(new URL('../app/account/company/import/page.tsx', import.meta.url), 'utf8')
const companyImportClient = readFileSync(new URL('../app/account/company/import/CompanyImportClient.tsx', import.meta.url), 'utf8')
const companyImportParser = readFileSync(new URL('../lib/company-listing-import.ts', import.meta.url), 'utf8')
const companyImportPreviewApi = readFileSync(new URL('../app/api/account/company/import/preview/route.ts', import.meta.url), 'utf8')
const companyImportApi = readFileSync(new URL('../app/api/account/company/import/route.ts', import.meta.url), 'utf8')
const companyAnalytics = readFileSync(new URL('../app/account/company/analytics/page.tsx', import.meta.url), 'utf8')
const companyTeam = readFileSync(new URL('../app/account/company/team/page.tsx', import.meta.url), 'utf8')
const companyTeamInviteApi = readFileSync(new URL('../app/api/account/company/team/invitations/route.ts', import.meta.url), 'utf8')
const companyTeamAcceptApi = readFileSync(new URL('../app/api/account/company/team/accept/route.ts', import.meta.url), 'utf8')
const companyTeamPublicAcceptPage = readFileSync(new URL('../app/company/team/accept/page.tsx', import.meta.url), 'utf8')
const businessTeam = readFileSync(new URL('../lib/business-team.ts', import.meta.url), 'utf8')
const teamMigration = readFileSync(new URL('../supabase/migrations/20260715200000_business_team_invitations.sql', import.meta.url), 'utf8')

test('market currencies follow URL market requirements', () => {
  for (const [market, currency] of Object.entries({
    se: 'sek',
    dk: 'dkk',
    pl: 'pln',
    de: 'eur',
    fr: 'eur',
    it: 'eur',
    es: 'eur',
    nl: 'eur',
    be: 'eur',
    at: 'eur',
    fi: 'eur',
  })) {
    assert.match(catalog, new RegExp(`${market}: '${currency}'`))
  }
})

test('catalog contains required private listing package prices', () => {
  assert.match(catalog, /cars:[\s\S]*standard: \{ sek: 9900, eur: 899, dkk: 6900, pln: 3900 \}/)
  assert.match(catalog, /cars:[\s\S]*premium: \{ sek: 19900, eur: 1799, dkk: 13900, pln: 7900 \}/)
  assert.match(catalog, /construction:[\s\S]*standard: \{ sek: 29900, eur: 2599, dkk: 19900, pln: 11900 \}/)
  assert.match(catalog, /construction:[\s\S]*premium: \{ sek: 69900, eur: 5999, dkk: 47900, pln: 27900 \}/)
})

test('checkout uses server-side catalog/database price lookup and rejects client pricing', () => {
  assert.match(checkout, /resolveBillingPrice\(product, market\)/)
  assert.doesNotMatch(checkout, /body\.amount|body\.currency/)
  assert.match(checkout, /Product does not match listing category/)
  assert.match(checkout, /Free listings do not use Stripe checkout/)
  assert.match(checkout, /price_data/)
  assert.match(checkout, /unit_amount: price\.amountMinor/)
})

test('checkout returns a JSON configuration error instead of a raw server crash', () => {
  assert.match(checkout, /Could not create Stripe checkout session/)
  assert.match(checkout, /Missing STRIPE_SECRET_KEY/)
  assert.match(checkout, /Stripe checkout is not configured for this environment/)
  assert.match(checkout, /\{ status: 503 \}/)
})

test('checkout sessions use Autorell branding and product copy', () => {
  assert.match(checkout, /branding_settings: checkoutBranding/)
  assert.match(checkout, /submit_type: product\.billingType === 'payment' \? 'pay' : undefined/)
  assert.doesNotMatch(checkout, /submit_type: 'pay'/)
  assert.match(checkout, /display_name: 'Autorell'/)
  assert.match(checkout, /button_color: '#0866ff'/)
  assert.match(checkout, /url: 'https:\/\/www\.autorell\.com\/autorell-logo-primary\.png'/)
  assert.doesNotMatch(checkout, /autorell-brand-logo-color\.png/)
  assert.doesNotMatch(checkout, /images: \[checkoutBranding\.logo\.url\]/)
  assert.match(checkout, /name: checkoutProduct\.name/)
  assert.match(checkout, /description: checkoutProduct\.description/)
  assert.match(checkout, /packageLabel = packageName === 'premium' \? 'Premiumannons' : 'Standardannons'/)
  assert.match(checkout, /name: `\$\{packageLabel\} .+ \$\{categoryLabel\}`/)
  assert.match(checkout, /name: `Topplacering .+ \$\{days\}`/)
  assert.match(checkout, /name: `F.+retag .+ \$\{capitalize\(plan\)\}`/)
  assert.match(checkout, /custom_text: \{[\s\S]*submitText/)
  assert.match(checkout, /after_submit: \{[\s\S]*betalning via Stripe/)
  assert.match(checkout, /locale: stripeLocaleForMarket\(market\)/)
})

test('business subscriptions support Stripe invoice terms for B2B customers', () => {
  assert.match(businessPlanChooser, /billingMethod: BillingMethod = 'card'/)
  assert.match(businessPlanChooser, /invoice30: 'Invoice 30 days'/)
  assert.match(businessPlanChooser, /invoiceUrl/)
  assert.match(checkout, /billingMethod = body\.billingMethod === 'invoice' \? 'invoice' : 'card'/)
  assert.match(checkout, /billingMethod === 'invoice' && profile\.account_type !== 'business'/)
  assert.match(checkout, /Faktura kan bara användas av företagskonton\./)
  assert.match(checkout, /collection_method: 'send_invoice'/)
  assert.match(checkout, /days_until_due: 30/)
  assert.match(checkout, /payment_method_types: \['customer_balance'\]/)
  assert.match(checkout, /type: 'eu_bank_transfer'/)
  assert.match(checkout, /bankTransferEnabled/)
  assert.match(checkout, /finalizeInvoice/)
  assert.match(checkout, /sendInvoice/)
  assert.match(checkout, /invoiceEmail/)
  assert.match(checkout, /price\.stripePriceId/)
  assert.match(checkout, /business_onboarding_status: 'active'/)
  assert.match(webhook, /case 'invoice\.sent':/)
  assert.match(webhook, /upsertBusinessInvoice/)
  assert.match(webhook, /!isInvoiceEvent && object\.status/)
  assert.match(fulfillment, /payment_status: 'paid'/)
})

test('business subscription billing emails cover welcome, invoice, reminders and blocking', () => {
  assert.match(emailMigration, /business_email_deliveries/)
  assert.match(emailMigration, /delivery_key text not null unique/)
  assert.match(emailMigration, /add column if not exists due_at/)
  assert.match(billingEmail, /new Resend/)
  assert.match(billingEmail, /Idempotency-Key/)
  assert.match(billingEmail, /welcomeSubject: \(plan: string\) => `Welcome to Autorell/)
  assert.match(billingEmail, /invoice_ready/)
  assert.match(billingEmail, /payment_receipt/)
  assert.match(billingEmail, /payment_failed/)
  assert.match(billingEmail, /invoice_reminder/)
  assert.match(billingEmail, /account_blocked/)
  assert.match(billingEmail, /cancellation_scheduled/)
  assert.match(checkout, /sendBusinessBillingEmail/)
  assert.match(checkout, /business-welcome-\$\{subscription\.id\}/)
  assert.match(checkout, /business-invoice-ready-\$\{latestInvoice\.id\}/)
  assert.match(fulfillment, /sendBusinessBillingEmail/)
  assert.match(webhook, /business-invoice-ready-\$\{invoice\.id\}/)
  assert.match(webhook, /business-payment-receipt-\$\{invoice\.id\}/)
  assert.match(webhook, /business-payment-failed-\$\{invoice\.id\}/)
  assert.match(billingCron, /CRON_SECRET/)
  assert.match(billingCron, /business-invoice-reminder-\$\{daysLeft\}-\$\{invoice\.stripe_invoice_id\}/)
  assert.match(billingCron, /business-account-blocked-\$\{invoice\.stripe_invoice_id\}/)
  assert.match(billingCron, /business_onboarding_status: 'suspended'/)
  assert.match(vercelConfig, /"path": "\/api\/cron\/business-billing"/)
})

test('business subscription cards expose five tiered plans with Free kept listing-only', () => {
  assert.match(businessPlanChooser, /key: 'free'/)
  assert.match(businessPlanChooser, /key: 'starter'/)
  assert.match(businessPlanChooser, /key: 'growth'/)
  assert.match(businessPlanChooser, /key: 'professional'/)
  assert.match(businessPlanChooser, /key: 'enterprise'/)
  assert.match(businessPlanChooser, /No company page|Company page/)
  assert.match(businessPlanChooser, /Company page Basic/)
  assert.match(businessPlanChooser, /Company page Plus/)
  assert.match(businessPlanChooser, /Company page Pro/)
  assert.match(businessPlanChooser, /Team accounts/)
  assert.match(businessPlanChooser, /10 team accounts/)
  assert.match(businessPlanChooser, /50\+ team accounts/)
  assert.match(businessPlanChooser, /Reports and export/)
  assert.match(businessPlanChooser, /invoice30: 'Invoice 30 days'/)
  assert.match(businessPlanChooser, /invoiceCreated: 'The invoice has been created and sent to'/)
  assert.match(businessPlanChooser, /annual: 'Annual - save 15%'/)
  assert.match(businessPlanChooser, /current[\s\S]*border-\[#0866ff\]/)
  assert.match(catalog, /subscriptionProduct\('starter', 25,[\s\S]*\}, 'year'\)/)
  assert.match(catalog, /subscriptionProduct\('growth', 100,[\s\S]*\}, 'year'\)/)
  assert.match(catalog, /subscriptionProduct\('professional', 500,[\s\S]*\}, 'year'\)/)
  assert.doesNotMatch(businessPlanChooser, /Sparkles/)
  assert.doesNotMatch(businessPlanChooser, /#10b981|#15803d|text-\[#15803d\]|bg-\[#10b981\]/)
  assert.match(publicHeader, /isBusinessAccount[\s\S]*account\/company\/subscription/)
  assert.match(accountPage, /profile\.account_type === 'business'[\s\S]*redirectBusinessAccountFromLegacyAccount/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/saved-listings'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/saved-searches'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/payments'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/profile'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/settings'\)/)
  assert.match(accountPage, /href: localizePublicHref\(locale, '\/account\/support'\)/)
  assert.match(marketCatchall, /slugPath === 'account\/profile'/)
  assert.match(marketCatchall, /slugPath === 'account\/settings'/)
  assert.match(marketCatchall, /slugPath === 'account\/support'/)
  assert.doesNotMatch(accountPage, /title: copy\.plan/)
})

test('business users have a dedicated company portal with localized account routes', () => {
  assert.match(companyPortal, /export async function getCompanyPortalContext/)
  assert.match(companyPortal, /profile\?\.account_type !== 'business'/)
  assert.match(companyPortal, /redirect\(localizePublicHref\(locale, '\/account'\)\)/)
  assert.match(companyPortal, /getAccountListingSummary/)
  assert.match(companyPortal, /resolveBusinessAccountScope\(user\.id, admin\)/)
  assert.match(companyPortal, /\.eq\('user_id', scope\.subscriptionUserId\)/)
  assert.match(companyPortal, /getAccountListingSummary\(admin, scope\.listingOwnerUserIds\)/)
  assert.match(companyPortal, /href: '\/account\/company'/)
  assert.match(companyPortal, /href: '\/account\/company\/listings'/)
  assert.match(companyPortal, /href: '\/account\/company\/listings\/create'/)
  assert.match(companyPortal, /href: '\/account\/company\/import'[\s\S]*requiredPlan: 'Growth'/)
  assert.match(companyPortal, /href: '\/account\/company\/analytics'[\s\S]*requiredPlan: 'Growth'/)
  assert.match(companyPortal, /href: '\/account\/company\/team'[\s\S]*requiredPlan: 'Growth'/)
  assert.match(companyPortal, /href: '\/account\/company\/subscription'/)
  assert.match(companyPortal, /href: '\/account\/company\/profile'/)
  assert.match(companyPortal, /href: '\/account\/company\/settings'/)
  assert.match(companyPortal, /href: '\/account\/company\/support'/)
  assert.match(companyPortal, /planAllows\(plan, item\.requiredPlan\)/)
  assert.match(companyOverview, /summary\.counts\.active/)
  assert.match(companyOverview, /context\.subscription\?\.active_listing_limit/)
  assert.match(companyOverview, /summary\.totalViews/)
  assert.match(companyImport, /LockedFeature[\s\S]*requiredPlan="Growth"/)
  assert.match(companyImportClient, /\/templates\/autorell-business-import\.csv/)
  assert.match(companyAnalytics, /LockedFeature[\s\S]*requiredPlan="Growth"/)
  assert.match(companyTeam, /LockedFeature[\s\S]*requiredPlan="Growth"/)
  assert.match(companyTeam, /getCompanyTeamOverview/)
  assert.match(companyTeam, /TeamInviteForm/)
  assert.match(marketCatchall, /slugPath === 'account\/company'/)
  assert.match(marketCatchall, /slugPath === 'account\/company\/listings'/)
  assert.match(marketCatchall, /slugPath === 'account\/company\/team\/accept'/)
  assert.match(marketCatchall, /slugPath === 'account\/company\/subscription\/cancel'/)
  assert.match(publicHeader, /isBusinessAccount/)
  assert.match(publicHeader, /\/account\/company\/subscription/)
  assert.match(publicHeader, /\/account\/company\/listings/)
  assert.match(accountPage, /localizePublicHref\(locale, '\/account\/company'\)/)
  assert.match(accountPage, /redirect\(localizePublicHref\(locale, '\/account\/company'\)\)/)
})

test('company team invitations are server-side, seat-limited and token accepted', () => {
  assert.match(teamMigration, /create table if not exists public\.marketplace_company_invitations/)
  assert.match(teamMigration, /token_hash text not null unique/)
  assert.match(teamMigration, /enable row level security/)
  assert.match(teamMigration, /revoke all on public\.marketplace_company_invitations from anon, authenticated/)
  assert.match(businessTeam, /growth: 10/)
  assert.match(businessTeam, /professional: 50/)
  assert.match(businessTeam, /createTeamInvitationToken/)
  assert.match(businessTeam, /hashTeamInvitationToken/)
  assert.match(businessTeam, /sendCompanyTeamInvitationEmail/)
  assert.match(companyTeamInviteApi, /profile\.account_type !== 'business'/)
  assert.match(companyTeamInviteApi, /\['growth', 'professional', 'enterprise'\]\.includes\(planKey\)/)
  assert.match(companyTeamInviteApi, /team\.remainingSeats <= 0/)
  assert.match(companyTeamInviteApi, /token_hash: tokenHash/)
  assert.match(companyTeamInviteApi, /sendCompanyTeamInvitationEmail/)
  assert.doesNotMatch(companyTeamInviteApi, /body\.companyId|body\.planKey|body\.seatLimit/)
  assert.match(businessTeam, /\/company\/team\/accept\?token=/)
  assert.doesNotMatch(businessTeam, /\/account\/company\/team\/accept\?token=/)
  assert.match(companyTeamPublicAcceptPage, /account\/company\/team\/accept\/page/)
  assert.match(marketCatchall, /slugPath === 'company\/team\/accept'/)
  assert.match(loginPage, /redirect\('\/\?auth=login'\)/)
  assert.match(authModal, /\/api\/auth\/email-code\/request/)
  assert.match(authModal, /\/api\/auth\/email-code\/verify/)
  assert.match(emailCodeAuth, /params\.get\('next'\)/)
  assert.match(emailCodeVerifyApi, /marketplace_company_invitations/)
  assert.match(emailCodeVerifyApi, /requested\.includes\('\/company\/team\/accept'\)/)
  assert.match(emailCodeVerifyApi, /accountType === 'business' \? `\$\{prefix\}\/account\/company`/)
  assert.match(companyTeamAcceptApi, /hashTeamInvitationToken\(token\)/)
  assert.match(companyTeamAcceptApi, /user\.email/)
  assert.doesNotMatch(companyTeamAcceptApi, /Skapa Autorell-konto med samma/)
  assert.match(companyTeamAcceptApi, /from\('marketplace_company_members'\)[\s\S]*upsert\(\{/)
  assert.match(companyTeamAcceptApi, /from\('marketplace_profiles'\)[\s\S]*insert\(\{[\s\S]*user_id: user\.id/)
  assert.match(companyTeamAcceptApi, /business_onboarding_status: 'active'/)
  assert.match(companyTeamAcceptApi, /status: 'accepted'/)
})

test('company CSV import is server-side, Growth gated and quota reserved per draft', () => {
  assert.match(companyImport, /CompanyImportClient/)
  assert.match(companyImport, /LockedFeature[\s\S]*requiredPlan="Growth"/)
  assert.match(companyImportClient, /\/api\/account\/company\/import\/preview/)
  assert.match(companyImportClient, /\/api\/account\/company\/import/)
  assert.match(companyImport, /Import as drafts/)
  assert.match(companyImportParser, /COMPANY_IMPORT_MAX_ROWS = 250/)
  assert.match(companyImportParser, /COMPANY_IMPORT_HEADERS/)
  assert.match(companyImportParser, /parseCsv/)
  assert.match(companyImportParser, /euCountryCodes\.has/)
  assert.match(companyImportParser, /isSupportedCurrency/)
  assert.match(companyImportPreviewApi, /requireBusinessListingEntitlement\(userId\)/)
  assert.match(companyImportPreviewApi, /planAllows\(entitlement\.planKey, 'growth'\)/)
  assert.match(companyImportApi, /requireBusinessListingEntitlement\(userId\)/)
  assert.match(companyImportApi, /planAllows\(entitlement\.planKey, 'growth'\)/)
  assert.match(companyImportApi, /reserveBusinessListingQuota\(user\.id\)/)
  assert.match(companyImportApi, /attachBusinessListingQuotaReservation\(openReservationKey, listing\.id\)/)
  assert.match(companyImportApi, /releaseBusinessListingQuotaReservation\(openReservationKey\)/)
  assert.match(companyImportApi, /status: 'draft'/)
  assert.match(companyImportApi, /event_type: 'company_import_draft_created'/)
  assert.doesNotMatch(companyImportApi, /body\.companyId|body\.planKey|body\.limit|activeListingLimit: body/)
})

test('webhook handling is signature verified and idempotent', () => {
  assert.match(webhook, /request\.headers\.get\('stripe-signature'\)/)
  assert.match(webhook, /process\.env\.STRIPE_WEBHOOK_SECRET/)
  assert.match(webhook, /constructEvent\(/)
  assert.match(webhook, /stripe_webhook_events/)
  assert.match(webhook, /duplicate/)
  assert.match(migration, /stripe_event_id text primary key/)
  assert.match(fulfillment, /Stripe session metadata mismatch/)
  assert.match(fulfillment, /session\.amount_total !== order\.amount_minor/)
  assert.match(fulfillment, /session\.currency[\s\S]*order\.currency/)
})

test('premium fulfillment starts 30-day listing and 7-day boost only when publishable', () => {
  assert.match(fulfillment, /product\.package === 'premium'/)
  assert.match(fulfillment, /product\.includedBoostDays/)
  assert.match(fulfillment, /pending_review/)
  assert.match(catalog, /listingProduct\(typedCategory, 'premium', 30, prices\.premium, 7\)/)
})

test('top placement sorting uses active boost window before normal listings', () => {
  assert.match(search, /searchPublishedWithSponsoredBlock/)
  assert.match(search, /applyActiveTopPlacementFilter/)
  assert.match(search, /\.eq\('boost_status', 'active'\)/)
  assert.match(search, /\.gt\('boost_expires_at', now\)/)
  assert.match(search, /applyNotActiveTopPlacementFilter/)
})

test('featured listings have active-window queries for home and category UI', () => {
  assert.match(publicData, /getFeaturedMarketplaceHomeListings/)
  assert.match(publicData, /getFeaturedMarketplaceCategoryListings/)
  assert.match(publicData, /\.eq\('featured_status', 'active'\)/)
  assert.match(publicData, /\.gt\('featured_expires_at', now\)/)
})

test('refresh credits are protected by RPC atomic locks and cooldown', () => {
  assert.match(migration, /for update;/)
  assert.match(migration, /last_refreshed_at > now\(\) - p_cooldown/)
  assert.match(migration, /refresh_credits = refresh_credits - 1/)
  assert.match(migration, /sort_refreshed_at = now\(\)/)
  assert.doesNotMatch(migration, /created_at = now\(\)/)
})

test('client cannot update payment-controlled fields through normal authenticated grants', () => {
  assert.match(migration, /revoke update \([\s\S]*boost_status[\s\S]*featured_status[\s\S]*premium_badge_expires_at[\s\S]*\) on public\.marketplace_listings from authenticated/)
  assert.match(migration, /revoke all on function public\.increment_refresh_credits/)
  assert.match(migration, /grant execute on function public\.increment_refresh_credits[\s\S]*to service_role/)
})

test('business listing limits are enforced through a monthly database quota ledger', () => {
  assert.match(businessLimits, /starter: 25/)
  assert.match(businessLimits, /growth: 100/)
  assert.match(businessLimits, /professional: 500/)
  assert.match(businessAccountScope, /marketplace_companies'[\s\S]*created_by/)
  assert.match(businessAccountScope, /marketplace_company_members'[\s\S]*select\('user_id'\)/)
  assert.match(businessAccountScope, /subscriptionUserId = String\(company\?\.created_by \|\| userId\)/)
  assert.match(businessAccountScope, /listingOwnerUserIds = Array\.from\(new Set/)
  assert.match(businessEntitlement, /resolveBusinessAccountScope\(userId, admin\)/)
  assert.match(businessEntitlement, /\.eq\('user_id', scope\.subscriptionUserId\)/)
  assert.match(businessEntitlement, /\.in\('seller_user_id', userIds\.length \? userIds/)
  assert.match(quotaMigration, /create table if not exists public\.business_listing_usage_ledger/)
  assert.match(quotaMigration, /reserve_business_listing_quota/)
  assert.match(quotaMigration, /for update;/)
  assert.match(quotaMigration, /period_start/)
  assert.match(quotaMigration, /period_end/)
  assert.match(quotaMigration, /event_type in \('reserved', 'released'\)/)
  assert.match(quotaMigration, /grant execute on function public\.reserve_business_listing_quota[\s\S]*to service_role/)
  assert.match(businessLimits, /reserveBusinessListingQuota/)
  assert.match(businessLimits, /resolveBusinessAccountScope\(userId, admin\)/)
  assert.match(businessLimits, /p_user_id: scope\.subscriptionUserId/)
  assert.match(businessLimits, /\.in\('seller_user_id', scope\.listingOwnerUserIds\.length \? scope\.listingOwnerUserIds/)
  assert.match(businessLimits, /attachBusinessListingQuotaReservation/)
  assert.match(businessLimits, /releaseBusinessListingQuotaReservation/)
  assert.match(listingRoute, /reserveBusinessListingQuota\(user\.id\)/)
  assert.match(listingRoute, /attachBusinessListingQuotaReservation\(quotaReservation\.reservationKey, listing\.id\)/)
  assert.doesNotMatch(listingRoute, /import \{ checkBusinessListingPublicationLimit \}/)
})

test('canonical English pricing routes do not redirect to themselves', () => {
  assert.match(proxy, /isPublicLanguage\(targetMarket \|\| ''\) &&\s*targetMarket !== 'en'/)
  assert.match(proxy, /targetMarket === 'sv' \? 'se' : targetMarket/)
  assert.doesNotMatch(proxy, /targetMarket === 'en' \? pathname/)
})

test('EU home sections and browser-only header state hydrate deterministically', () => {
  assert.match(home, /localMarketCode === 'EU'[\s\S]*\? localListingSections/)
  assert.match(home, /key=\{section\.id\}/)
  assert.match(countryFlag, /\.toFixed\(4\)/)
  assert.match(publicHeader, /useState<HeaderAccount>\(emptyHeaderAccount\)/)
  assert.match(publicHeader, /useState\(true\)/)
})

test('content security policy allows the MapLibre blob worker', () => {
  assert.match(nextConfig, /worker-src 'self' blob:/)
})
