import { translationLocale, type PublicLocale } from '@/lib/public-i18n'

export type DealerOffersCopy = {
  title: string
  description: string
  lockedText: string
  planBadge: string
  introTitle: string
  introText: string
  noRequestsTitle: string
  noRequestsText: string
  viewPublicPage: string
  workflowTitle: string
  workflow: string[]
  notificationsTitle: string
  notificationsText: string
  emailEnabled: string
  emailLabel: string
  emailPlaceholder: string
  scopeLabel: string
  scopeHome: string
  scopeSelected: string
  scopeAll: string
  countriesLabel: string
  save: string
  saving: string
  saved: string
  saveError: string
  call: string
  sendEmail: string
  images: string
  noImages: string
  vehicleDetails: string
  conditionHistory: string
  contactDetails: string
  country: string
  contactTracking: DealerLeadContactTrackingCopy
  labels: Record<string, string>
  statuses: Record<string, string>
}

export type DealerLeadContactTrackingCopy = {
  label: string
  help: string
  markedBy: string
  visibleUntil: string
  saving: string
  error: string
}

const en: DealerOffersCopy = {
  title: 'Dealer offers',
  description: 'Review seller requests, vehicle condition, photos and contact details.',
  lockedText: 'Dealer requests are available from Growth and above. Upgrade to receive seller requests in the company portal.',
  planBadge: 'Growth and above',
  introTitle: 'Incoming vehicle requests',
  introText: 'Requests are matched to your selected countries. Contact the seller directly by phone or email.',
  noRequestsTitle: 'No matching requests yet',
  noRequestsText: 'New seller requests from your selected countries will appear here.',
  viewPublicPage: 'View seller page',
  workflowTitle: 'Recommended follow-up',
  workflow: ['Check the vehicle and condition before contacting the seller.', 'Review notes and photos before making an offer.', 'Respond quickly and agree the next step directly with the seller.'],
  notificationsTitle: 'Lead notifications', notificationsText: 'Choose where you want to receive seller requests. Your home country is used until you change this setting.', emailEnabled: 'Email me about new requests', emailLabel: 'Notification email', emailPlaceholder: 'dealer@example.com', scopeLabel: 'Countries', scopeHome: 'My home country', scopeSelected: 'Selected countries', scopeAll: 'All Autorell countries', countriesLabel: 'Choose countries', save: 'Save settings', saving: 'Saving…', saved: 'Settings saved', saveError: 'Settings could not be saved.',
  call: 'Call seller', sendEmail: 'Email seller', images: 'Photos', noImages: 'No photos uploaded.', vehicleDetails: 'Vehicle details', conditionHistory: 'Condition and history', contactDetails: 'Contact details', country: 'Country',
  contactTracking: { label: 'Seller contacted', help: 'Shared with everyone in your company to prevent duplicate follow-up.', markedBy: 'Contacted by', visibleUntil: 'This request remains visible until', saving: 'Saving contact status…', error: 'Contact status could not be saved.' },
  labels: labels('Mileage','Fuel','Transmission','Body type','Colour','Engine power','Previous owners','Keys','Service book','Last service','Summer tyres','Winter tyres','Inspected','Drivable','Finance or credit','Visible damage','Damage description','Scratches, dents or paint','Accident','Warning lights','Technical problems','Engine or transmission','Rust','Serviced on schedule','Smoke-free','Interior wear','Other information','Name','Email','Phone','Postal code','City','Preferred contact','VIN'),
  statuses: statuses('New','Contacted','Offer sent','Accepted','Closed'),
}

const copies: Partial<Record<PublicLocale, DealerOffersCopy>> = {
  en,
  sv: language(en, {
    title:'Handlarbud',description:'Granska säljarförfrågningar, fordonets skick, bilder och kontaktuppgifter.',lockedText:'Handlarförfrågningar ingår från Growth och uppåt. Uppgradera för att ta emot förfrågningar i företagsportalen.',planBadge:'Growth och uppåt',introTitle:'Inkommande fordonsförfrågningar',introText:'Förfrågningar matchas mot dina valda länder. Ring eller mejla säljaren direkt.',noRequestsTitle:'Inga matchande förfrågningar ännu',noRequestsText:'Nya säljarförfrågningar från dina valda länder visas här.',viewPublicPage:'Visa säljarsidan',workflowTitle:'Rekommenderad uppföljning',workflow:['Kontrollera fordonet och skicket innan du kontaktar säljaren.','Granska anteckningar och bilder innan du lämnar bud.','Svara snabbt och kom överens om nästa steg direkt med säljaren.'],notificationsTitle:'Leadnotiser',notificationsText:'Välj varifrån du vill få säljarförfrågningar. Ditt hemland används tills du ändrar inställningen.',emailEnabled:'Mejla mig om nya förfrågningar',emailLabel:'E-post för notiser',emailPlaceholder:'handlare@foretag.se',scopeLabel:'Länder',scopeHome:'Mitt hemland',scopeSelected:'Valda länder',scopeAll:'Alla Autorell-länder',countriesLabel:'Välj länder',save:'Spara inställningar',saving:'Sparar…',saved:'Inställningarna har sparats',saveError:'Inställningarna kunde inte sparas.',call:'Ring säljaren',sendEmail:'Mejla säljaren',images:'Bilder',noImages:'Inga bilder uppladdade.',vehicleDetails:'Biluppgifter',conditionHistory:'Skick och historik',contactDetails:'Kontaktuppgifter',country:'Land',labels:labels('Mätarställning','Drivmedel','Växellåda','Karosstyp','Färg','Motoreffekt','Tidigare ägare','Nycklar','Servicebok','Senast servad','Sommarhjul','Vinterhjul','Besiktigad','Körbar','Finansiering eller kredit','Synliga skador','Skadebeskrivning','Repor, bucklor eller lack','Olycka','Varningslampor','Tekniska problem','Motor eller växellåda','Rost','Servad enligt intervall','Rökfri','Invändigt slitage','Övrig information','Namn','E-post','Telefon','Postnummer','Ort','Önskad kontaktväg','VIN'),statuses:statuses('Ny','Kontaktad','Bud lämnat','Accepterad','Avslutad'),
  }),
  de: language(en, {
    title:'Händlerangebote',description:'Verkäuferanfragen, Fahrzeugzustand, Fotos und Kontaktdaten prüfen.',lockedText:'Händleranfragen sind ab Growth verfügbar. Führen Sie ein Upgrade durch, um Anfragen im Unternehmensportal zu erhalten.',planBadge:'Growth und höher',introTitle:'Eingehende Fahrzeuganfragen',introText:'Anfragen werden Ihren ausgewählten Ländern zugeordnet. Kontaktieren Sie den Verkäufer direkt per Telefon oder E-Mail.',noRequestsTitle:'Noch keine passenden Anfragen',noRequestsText:'Neue Verkäuferanfragen aus Ihren ausgewählten Ländern erscheinen hier.',viewPublicPage:'Verkäuferseite öffnen',workflowTitle:'Empfohlene Bearbeitung',workflow:['Prüfen Sie Fahrzeug und Zustand vor der Kontaktaufnahme.','Prüfen Sie Hinweise und Fotos vor einem Angebot.','Antworten Sie schnell und vereinbaren Sie den nächsten Schritt direkt mit dem Verkäufer.'],notificationsTitle:'Lead-Benachrichtigungen',notificationsText:'Wählen Sie, aus welchen Ländern Sie Verkäuferanfragen erhalten möchten. Bis zur Änderung gilt Ihr Heimatland.',emailEnabled:'E-Mail bei neuen Anfragen senden',emailLabel:'Benachrichtigungs-E-Mail',emailPlaceholder:'haendler@firma.de',scopeLabel:'Länder',scopeHome:'Mein Heimatland',scopeSelected:'Ausgewählte Länder',scopeAll:'Alle Autorell-Länder',countriesLabel:'Länder auswählen',save:'Einstellungen speichern',saving:'Wird gespeichert…',saved:'Einstellungen gespeichert',saveError:'Einstellungen konnten nicht gespeichert werden.',call:'Verkäufer anrufen',sendEmail:'E-Mail senden',images:'Fotos',noImages:'Keine Fotos hochgeladen.',vehicleDetails:'Fahrzeugdaten',conditionHistory:'Zustand und Historie',contactDetails:'Kontaktdaten',country:'Land',labels:labels('Kilometerstand','Kraftstoff','Getriebe','Karosserie','Farbe','Motorleistung','Vorbesitzer','Schlüssel','Serviceheft','Letzter Service','Sommerreifen','Winterreifen','Hauptuntersuchung','Fahrbereit','Finanzierung oder Kredit','Sichtbare Schäden','Schadensbeschreibung','Kratzer, Dellen oder Lack','Unfall','Warnleuchten','Technische Probleme','Motor oder Getriebe','Rost','Nach Intervall gewartet','Nichtraucher','Innenraumverschleiß','Weitere Angaben','Name','E-Mail','Telefon','Postleitzahl','Ort','Bevorzugter Kontakt','FIN'),statuses:statuses('Neu','Kontaktiert','Angebot gesendet','Angenommen','Abgeschlossen'),
  }),
  fr: language(en, {
    title:'Offres professionnelles',description:'Consultez les demandes, l’état du véhicule, les photos et les coordonnées.',lockedText:'Les demandes vendeurs sont disponibles à partir de Growth. Passez à une offre supérieure pour les recevoir dans le portail entreprise.',planBadge:'Growth et supérieur',introTitle:'Demandes de véhicules reçues',introText:'Les demandes correspondent aux pays sélectionnés. Contactez directement le vendeur par téléphone ou e-mail.',noRequestsTitle:'Aucune demande correspondante',noRequestsText:'Les nouvelles demandes des pays sélectionnés apparaîtront ici.',viewPublicPage:'Voir la page vendeur',workflowTitle:'Suivi recommandé',workflow:['Vérifiez le véhicule et son état avant de contacter le vendeur.','Consultez les notes et les photos avant de faire une offre.','Répondez rapidement et convenez de la suite avec le vendeur.'],notificationsTitle:'Notifications de prospects',notificationsText:'Choisissez les pays dont vous souhaitez recevoir les demandes. Votre pays est utilisé par défaut.',emailEnabled:'Recevoir les nouvelles demandes par e-mail',emailLabel:'E-mail de notification',emailPlaceholder:'professionnel@entreprise.fr',scopeLabel:'Pays',scopeHome:'Mon pays',scopeSelected:'Pays sélectionnés',scopeAll:'Tous les pays Autorell',countriesLabel:'Choisir les pays',save:'Enregistrer',saving:'Enregistrement…',saved:'Paramètres enregistrés',saveError:'Impossible d’enregistrer les paramètres.',call:'Appeler le vendeur',sendEmail:'Écrire au vendeur',images:'Photos',noImages:'Aucune photo ajoutée.',vehicleDetails:'Détails du véhicule',conditionHistory:'État et historique',contactDetails:'Coordonnées',country:'Pays',labels:labels('Kilométrage','Carburant','Boîte de vitesses','Carrosserie','Couleur','Puissance','Anciens propriétaires','Clés','Carnet d’entretien','Dernier entretien','Pneus été','Pneus hiver','Contrôle technique','Roulant','Financement ou crédit','Dommages visibles','Description des dommages','Rayures, bosses ou peinture','Accident','Voyants','Problèmes techniques','Moteur ou boîte','Rouille','Entretien régulier','Non-fumeur','Usure intérieure','Autres informations','Nom','E-mail','Téléphone','Code postal','Ville','Contact préféré','VIN'),statuses:statuses('Nouvelle','Contactée','Offre envoyée','Acceptée','Clôturée'),
  }),
  es: language(en, {
    title:'Ofertas de concesionarios',description:'Revisa solicitudes, estado del vehículo, fotos y datos de contacto.',lockedText:'Las solicitudes están disponibles desde Growth. Mejora el plan para recibirlas en el portal de empresa.',planBadge:'Growth y superiores',introTitle:'Solicitudes de vehículos',introText:'Las solicitudes se asignan a los países seleccionados. Llama o escribe directamente al vendedor.',noRequestsTitle:'Aún no hay solicitudes coincidentes',noRequestsText:'Las nuevas solicitudes de los países seleccionados aparecerán aquí.',viewPublicPage:'Ver página de venta',workflowTitle:'Seguimiento recomendado',workflow:['Comprueba el vehículo y su estado antes de contactar.','Revisa notas y fotos antes de hacer una oferta.','Responde rápido y acuerda el siguiente paso con el vendedor.'],notificationsTitle:'Notificaciones de contactos',notificationsText:'Elige los países de los que quieres recibir solicitudes. Se usa tu país hasta que lo cambies.',emailEnabled:'Enviar nuevas solicitudes por correo',emailLabel:'Correo de notificación',emailPlaceholder:'concesionario@empresa.es',scopeLabel:'Países',scopeHome:'Mi país',scopeSelected:'Países seleccionados',scopeAll:'Todos los países de Autorell',countriesLabel:'Elegir países',save:'Guardar ajustes',saving:'Guardando…',saved:'Ajustes guardados',saveError:'No se pudieron guardar los ajustes.',call:'Llamar al vendedor',sendEmail:'Enviar correo',images:'Fotos',noImages:'No se han subido fotos.',vehicleDetails:'Datos del vehículo',conditionHistory:'Estado e historial',contactDetails:'Datos de contacto',country:'País',labels:labels('Kilometraje','Combustible','Transmisión','Carrocería','Color','Potencia','Propietarios anteriores','Llaves','Libro de mantenimiento','Último mantenimiento','Neumáticos de verano','Neumáticos de invierno','Inspeccionado','En circulación','Financiación o crédito','Daños visibles','Descripción del daño','Arañazos, abolladuras o pintura','Accidente','Testigos','Problemas técnicos','Motor o transmisión','Óxido','Mantenimiento periódico','Libre de humo','Desgaste interior','Más información','Nombre','Correo electrónico','Teléfono','Código postal','Ciudad','Contacto preferido','VIN'),statuses:statuses('Nueva','Contactada','Oferta enviada','Aceptada','Cerrada'),
  }),
  it: language(en, {
    title:'Offerte concessionari',description:'Consulta richieste, condizioni, foto e contatti del venditore.',lockedText:'Le richieste sono disponibili dal piano Growth. Effettua l’upgrade per riceverle nel portale aziendale.',planBadge:'Growth e superiori',introTitle:'Richieste di veicoli in arrivo',introText:'Le richieste corrispondono ai Paesi selezionati. Contatta direttamente il venditore per telefono o e-mail.',noRequestsTitle:'Nessuna richiesta corrispondente',noRequestsText:'Le nuove richieste dai Paesi selezionati appariranno qui.',viewPublicPage:'Vedi pagina venditore',workflowTitle:'Gestione consigliata',workflow:['Controlla veicolo e condizioni prima del contatto.','Esamina note e foto prima di fare un’offerta.','Rispondi rapidamente e concorda il prossimo passo con il venditore.'],notificationsTitle:'Notifiche lead',notificationsText:'Scegli i Paesi da cui ricevere le richieste. Viene usato il tuo Paese finché non modifichi l’impostazione.',emailEnabled:'Invia le nuove richieste via e-mail',emailLabel:'E-mail per le notifiche',emailPlaceholder:'concessionario@azienda.it',scopeLabel:'Paesi',scopeHome:'Il mio Paese',scopeSelected:'Paesi selezionati',scopeAll:'Tutti i Paesi Autorell',countriesLabel:'Scegli i Paesi',save:'Salva impostazioni',saving:'Salvataggio…',saved:'Impostazioni salvate',saveError:'Impossibile salvare le impostazioni.',call:'Chiama il venditore',sendEmail:'Invia e-mail',images:'Foto',noImages:'Nessuna foto caricata.',vehicleDetails:'Dati del veicolo',conditionHistory:'Condizioni e storico',contactDetails:'Contatti',country:'Paese',labels:labels('Chilometraggio','Alimentazione','Cambio','Carrozzeria','Colore','Potenza','Proprietari precedenti','Chiavi','Libretto tagliandi','Ultimo tagliando','Pneumatici estivi','Pneumatici invernali','Revisionata','Marciabile','Finanziamento o credito','Danni visibili','Descrizione danni','Graffi, ammaccature o vernice','Incidente','Spie','Problemi tecnici','Motore o cambio','Ruggine','Tagliandi regolari','Non fumatori','Usura interna','Altre informazioni','Nome','E-mail','Telefono','CAP','Città','Contatto preferito','VIN'),statuses:statuses('Nuova','Contattata','Offerta inviata','Accettata','Chiusa'),
  }),
  nl: language(en, {
    title:'Dealerbiedingen',description:'Bekijk verkoopaanvragen, voertuigstaat, foto’s en contactgegevens.',lockedText:'Dealerleads zijn beschikbaar vanaf Growth. Upgrade om aanvragen in het bedrijfsportaal te ontvangen.',planBadge:'Growth en hoger',introTitle:'Binnenkomende voertuigaanvragen',introText:'Aanvragen worden gekoppeld aan uw geselecteerde landen. Bel of mail de verkoper rechtstreeks.',noRequestsTitle:'Nog geen passende aanvragen',noRequestsText:'Nieuwe aanvragen uit uw geselecteerde landen verschijnen hier.',viewPublicPage:'Verkoperspagina bekijken',workflowTitle:'Aanbevolen opvolging',workflow:['Controleer voertuig en staat voordat u contact opneemt.','Bekijk notities en foto’s voordat u een bod doet.','Reageer snel en spreek de volgende stap af met de verkoper.'],notificationsTitle:'Leadmeldingen',notificationsText:'Kies uit welke landen u aanvragen wilt ontvangen. Uw thuisland geldt totdat u dit wijzigt.',emailEnabled:'E-mail mij bij nieuwe aanvragen',emailLabel:'E-mailadres voor meldingen',emailPlaceholder:'dealer@bedrijf.nl',scopeLabel:'Landen',scopeHome:'Mijn thuisland',scopeSelected:'Geselecteerde landen',scopeAll:'Alle Autorell-landen',countriesLabel:'Landen kiezen',save:'Instellingen opslaan',saving:'Opslaan…',saved:'Instellingen opgeslagen',saveError:'Instellingen konden niet worden opgeslagen.',call:'Verkoper bellen',sendEmail:'Verkoper mailen',images:'Foto’s',noImages:'Geen foto’s geüpload.',vehicleDetails:'Voertuiggegevens',conditionHistory:'Staat en historie',contactDetails:'Contactgegevens',country:'Land',labels:labels('Kilometerstand','Brandstof','Transmissie','Carrosserie','Kleur','Motorvermogen','Vorige eigenaren','Sleutels','Onderhoudsboek','Laatste onderhoud','Zomerbanden','Winterbanden','Gekeurd','Rijdbaar','Financiering of krediet','Zichtbare schade','Schadeomschrijving','Krassen, deuken of lak','Ongeval','Waarschuwingslampjes','Technische problemen','Motor of transmissie','Roest','Volgens schema onderhouden','Rookvrij','Slijtage interieur','Overige informatie','Naam','E-mail','Telefoon','Postcode','Plaats','Voorkeurscontact','VIN'),statuses:statuses('Nieuw','Gecontacteerd','Bod verzonden','Geaccepteerd','Gesloten'),
  }),
  fi: language(en, {
    title:'Liikkeiden tarjoukset',description:'Tarkista myyntipyynnöt, ajoneuvon kunto, kuvat ja yhteystiedot.',lockedText:'Myyjäpyynnöt ovat käytettävissä Growth-paketista alkaen. Päivitä paketti saadaksesi pyynnöt yritysportaaliin.',planBadge:'Growth ja sitä ylemmät',introTitle:'Saapuvat ajoneuvopyynnöt',introText:'Pyynnöt kohdistetaan valitsemiisi maihin. Soita tai lähetä sähköpostia suoraan myyjälle.',noRequestsTitle:'Ei vielä sopivia pyyntöjä',noRequestsText:'Valituista maista tulevat uudet myyjäpyynnöt näkyvät täällä.',viewPublicPage:'Avaa myyntisivu',workflowTitle:'Suositeltu jatkokäsittely',workflow:['Tarkista ajoneuvo ja kunto ennen yhteydenottoa.','Tarkista tiedot ja kuvat ennen tarjousta.','Vastaa nopeasti ja sovi seuraava vaihe suoraan myyjän kanssa.'],notificationsTitle:'Liidi-ilmoitukset',notificationsText:'Valitse maat, joista haluat saada pyyntöjä. Kotimaatasi käytetään, kunnes muutat asetusta.',emailEnabled:'Lähetä uudet pyynnöt sähköpostiin',emailLabel:'Ilmoitusten sähköposti',emailPlaceholder:'autoliike@yritys.fi',scopeLabel:'Maat',scopeHome:'Kotimaani',scopeSelected:'Valitut maat',scopeAll:'Kaikki Autorell-maat',countriesLabel:'Valitse maat',save:'Tallenna asetukset',saving:'Tallennetaan…',saved:'Asetukset tallennettu',saveError:'Asetuksia ei voitu tallentaa.',call:'Soita myyjälle',sendEmail:'Lähetä sähköpostia',images:'Kuvat',noImages:'Kuvia ei ole ladattu.',vehicleDetails:'Ajoneuvon tiedot',conditionHistory:'Kunto ja historia',contactDetails:'Yhteystiedot',country:'Maa',labels:labels('Ajokilometrit','Polttoaine','Vaihteisto','Korimalli','Väri','Moottoriteho','Aiemmat omistajat','Avaimet','Huoltokirja','Viimeisin huolto','Kesärenkaat','Talvirenkaat','Katsastettu','Ajokuntoinen','Rahoitus tai luotto','Näkyvät vauriot','Vaurioiden kuvaus','Naarmut, lommot tai maalipinta','Kolari','Varoitusvalot','Tekniset ongelmat','Moottori tai vaihteisto','Ruoste','Huollettu aikataulun mukaan','Savuton','Sisätilojen kuluminen','Muut tiedot','Nimi','Sähköposti','Puhelin','Postinumero','Kaupunki','Toivottu yhteydenotto','VIN'),statuses:statuses('Uusi','Kontaktoitu','Tarjous lähetetty','Hyväksytty','Suljettu'),
  }),
  da: language(en, {
    title:'Forhandlerbud',description:'Gennemgå sælgerforespørgsler, køretøjets stand, billeder og kontaktoplysninger.',lockedText:'Forhandlerforespørgsler er tilgængelige fra Growth. Opgrader for at modtage dem i virksomhedsportalen.',planBadge:'Growth og højere',introTitle:'Indkomne køretøjsforespørgsler',introText:'Forespørgsler matches med dine valgte lande. Ring eller skriv direkte til sælgeren.',noRequestsTitle:'Ingen matchende forespørgsler endnu',noRequestsText:'Nye forespørgsler fra dine valgte lande vises her.',viewPublicPage:'Se sælgersiden',workflowTitle:'Anbefalet opfølgning',workflow:['Kontrollér køretøj og stand før kontakt.','Gennemgå noter og billeder før et bud.','Svar hurtigt, og aftal næste trin direkte med sælgeren.'],notificationsTitle:'Leadnotifikationer',notificationsText:'Vælg de lande, du vil modtage forespørgsler fra. Dit hjemland bruges, indtil du ændrer det.',emailEnabled:'Send nye forespørgsler på e-mail',emailLabel:'E-mail til notifikationer',emailPlaceholder:'forhandler@firma.dk',scopeLabel:'Lande',scopeHome:'Mit hjemland',scopeSelected:'Valgte lande',scopeAll:'Alle Autorell-lande',countriesLabel:'Vælg lande',save:'Gem indstillinger',saving:'Gemmer…',saved:'Indstillinger gemt',saveError:'Indstillingerne kunne ikke gemmes.',call:'Ring til sælger',sendEmail:'Send e-mail',images:'Billeder',noImages:'Ingen billeder uploadet.',vehicleDetails:'Køretøjsoplysninger',conditionHistory:'Stand og historik',contactDetails:'Kontaktoplysninger',country:'Land',labels:labels('Kilometertal','Brændstof','Gearkasse','Karrosseri','Farve','Motoreffekt','Tidligere ejere','Nøgler','Servicebog','Seneste service','Sommerdæk','Vinterdæk','Synet','Kørbar','Finansiering eller kredit','Synlige skader','Skadebeskrivelse','Ridser, buler eller lak','Ulykke','Advarselslamper','Tekniske problemer','Motor eller gearkasse','Rust','Serviceret efter plan','Røgfri','Slitage i kabinen','Andre oplysninger','Navn','E-mail','Telefon','Postnummer','By','Foretrukken kontakt','VIN'),statuses:statuses('Ny','Kontaktet','Bud afgivet','Accepteret','Afsluttet'),
  }),
  pl: language(en, {
    title:'Oferty dealerów',description:'Przeglądaj zapytania, stan pojazdu, zdjęcia i dane kontaktowe.',lockedText:'Zapytania są dostępne od planu Growth. Zmień plan, aby otrzymywać je w portalu firmowym.',planBadge:'Growth i wyższe',introTitle:'Nowe zapytania o pojazdy',introText:'Zapytania są dopasowane do wybranych krajów. Zadzwoń lub napisz bezpośrednio do sprzedającego.',noRequestsTitle:'Brak pasujących zapytań',noRequestsText:'Nowe zapytania z wybranych krajów pojawią się tutaj.',viewPublicPage:'Zobacz stronę sprzedaży',workflowTitle:'Zalecana obsługa',workflow:['Sprawdź pojazd i jego stan przed kontaktem.','Przejrzyj uwagi i zdjęcia przed złożeniem oferty.','Odpowiedz szybko i uzgodnij kolejny krok ze sprzedającym.'],notificationsTitle:'Powiadomienia o leadach',notificationsText:'Wybierz kraje, z których chcesz otrzymywać zapytania. Domyślnie używany jest kraj firmy.',emailEnabled:'Wysyłaj nowe zapytania e-mailem',emailLabel:'E-mail do powiadomień',emailPlaceholder:'dealer@firma.pl',scopeLabel:'Kraje',scopeHome:'Mój kraj',scopeSelected:'Wybrane kraje',scopeAll:'Wszystkie kraje Autorell',countriesLabel:'Wybierz kraje',save:'Zapisz ustawienia',saving:'Zapisywanie…',saved:'Ustawienia zapisane',saveError:'Nie udało się zapisać ustawień.',call:'Zadzwoń do sprzedającego',sendEmail:'Napisz e-mail',images:'Zdjęcia',noImages:'Nie przesłano zdjęć.',vehicleDetails:'Dane pojazdu',conditionHistory:'Stan i historia',contactDetails:'Dane kontaktowe',country:'Kraj',labels:labels('Przebieg','Paliwo','Skrzynia biegów','Nadwozie','Kolor','Moc silnika','Poprzedni właściciele','Kluczyki','Książka serwisowa','Ostatni serwis','Opony letnie','Opony zimowe','Przegląd','Sprawny do jazdy','Finansowanie lub kredyt','Widoczne uszkodzenia','Opis uszkodzeń','Rysy, wgniecenia lub lakier','Wypadek','Kontrolki','Problemy techniczne','Silnik lub skrzynia','Rdza','Serwisowany terminowo','Dla niepalących','Zużycie wnętrza','Inne informacje','Imię i nazwisko','E-mail','Telefon','Kod pocztowy','Miasto','Preferowany kontakt','VIN'),statuses:statuses('Nowe','Skontaktowano','Wysłano ofertę','Zaakceptowane','Zamknięte'),
  }),
}

const contactTrackingByLocale: Partial<Record<ReturnType<typeof translationLocale>, DealerLeadContactTrackingCopy>> = {
  sv: { label: 'Säljaren är kontaktad', help: 'Delas med alla i företaget så att säljaren inte kontaktas flera gånger.', markedBy: 'Kontaktad av', visibleUntil: 'Förfrågan visas till', saving: 'Sparar kontaktstatus…', error: 'Kontaktstatusen kunde inte sparas.' },
  de: { label: 'Verkäufer wurde kontaktiert', help: 'Wird im Unternehmen geteilt, um doppelte Kontaktaufnahme zu vermeiden.', markedBy: 'Kontaktiert von', visibleUntil: 'Die Anfrage bleibt sichtbar bis', saving: 'Kontaktstatus wird gespeichert…', error: 'Der Kontaktstatus konnte nicht gespeichert werden.' },
  fr: { label: 'Vendeur contacté', help: 'Partagé avec toute votre entreprise afin d’éviter les doubles contacts.', markedBy: 'Contacté par', visibleUntil: 'La demande reste visible jusqu’au', saving: 'Enregistrement du statut…', error: 'Impossible d’enregistrer le statut de contact.' },
  es: { label: 'Vendedor contactado', help: 'Se comparte con toda la empresa para evitar contactos duplicados.', markedBy: 'Contactado por', visibleUntil: 'La solicitud seguirá visible hasta', saving: 'Guardando el estado…', error: 'No se pudo guardar el estado de contacto.' },
  it: { label: 'Venditore contattato', help: 'Condiviso con tutta l’azienda per evitare contatti duplicati.', markedBy: 'Contattato da', visibleUntil: 'La richiesta resta visibile fino al', saving: 'Salvataggio dello stato…', error: 'Impossibile salvare lo stato del contatto.' },
  nl: { label: 'Verkoper gecontacteerd', help: 'Gedeeld met iedereen in uw bedrijf om dubbel contact te voorkomen.', markedBy: 'Gecontacteerd door', visibleUntil: 'De aanvraag blijft zichtbaar tot', saving: 'Contactstatus opslaan…', error: 'De contactstatus kon niet worden opgeslagen.' },
  fi: { label: 'Myyjään on otettu yhteyttä', help: 'Tieto jaetaan koko yritykselle päällekkäisten yhteydenottojen estämiseksi.', markedBy: 'Yhteydenottaja', visibleUntil: 'Pyyntö näkyy tähän asti', saving: 'Tallennetaan yhteydenoton tila…', error: 'Yhteydenoton tilaa ei voitu tallentaa.' },
  da: { label: 'Sælgeren er kontaktet', help: 'Deles med hele virksomheden for at undgå dobbelt kontakt.', markedBy: 'Kontaktet af', visibleUntil: 'Forespørgslen vises indtil', saving: 'Gemmer kontaktstatus…', error: 'Kontaktstatus kunne ikke gemmes.' },
  pl: { label: 'Skontaktowano się ze sprzedającym', help: 'Informacja jest udostępniana całej firmie, aby uniknąć wielokrotnego kontaktu.', markedBy: 'Kontakt nawiązał(a)', visibleUntil: 'Zapytanie będzie widoczne do', saving: 'Zapisywanie statusu kontaktu…', error: 'Nie udało się zapisać statusu kontaktu.' },
}

export function getDealerOffersCopy(locale: PublicLocale) {
  const normalizedLocale = translationLocale(locale)
  const copy = copies[normalizedLocale] || en
  return {
    ...copy,
    contactTracking: contactTrackingByLocale[normalizedLocale] || en.contactTracking,
  }
}

function language(base: DealerOffersCopy, override: Partial<DealerOffersCopy>): DealerOffersCopy {
  return { ...base, ...override }
}

function labels(mileage:string,fuel:string,transmission:string,bodyType:string,color:string,enginePower:string,previousOwners:string,keys:string,serviceBook:string,lastService:string,summerTires:string,winterTires:string,inspected:string,drivable:string,finance:string,visibleDamage:string,damageDescription:string,cosmetic:string,accident:string,warningLights:string,technical:string,engineTransmission:string,rust:string,serviced:string,smokeFree:string,interior:string,other:string,name:string,email:string,phone:string,postalCode:string,city:string,preferredContact:string,vin:string) {
  return { mileage,fuel,transmission,bodyType,color,enginePower,previousOwners,keys,serviceBook,lastService,summerTires,winterTires,inspected,drivable,finance,visibleDamage,damageDescription,cosmetic,accident,warningLights,technical,engineTransmission,rust,serviced,smokeFree,interior,other,name,email,phone,postalCode,city,preferredContact,vin }
}

function statuses(newLabel:string,contacted:string,offerSent:string,accepted:string,closed:string) {
  return { new:newLabel, contacted, offer_sent:offerSent, accepted, closed, archived:closed }
}
