import { translationLocale, type PublicLocale } from './public-i18n'

type AuthMode = 'login' | 'register'
type AuthView = AuthMode | 'forgot' | 'reset'

export type AuthModalCopy = {
  loginTab: string
  registerTab: string
  close: string
  title: string
  description: string
  passwordDescription: string
  email: string
  emailPlaceholder: string
  password: string
  confirmPassword: string
  forgotPassword: string
  showPassword: string
  hidePassword: string
  passwordRequirement: string
  remember: string
  continue: string
  passwordSubmit: string
  passwordLoading: string
  sending: string
  codeTitle: string
  codeSent: string
  digit: string
  submitCode: string
  verifying: string
  resend: string
  resendIn: string
  back: string
  newHere: string
  haveAccount: string
  useCodeInstead: string
  usePasswordInstead: string
  invalidPassword: string
  passwordMismatch: string
  signupError: string
  confirmEmailSent: string
  emailRequired: string
  sendReset: string
  sendingReset: string
  resetSent: string
  backToLogin: string
  savePassword: string
  savingPassword: string
  passwordUpdated: string
  resetError: string
  sendError: string
  codeError: string
  connectionError: string
  chooseMarket: string
}

export type AuthApiCopy = Pick<
  AuthModalCopy,
  | 'emailRequired'
  | 'passwordRequirement'
  | 'passwordMismatch'
  | 'signupError'
  | 'sendError'
  | 'codeError'
  | 'connectionError'
> & {
  rateLimited: string
  waitBeforeNewCode: string
  emailUnavailable: string
  tooManyAttempts: string
  usedCode: string
  recoveryUnavailable: string
}

const passwordRequirements: Record<string, string> = {
  en: 'Use at least 8 characters with uppercase, lowercase and a number.',
  sv: 'Använd minst 8 tecken med stor bokstav, liten bokstav och en siffra.',
  de: 'Mindestens 8 Zeichen mit Großbuchstaben, Kleinbuchstaben und Zahl.',
  fr: 'Utilisez au moins 8 caractères avec majuscule, minuscule et chiffre.',
  es: 'Usa al menos 8 caracteres con mayúscula, minúscula y un número.',
  it: 'Usa almeno 8 caratteri con maiuscola, minuscola e un numero.',
  pl: 'Użyj co najmniej 8 znaków, w tym wielkiej litery, małej litery i cyfry.',
  nl: 'Gebruik minimaal 8 tekens met een hoofdletter, kleine letter en cijfer.',
  fi: 'Käytä vähintään 8 merkkiä, joissa on iso kirjain, pieni kirjain ja numero.',
  da: 'Brug mindst 8 tegn med stort bogstav, lille bogstav og et tal.',
}

const modalBase = {
  en: {
    loginTab: 'Log in',
    registerTab: 'Create account',
    close: 'Close',
    title: {
      login: 'Welcome back',
      register: 'Create your account',
      forgot: 'Reset your password',
      reset: 'Choose a new password',
    },
    description: {
      login: 'Enter your email and we will send you a one-time login code.',
      register: 'Use your email to start. We will send a code before you continue.',
      forgot: 'Enter your email and we will send a secure reset link.',
      reset: 'Choose a new password for your Autorell account.',
    },
    passwordDescription: {
      login: 'Log in with your email and password, or use a one-time code instead.',
      register: 'Create your Autorell account with email and password, or use a one-time code instead.',
    },
    email: 'Email',
    emailPlaceholder: 'Enter your email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    forgotPassword: 'Forgot password?',
    showPassword: 'Show password',
    hidePassword: 'Hide password',
    remember: 'Remember my email',
    continue: 'Send login code',
    passwordSubmit: { login: 'Log in', register: 'Create account' },
    passwordLoading: { login: 'Logging in...', register: 'Creating account...' },
    sending: 'Sending code...',
    codeTitle: 'Enter your code',
    codeSent: 'We sent a six-digit code to',
    digit: 'Code digit',
    submitCode: { login: 'Log in', register: 'Continue' },
    verifying: 'Checking code...',
    resend: 'Send a new code',
    resendIn: 'New code in',
    back: 'Change email',
    newHere: 'New to Autorell?',
    haveAccount: 'Already have an account?',
    useCodeInstead: 'Use one-time code instead',
    usePasswordInstead: 'Use password instead',
    invalidPassword: 'The email or password is incorrect. If you registered with a one-time code, use one-time code or reset your password first.',
    passwordMismatch: 'The passwords do not match.',
    signupError: 'The account could not be created. If the email already uses one-time code, reset the password or continue with one-time code.',
    confirmEmailSent: 'If email confirmation is required, open the email we sent and then continue creating your profile.',
    emailRequired: 'Enter your email address.',
    sendReset: 'Send reset link',
    sendingReset: 'Sending reset link...',
    resetSent: 'If an account exists for this email, we have sent a reset link.',
    backToLogin: 'Back to login',
    savePassword: 'Save new password',
    savingPassword: 'Saving password...',
    passwordUpdated: 'Your password has been updated. Log in again with your new password.',
    resetError: 'The password could not be updated. Open the latest reset link and try again.',
    sendError: 'The code could not be sent.',
    codeError: 'The code is incorrect or has expired.',
    connectionError: 'The connection was interrupted. Try again.',
    chooseMarket: 'Choose language and market',
    spamHint: 'If you cannot find the email, check your spam or junk folder.',
  },
  sv: {
    loginTab: 'Logga in',
    registerTab: 'Skapa konto',
    close: 'Stäng',
    title: {
      login: 'Välkommen tillbaka',
      register: 'Skapa ditt konto',
      forgot: 'Återställ lösenord',
      reset: 'Välj nytt lösenord',
    },
    description: {
      login: 'Ange din mejladress så skickar vi en engångskod.',
      register: 'Börja med din mejladress. Vi skickar en kod innan du fortsätter.',
      forgot: 'Ange din mejladress så skickar vi en säker återställningslänk.',
      reset: 'Välj ett nytt lösenord för ditt Autorell-konto.',
    },
    passwordDescription: {
      login: 'Logga in med mejladress och lösenord, eller använd engångskod istället.',
      register: 'Skapa ditt Autorell-konto med mejladress och lösenord, eller använd engångskod istället.',
    },
    email: 'Mejl',
    emailPlaceholder: 'Ange din mejladress',
    password: 'Lösenord',
    confirmPassword: 'Bekräfta lösenord',
    forgotPassword: 'Glömt lösenord?',
    showPassword: 'Visa lösenord',
    hidePassword: 'Dölj lösenord',
    remember: 'Kom ihåg min mejladress',
    continue: 'Skicka inloggningskod',
    passwordSubmit: { login: 'Logga in', register: 'Skapa konto' },
    passwordLoading: { login: 'Loggar in...', register: 'Skapar konto...' },
    sending: 'Skickar kod...',
    codeTitle: 'Ange din kod',
    codeSent: 'Vi skickade en sexsiffrig kod till',
    digit: 'Kodens siffra',
    submitCode: { login: 'Logga in', register: 'Fortsätt' },
    verifying: 'Kontrollerar kod...',
    resend: 'Skicka en ny kod',
    resendIn: 'Ny kod om',
    back: 'Byt mejladress',
    newHere: 'Ny på Autorell?',
    haveAccount: 'Har du redan ett konto?',
    useCodeInstead: 'Använd engångskod istället',
    usePasswordInstead: 'Använd lösenord istället',
    invalidPassword: 'Mejladressen eller lösenordet är fel. Om kontot skapades med engångskod, använd engångskod eller återställ lösenordet först.',
    passwordMismatch: 'Lösenorden matchar inte.',
    signupError: 'Kontot kunde inte skapas. Om mejlen redan används med engångskod, återställ lösenordet eller fortsätt med engångskod.',
    confirmEmailSent: 'Om mejlbekräftelse krävs, öppna mejlet vi skickade och fortsätt sedan skapa din profil.',
    emailRequired: 'Ange din mejladress.',
    sendReset: 'Skicka återställningslänk',
    sendingReset: 'Skickar återställningslänk...',
    resetSent: 'Om det finns ett konto för mejladressen har vi skickat en återställningslänk.',
    backToLogin: 'Tillbaka till inloggning',
    savePassword: 'Spara nytt lösenord',
    savingPassword: 'Sparar lösenord...',
    passwordUpdated: 'Ditt lösenord har uppdaterats. Logga in igen med ditt nya lösenord.',
    resetError: 'Lösenordet kunde inte uppdateras. Öppna den senaste återställningslänken och försök igen.',
    sendError: 'Koden kunde inte skickas.',
    codeError: 'Koden är felaktig eller har gått ut.',
    connectionError: 'Anslutningen avbröts. Försök igen.',
    chooseMarket: 'Välj språk och marknad',
    spamHint: 'Om mejlet inte syns, kontrollera skräppost eller skräpkorgen.',
  },
  de: {
    loginTab: 'Anmelden',
    registerTab: 'Konto erstellen',
    close: 'Schließen',
    title: {
      login: 'Willkommen zurück',
      register: 'Konto erstellen',
      forgot: 'Passwort zurücksetzen',
      reset: 'Neues Passwort wählen',
    },
    description: {
      login: 'Geben Sie Ihre E-Mail ein und wir senden Ihnen einen einmaligen Anmeldecode.',
      register: 'Starten Sie mit Ihrer E-Mail. Wir senden einen Code, bevor Sie fortfahren.',
      forgot: 'Geben Sie Ihre E-Mail ein und wir senden einen sicheren Link zum Zurücksetzen.',
      reset: 'Wählen Sie ein neues Passwort für Ihr Autorell-Konto.',
    },
    passwordDescription: {
      login: 'Melden Sie sich mit E-Mail und Passwort an oder verwenden Sie stattdessen einen Einmalcode.',
      register: 'Erstellen Sie Ihr Autorell-Konto mit E-Mail und Passwort oder verwenden Sie stattdessen einen Einmalcode.',
    },
    email: 'E-Mail',
    emailPlaceholder: 'E-Mail eingeben',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    forgotPassword: 'Passwort vergessen?',
    showPassword: 'Passwort anzeigen',
    hidePassword: 'Passwort ausblenden',
    remember: 'E-Mail merken',
    continue: 'Anmeldecode senden',
    passwordSubmit: { login: 'Anmelden', register: 'Konto erstellen' },
    passwordLoading: { login: 'Anmeldung...', register: 'Konto wird erstellt...' },
    sending: 'Code wird gesendet...',
    codeTitle: 'Code eingeben',
    codeSent: 'Wir haben einen sechsstelligen Code gesendet an',
    digit: 'Code-Ziffer',
    submitCode: { login: 'Anmelden', register: 'Weiter' },
    verifying: 'Code wird geprüft...',
    resend: 'Neuen Code senden',
    resendIn: 'Neuer Code in',
    back: 'E-Mail ändern',
    newHere: 'Neu bei Autorell?',
    haveAccount: 'Bereits registriert?',
    useCodeInstead: 'Einmalcode verwenden',
    usePasswordInstead: 'Passwort verwenden',
    invalidPassword: 'E-Mail oder Passwort ist falsch. Wenn Sie sich mit Einmalcode registriert haben, nutzen Sie den Einmalcode oder setzen Sie zuerst das Passwort zurück.',
    passwordMismatch: 'Die Passwörter stimmen nicht überein.',
    signupError: 'Das Konto konnte nicht erstellt werden. Wenn die E-Mail bereits mit Einmalcode genutzt wird, setzen Sie das Passwort zurück oder fahren Sie mit Einmalcode fort.',
    confirmEmailSent: 'Falls eine E-Mail-Bestätigung erforderlich ist, öffnen Sie die E-Mail und erstellen Sie danach Ihr Profil weiter.',
    emailRequired: 'Geben Sie Ihre E-Mail-Adresse ein.',
    sendReset: 'Link senden',
    sendingReset: 'Link wird gesendet...',
    resetSent: 'Falls ein Konto für diese E-Mail existiert, haben wir einen Link gesendet.',
    backToLogin: 'Zurück zur Anmeldung',
    savePassword: 'Neues Passwort speichern',
    savingPassword: 'Passwort wird gespeichert...',
    passwordUpdated: 'Ihr Passwort wurde aktualisiert. Melden Sie sich erneut mit dem neuen Passwort an.',
    resetError: 'Das Passwort konnte nicht aktualisiert werden. Öffnen Sie den neuesten Link und versuchen Sie es erneut.',
    sendError: 'Der Code konnte nicht gesendet werden.',
    codeError: 'Der Code ist falsch oder abgelaufen.',
    connectionError: 'Die Verbindung wurde unterbrochen. Erneut versuchen.',
    chooseMarket: 'Sprache und Markt wählen',
    spamHint: 'Wenn die E-Mail nicht sichtbar ist, prüfen Sie bitte den Spam- oder Junk-Ordner.',
  },
  fr: {
    loginTab: 'Se connecter',
    registerTab: 'Créer un compte',
    close: 'Fermer',
    title: {
      login: 'Bon retour',
      register: 'Créez votre compte',
      forgot: 'Réinitialiser le mot de passe',
      reset: 'Choisir un nouveau mot de passe',
    },
    description: {
      login: 'Saisissez votre e-mail et nous vous enverrons un code de connexion à usage unique.',
      register: 'Commencez avec votre e-mail. Nous enverrons un code avant de continuer.',
      forgot: 'Saisissez votre e-mail et nous vous enverrons un lien sécurisé.',
      reset: 'Choisissez un nouveau mot de passe pour votre compte Autorell.',
    },
    passwordDescription: {
      login: 'Connectez-vous avec votre e-mail et mot de passe, ou utilisez un code à usage unique.',
      register: 'Créez votre compte Autorell avec e-mail et mot de passe, ou utilisez un code à usage unique.',
    },
    email: 'E-mail',
    emailPlaceholder: 'Saisissez votre e-mail',
    password: 'Mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    forgotPassword: 'Mot de passe oublié ?',
    showPassword: 'Afficher le mot de passe',
    hidePassword: 'Masquer le mot de passe',
    remember: 'Mémoriser mon e-mail',
    continue: 'Envoyer le code',
    passwordSubmit: { login: 'Se connecter', register: 'Créer un compte' },
    passwordLoading: { login: 'Connexion...', register: 'Création du compte...' },
    sending: 'Envoi du code...',
    codeTitle: 'Saisissez votre code',
    codeSent: 'Nous avons envoyé un code à six chiffres à',
    digit: 'Chiffre du code',
    submitCode: { login: 'Se connecter', register: 'Continuer' },
    verifying: 'Vérification du code...',
    resend: 'Envoyer un nouveau code',
    resendIn: 'Nouveau code dans',
    back: 'Changer l’e-mail',
    newHere: 'Nouveau sur Autorell ?',
    haveAccount: 'Vous avez déjà un compte ?',
    useCodeInstead: 'Utiliser un code à usage unique',
    usePasswordInstead: 'Utiliser le mot de passe',
    invalidPassword: 'L’e-mail ou le mot de passe est incorrect. Si le compte a été créé avec un code, utilisez le code ou réinitialisez le mot de passe.',
    passwordMismatch: 'Les mots de passe ne correspondent pas.',
    signupError: 'Le compte n’a pas pu être créé. Si l’e-mail utilise déjà un code, réinitialisez le mot de passe ou continuez avec un code.',
    confirmEmailSent: 'Si une confirmation e-mail est requise, ouvrez l’e-mail envoyé puis continuez la création du profil.',
    emailRequired: 'Saisissez votre adresse e-mail.',
    sendReset: 'Envoyer le lien',
    sendingReset: 'Envoi du lien...',
    resetSent: 'Si un compte existe pour cet e-mail, nous avons envoyé un lien.',
    backToLogin: 'Retour à la connexion',
    savePassword: 'Enregistrer le nouveau mot de passe',
    savingPassword: 'Enregistrement...',
    passwordUpdated: 'Votre mot de passe a été mis à jour. Connectez-vous à nouveau.',
    resetError: 'Le mot de passe n’a pas pu être mis à jour. Ouvrez le dernier lien et réessayez.',
    sendError: 'Le code n’a pas pu être envoyé.',
    codeError: 'Le code est incorrect ou a expiré.',
    connectionError: 'La connexion a été interrompue. Réessayez.',
    chooseMarket: 'Choisir langue et marché',
    spamHint: 'Si vous ne trouvez pas l’e-mail, vérifiez les courriers indésirables.',
  },
  es: {
    loginTab: 'Iniciar sesión',
    registerTab: 'Crear cuenta',
    close: 'Cerrar',
    title: {
      login: 'Bienvenido de nuevo',
      register: 'Crea tu cuenta',
      forgot: 'Restablecer contraseña',
      reset: 'Elige una nueva contraseña',
    },
    description: {
      login: 'Introduce tu correo electrónico y te enviaremos un código de un solo uso.',
      register: 'Empieza con tu correo electrónico. Te enviaremos un código antes de continuar.',
      forgot: 'Introduce tu correo electrónico y te enviaremos un enlace seguro.',
      reset: 'Elige una nueva contraseña para tu cuenta de Autorell.',
    },
    passwordDescription: {
      login: 'Inicia sesión con correo y contraseña, o usa un código de un solo uso.',
      register: 'Crea tu cuenta de Autorell con correo y contraseña, o usa un código de un solo uso.',
    },
    email: 'Correo electrónico',
    emailPlaceholder: 'Introduce tu correo electrónico',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    forgotPassword: '¿Olvidaste la contraseña?',
    showPassword: 'Mostrar contraseña',
    hidePassword: 'Ocultar contraseña',
    remember: 'Recordar mi correo',
    continue: 'Enviar código',
    passwordSubmit: { login: 'Iniciar sesión', register: 'Crear cuenta' },
    passwordLoading: { login: 'Iniciando sesión...', register: 'Creando cuenta...' },
    sending: 'Enviando código...',
    codeTitle: 'Introduce tu código',
    codeSent: 'Hemos enviado un código de seis dígitos a',
    digit: 'Dígito del código',
    submitCode: { login: 'Iniciar sesión', register: 'Continuar' },
    verifying: 'Comprobando código...',
    resend: 'Enviar un nuevo código',
    resendIn: 'Nuevo código en',
    back: 'Cambiar correo',
    newHere: '¿Nuevo en Autorell?',
    haveAccount: '¿Ya tienes una cuenta?',
    useCodeInstead: 'Usar código de un solo uso',
    usePasswordInstead: 'Usar contraseña',
    invalidPassword: 'El correo o la contraseña son incorrectos. Si te registraste con un código, usa el código o restablece la contraseña primero.',
    passwordMismatch: 'Las contraseñas no coinciden.',
    signupError: 'No se pudo crear la cuenta. Si el correo ya usa código, restablece la contraseña o continúa con código.',
    confirmEmailSent: 'Si se requiere confirmación por correo, abre el correo enviado y continúa creando tu perfil.',
    emailRequired: 'Introduce tu correo electrónico.',
    sendReset: 'Enviar enlace',
    sendingReset: 'Enviando enlace...',
    resetSent: 'Si existe una cuenta con este correo, hemos enviado un enlace.',
    backToLogin: 'Volver al inicio de sesión',
    savePassword: 'Guardar nueva contraseña',
    savingPassword: 'Guardando contraseña...',
    passwordUpdated: 'Tu contraseña se ha actualizado. Inicia sesión de nuevo.',
    resetError: 'No se pudo actualizar la contraseña. Abre el último enlace e inténtalo de nuevo.',
    sendError: 'No se pudo enviar el código.',
    codeError: 'El código es incorrecto o ha caducado.',
    connectionError: 'La conexión se interrumpió. Inténtalo de nuevo.',
    chooseMarket: 'Elegir idioma y mercado',
    spamHint: 'Si no encuentras el correo, revisa spam o correo no deseado.',
  },
  it: {
    loginTab: 'Accedi',
    registerTab: 'Crea account',
    close: 'Chiudi',
    title: { login: 'Bentornato', register: 'Crea il tuo account', forgot: 'Reimposta la password', reset: 'Scegli una nuova password' },
    description: {
      login: 'Inserisci la tua email e ti invieremo un codice monouso.',
      register: 'Inizia con la tua email. Ti invieremo un codice prima di continuare.',
      forgot: 'Inserisci la tua email e ti invieremo un link sicuro.',
      reset: 'Scegli una nuova password per il tuo account Autorell.',
    },
    passwordDescription: {
      login: 'Accedi con email e password oppure usa un codice monouso.',
      register: 'Crea il tuo account Autorell con email e password oppure usa un codice monouso.',
    },
    email: 'Email',
    emailPlaceholder: 'Inserisci la tua email',
    password: 'Password',
    confirmPassword: 'Conferma password',
    forgotPassword: 'Password dimenticata?',
    showPassword: 'Mostra password',
    hidePassword: 'Nascondi password',
    remember: 'Ricorda la mia email',
    continue: 'Invia codice',
    passwordSubmit: { login: 'Accedi', register: 'Crea account' },
    passwordLoading: { login: 'Accesso...', register: 'Creazione account...' },
    sending: 'Invio codice...',
    codeTitle: 'Inserisci il codice',
    codeSent: 'Abbiamo inviato un codice a sei cifre a',
    digit: 'Cifra del codice',
    submitCode: { login: 'Accedi', register: 'Continua' },
    verifying: 'Verifica codice...',
    resend: 'Invia un nuovo codice',
    resendIn: 'Nuovo codice tra',
    back: 'Cambia email',
    newHere: 'Nuovo su Autorell?',
    haveAccount: 'Hai già un account?',
    useCodeInstead: 'Usa codice monouso',
    usePasswordInstead: 'Usa password',
    invalidPassword: 'Email o password non corretti. Se ti sei registrato con un codice, usa il codice o reimposta prima la password.',
    passwordMismatch: 'Le password non corrispondono.',
    signupError: 'Non è stato possibile creare l’account. Se l’email usa già il codice, reimposta la password o continua con codice.',
    confirmEmailSent: 'Se serve conferma email, apri l’email inviata e poi continua a creare il profilo.',
    emailRequired: 'Inserisci la tua email.',
    sendReset: 'Invia link',
    sendingReset: 'Invio link...',
    resetSent: 'Se esiste un account con questa email, abbiamo inviato un link.',
    backToLogin: 'Torna al login',
    savePassword: 'Salva nuova password',
    savingPassword: 'Salvataggio...',
    passwordUpdated: 'La password è stata aggiornata. Accedi di nuovo.',
    resetError: 'Non è stato possibile aggiornare la password. Apri l’ultimo link e riprova.',
    sendError: 'Impossibile inviare il codice.',
    codeError: 'Il codice è errato o scaduto.',
    connectionError: 'La connessione è stata interrotta. Riprova.',
    chooseMarket: 'Scegli lingua e mercato',
    spamHint: 'Se non trovi l’email, controlla spam o posta indesiderata.',
  },
  pl: {
    loginTab: 'Zaloguj się',
    registerTab: 'Utwórz konto',
    close: 'Zamknij',
    title: { login: 'Witamy ponownie', register: 'Utwórz konto', forgot: 'Zresetuj hasło', reset: 'Wybierz nowe hasło' },
    description: {
      login: 'Wpisz e-mail, a wyślemy jednorazowy kod logowania.',
      register: 'Zacznij od e-maila. Przed kontynuacją wyślemy kod.',
      forgot: 'Wpisz e-mail, a wyślemy bezpieczny link resetowania.',
      reset: 'Wybierz nowe hasło do konta Autorell.',
    },
    passwordDescription: {
      login: 'Zaloguj się e-mailem i hasłem albo użyj kodu jednorazowego.',
      register: 'Utwórz konto Autorell e-mailem i hasłem albo użyj kodu jednorazowego.',
    },
    email: 'E-mail',
    emailPlaceholder: 'Wpisz e-mail',
    password: 'Hasło',
    confirmPassword: 'Potwierdź hasło',
    forgotPassword: 'Nie pamiętasz hasła?',
    showPassword: 'Pokaż hasło',
    hidePassword: 'Ukryj hasło',
    remember: 'Zapamiętaj mój e-mail',
    continue: 'Wyślij kod',
    passwordSubmit: { login: 'Zaloguj się', register: 'Utwórz konto' },
    passwordLoading: { login: 'Logowanie...', register: 'Tworzenie konta...' },
    sending: 'Wysyłanie kodu...',
    codeTitle: 'Wpisz kod',
    codeSent: 'Wysłaliśmy sześciocyfrowy kod na',
    digit: 'Cyfra kodu',
    submitCode: { login: 'Zaloguj się', register: 'Kontynuuj' },
    verifying: 'Sprawdzanie kodu...',
    resend: 'Wyślij nowy kod',
    resendIn: 'Nowy kod za',
    back: 'Zmień e-mail',
    newHere: 'Nowy w Autorell?',
    haveAccount: 'Masz już konto?',
    useCodeInstead: 'Użyj kodu jednorazowego',
    usePasswordInstead: 'Użyj hasła',
    invalidPassword: 'E-mail lub hasło jest nieprawidłowe. Jeśli konto utworzono kodem, użyj kodu albo najpierw zresetuj hasło.',
    passwordMismatch: 'Hasła nie są zgodne.',
    signupError: 'Nie można utworzyć konta. Jeśli e-mail używa już kodu, zresetuj hasło albo kontynuuj kodem.',
    confirmEmailSent: 'Jeśli wymagana jest weryfikacja e-mail, otwórz wiadomość i kontynuuj tworzenie profilu.',
    emailRequired: 'Wpisz adres e-mail.',
    sendReset: 'Wyślij link',
    sendingReset: 'Wysyłanie linku...',
    resetSent: 'Jeśli istnieje konto dla tego e-maila, wysłaliśmy link.',
    backToLogin: 'Powrót do logowania',
    savePassword: 'Zapisz nowe hasło',
    savingPassword: 'Zapisywanie hasła...',
    passwordUpdated: 'Hasło zostało zaktualizowane. Zaloguj się ponownie.',
    resetError: 'Nie można zaktualizować hasła. Otwórz najnowszy link i spróbuj ponownie.',
    sendError: 'Nie można wysłać kodu.',
    codeError: 'Kod jest nieprawidłowy lub wygasł.',
    connectionError: 'Połączenie zostało przerwane. Spróbuj ponownie.',
    chooseMarket: 'Wybierz język i rynek',
    spamHint: 'Jeśli nie widzisz wiadomości, sprawdź spam.',
  },
  nl: {
    loginTab: 'Inloggen',
    registerTab: 'Account maken',
    close: 'Sluiten',
    title: { login: 'Welkom terug', register: 'Maak je account', forgot: 'Wachtwoord resetten', reset: 'Kies een nieuw wachtwoord' },
    description: {
      login: 'Vul je e-mail in en we sturen een eenmalige inlogcode.',
      register: 'Begin met je e-mail. We sturen een code voordat je verdergaat.',
      forgot: 'Vul je e-mail in en we sturen een beveiligde resetlink.',
      reset: 'Kies een nieuw wachtwoord voor je Autorell-account.',
    },
    passwordDescription: {
      login: 'Log in met e-mail en wachtwoord, of gebruik een eenmalige code.',
      register: 'Maak je Autorell-account met e-mail en wachtwoord, of gebruik een eenmalige code.',
    },
    email: 'E-mail',
    emailPlaceholder: 'Vul je e-mail in',
    password: 'Wachtwoord',
    confirmPassword: 'Bevestig wachtwoord',
    forgotPassword: 'Wachtwoord vergeten?',
    showPassword: 'Wachtwoord tonen',
    hidePassword: 'Wachtwoord verbergen',
    remember: 'Onthoud mijn e-mail',
    continue: 'Code verzenden',
    passwordSubmit: { login: 'Inloggen', register: 'Account maken' },
    passwordLoading: { login: 'Inloggen...', register: 'Account maken...' },
    sending: 'Code verzenden...',
    codeTitle: 'Voer je code in',
    codeSent: 'We hebben een zescijferige code gestuurd naar',
    digit: 'Codecijfer',
    submitCode: { login: 'Inloggen', register: 'Doorgaan' },
    verifying: 'Code controleren...',
    resend: 'Nieuwe code verzenden',
    resendIn: 'Nieuwe code over',
    back: 'E-mail wijzigen',
    newHere: 'Nieuw bij Autorell?',
    haveAccount: 'Heb je al een account?',
    useCodeInstead: 'Eenmalige code gebruiken',
    usePasswordInstead: 'Wachtwoord gebruiken',
    invalidPassword: 'E-mail of wachtwoord is onjuist. Als je met een code bent geregistreerd, gebruik de code of reset eerst je wachtwoord.',
    passwordMismatch: 'De wachtwoorden komen niet overeen.',
    signupError: 'Het account kon niet worden gemaakt. Als de e-mail al code gebruikt, reset het wachtwoord of ga verder met code.',
    confirmEmailSent: 'Als e-mailbevestiging nodig is, open dan de e-mail en ga daarna verder met je profiel.',
    emailRequired: 'Vul je e-mailadres in.',
    sendReset: 'Resetlink verzenden',
    sendingReset: 'Resetlink verzenden...',
    resetSent: 'Als er een account bestaat voor deze e-mail, hebben we een link gestuurd.',
    backToLogin: 'Terug naar inloggen',
    savePassword: 'Nieuw wachtwoord opslaan',
    savingPassword: 'Wachtwoord opslaan...',
    passwordUpdated: 'Je wachtwoord is bijgewerkt. Log opnieuw in.',
    resetError: 'Het wachtwoord kon niet worden bijgewerkt. Open de nieuwste link en probeer opnieuw.',
    sendError: 'De code kon niet worden verzonden.',
    codeError: 'De code is onjuist of verlopen.',
    connectionError: 'De verbinding werd onderbroken. Probeer opnieuw.',
    chooseMarket: 'Kies taal en markt',
    spamHint: 'Kun je de e-mail niet vinden, controleer dan spam of ongewenste mail.',
  },
  fi: {
    loginTab: 'Kirjaudu',
    registerTab: 'Luo tili',
    close: 'Sulje',
    title: { login: 'Tervetuloa takaisin', register: 'Luo tilisi', forgot: 'Palauta salasana', reset: 'Valitse uusi salasana' },
    description: {
      login: 'Anna sähköpostisi, niin lähetämme kertakäyttöisen kirjautumiskoodin.',
      register: 'Aloita sähköpostilla. Lähetämme koodin ennen jatkamista.',
      forgot: 'Anna sähköpostisi, niin lähetämme turvallisen palautuslinkin.',
      reset: 'Valitse uusi salasana Autorell-tilillesi.',
    },
    passwordDescription: {
      login: 'Kirjaudu sähköpostilla ja salasanalla tai käytä kertakäyttökoodia.',
      register: 'Luo Autorell-tili sähköpostilla ja salasanalla tai käytä kertakäyttökoodia.',
    },
    email: 'Sähköposti',
    emailPlaceholder: 'Anna sähköpostisi',
    password: 'Salasana',
    confirmPassword: 'Vahvista salasana',
    forgotPassword: 'Unohditko salasanan?',
    showPassword: 'Näytä salasana',
    hidePassword: 'Piilota salasana',
    remember: 'Muista sähköpostini',
    continue: 'Lähetä koodi',
    passwordSubmit: { login: 'Kirjaudu', register: 'Luo tili' },
    passwordLoading: { login: 'Kirjaudutaan...', register: 'Luodaan tiliä...' },
    sending: 'Lähetetään koodia...',
    codeTitle: 'Anna koodi',
    codeSent: 'Lähetimme kuusinumeroisen koodin osoitteeseen',
    digit: 'Koodin numero',
    submitCode: { login: 'Kirjaudu', register: 'Jatka' },
    verifying: 'Tarkistetaan koodia...',
    resend: 'Lähetä uusi koodi',
    resendIn: 'Uusi koodi',
    back: 'Vaihda sähköposti',
    newHere: 'Uusi Autorellissa?',
    haveAccount: 'Onko sinulla jo tili?',
    useCodeInstead: 'Käytä kertakäyttökoodia',
    usePasswordInstead: 'Käytä salasanaa',
    invalidPassword: 'Sähköposti tai salasana on väärä. Jos rekisteröidyit koodilla, käytä koodia tai palauta salasana ensin.',
    passwordMismatch: 'Salasanat eivät täsmää.',
    signupError: 'Tiliä ei voitu luoda. Jos sähköposti käyttää jo koodia, palauta salasana tai jatka koodilla.',
    confirmEmailSent: 'Jos sähköpostivahvistus vaaditaan, avaa lähettämämme viesti ja jatka profiilin luontia.',
    emailRequired: 'Anna sähköpostiosoitteesi.',
    sendReset: 'Lähetä linkki',
    sendingReset: 'Lähetetään linkkiä...',
    resetSent: 'Jos tälle sähköpostille on tili, olemme lähettäneet linkin.',
    backToLogin: 'Takaisin kirjautumiseen',
    savePassword: 'Tallenna uusi salasana',
    savingPassword: 'Tallennetaan...',
    passwordUpdated: 'Salasana on päivitetty. Kirjaudu uudelleen.',
    resetError: 'Salasanaa ei voitu päivittää. Avaa uusin linkki ja yritä uudelleen.',
    sendError: 'Koodia ei voitu lähettää.',
    codeError: 'Koodi on väärä tai vanhentunut.',
    connectionError: 'Yhteys katkesi. Yritä uudelleen.',
    chooseMarket: 'Valitse kieli ja markkina',
    spamHint: 'Jos et löydä viestiä, tarkista roskaposti.',
  },
  da: {
    loginTab: 'Log ind',
    registerTab: 'Opret konto',
    close: 'Luk',
    title: { login: 'Velkommen tilbage', register: 'Opret din konto', forgot: 'Nulstil adgangskode', reset: 'Vælg en ny adgangskode' },
    description: {
      login: 'Indtast din e-mail, så sender vi en engangskode.',
      register: 'Start med din e-mail. Vi sender en kode, før du fortsætter.',
      forgot: 'Indtast din e-mail, så sender vi et sikkert nulstillingslink.',
      reset: 'Vælg en ny adgangskode til din Autorell-konto.',
    },
    passwordDescription: {
      login: 'Log ind med e-mail og adgangskode, eller brug en engangskode.',
      register: 'Opret din Autorell-konto med e-mail og adgangskode, eller brug en engangskode.',
    },
    email: 'E-mail',
    emailPlaceholder: 'Indtast din e-mail',
    password: 'Adgangskode',
    confirmPassword: 'Bekræft adgangskode',
    forgotPassword: 'Glemt adgangskode?',
    showPassword: 'Vis adgangskode',
    hidePassword: 'Skjul adgangskode',
    remember: 'Husk min e-mail',
    continue: 'Send kode',
    passwordSubmit: { login: 'Log ind', register: 'Opret konto' },
    passwordLoading: { login: 'Logger ind...', register: 'Opretter konto...' },
    sending: 'Sender kode...',
    codeTitle: 'Indtast din kode',
    codeSent: 'Vi har sendt en sekscifret kode til',
    digit: 'Kodeciffer',
    submitCode: { login: 'Log ind', register: 'Fortsæt' },
    verifying: 'Tjekker kode...',
    resend: 'Send en ny kode',
    resendIn: 'Ny kode om',
    back: 'Skift e-mail',
    newHere: 'Ny hos Autorell?',
    haveAccount: 'Har du allerede en konto?',
    useCodeInstead: 'Brug engangskode',
    usePasswordInstead: 'Brug adgangskode',
    invalidPassword: 'E-mail eller adgangskode er forkert. Hvis du oprettede konto med kode, brug koden eller nulstil adgangskoden først.',
    passwordMismatch: 'Adgangskoderne matcher ikke.',
    signupError: 'Kontoen kunne ikke oprettes. Hvis e-mailen allerede bruger kode, nulstil adgangskoden eller fortsæt med kode.',
    confirmEmailSent: 'Hvis e-mailbekræftelse kræves, åbn mailen og fortsæt derefter med profilen.',
    emailRequired: 'Indtast din e-mailadresse.',
    sendReset: 'Send link',
    sendingReset: 'Sender link...',
    resetSent: 'Hvis der findes en konto for denne e-mail, har vi sendt et link.',
    backToLogin: 'Tilbage til login',
    savePassword: 'Gem ny adgangskode',
    savingPassword: 'Gemmer...',
    passwordUpdated: 'Din adgangskode er opdateret. Log ind igen.',
    resetError: 'Adgangskoden kunne ikke opdateres. Åbn det nyeste link og prøv igen.',
    sendError: 'Koden kunne ikke sendes.',
    codeError: 'Koden er forkert eller udløbet.',
    connectionError: 'Forbindelsen blev afbrudt. Prøv igen.',
    chooseMarket: 'Vælg sprog og marked',
    spamHint: 'Hvis du ikke kan finde mailen, så tjek spam eller uønsket mail.',
  },
} as const

type ModalBaseKey = keyof typeof modalBase

function copyKey(locale: PublicLocale): ModalBaseKey {
  const translated = translationLocale(locale)
  return translated in modalBase ? translated as ModalBaseKey : 'en'
}

export function getLocalizedAuthModalCopy(locale: PublicLocale, mode: AuthMode, view: AuthView = mode): AuthModalCopy {
  const source = modalBase[copyKey(locale)]
  return {
    loginTab: source.loginTab,
    registerTab: source.registerTab,
    close: source.close,
    title: source.title[view],
    description: source.description[view],
    passwordDescription: source.passwordDescription[mode],
    email: source.email,
    emailPlaceholder: source.emailPlaceholder,
    password: source.password,
    confirmPassword: source.confirmPassword,
    forgotPassword: source.forgotPassword,
    showPassword: source.showPassword,
    hidePassword: source.hidePassword,
    passwordRequirement: passwordRequirements[copyKey(locale)] || passwordRequirements.en,
    remember: source.remember,
    continue: source.continue,
    passwordSubmit: source.passwordSubmit[mode],
    passwordLoading: source.passwordLoading[mode],
    sending: source.sending,
    codeTitle: source.codeTitle,
    codeSent: source.codeSent,
    digit: source.digit,
    submitCode: source.submitCode[mode],
    verifying: source.verifying,
    resend: source.resend,
    resendIn: source.resendIn,
    back: source.back,
    newHere: source.newHere,
    haveAccount: source.haveAccount,
    useCodeInstead: source.useCodeInstead,
    usePasswordInstead: source.usePasswordInstead,
    invalidPassword: source.invalidPassword,
    passwordMismatch: source.passwordMismatch,
    signupError: source.signupError,
    confirmEmailSent: source.confirmEmailSent,
    emailRequired: source.emailRequired,
    sendReset: source.sendReset,
    sendingReset: source.sendingReset,
    resetSent: source.resetSent,
    backToLogin: source.backToLogin,
    savePassword: source.savePassword,
    savingPassword: source.savingPassword,
    passwordUpdated: source.passwordUpdated,
    resetError: source.resetError,
    sendError: source.sendError,
    codeError: source.codeError,
    connectionError: source.connectionError,
    chooseMarket: source.chooseMarket,
  }
}

export function getAuthSpamHintCopy(locale: PublicLocale) {
  return modalBase[copyKey(locale)].spamHint
}

export function getAuthApiCopy(locale: PublicLocale): AuthApiCopy {
  const modal = getLocalizedAuthModalCopy(locale, 'login')
  return {
    emailRequired: modal.emailRequired,
    passwordRequirement: modal.passwordRequirement,
    passwordMismatch: modal.passwordMismatch,
    signupError: modal.signupError,
    sendError: modal.sendError,
    codeError: modal.codeError,
    connectionError: modal.connectionError,
    rateLimited: {
      en: 'Wait a few minutes before requesting more codes.',
      sv: 'Vänta några minuter innan du begär fler koder.',
      de: 'Warten Sie einige Minuten, bevor Sie weitere Codes anfordern.',
      fr: 'Attendez quelques minutes avant de demander d’autres codes.',
      es: 'Espera unos minutos antes de pedir más códigos.',
      it: 'Attendi qualche minuto prima di richiedere altri codici.',
      pl: 'Poczekaj kilka minut przed zamówieniem kolejnych kodów.',
      nl: 'Wacht enkele minuten voordat je meer codes aanvraagt.',
      fi: 'Odota muutama minuutti ennen uusien koodien pyytämistä.',
      da: 'Vent et par minutter, før du anmoder om flere koder.',
    }[copyKey(locale)],
    waitBeforeNewCode: {
      en: 'Wait a few seconds before requesting a new code.',
      sv: 'Vänta några sekunder innan du begär en ny kod.',
      de: 'Warten Sie einige Sekunden, bevor Sie einen neuen Code anfordern.',
      fr: 'Attendez quelques secondes avant de demander un nouveau code.',
      es: 'Espera unos segundos antes de pedir un nuevo código.',
      it: 'Attendi qualche secondo prima di richiedere un nuovo codice.',
      pl: 'Poczekaj kilka sekund przed zamówieniem nowego kodu.',
      nl: 'Wacht enkele seconden voordat je een nieuwe code aanvraagt.',
      fi: 'Odota muutama sekunti ennen uuden koodin pyytämistä.',
      da: 'Vent et par sekunder, før du anmoder om en ny kode.',
    }[copyKey(locale)],
    emailUnavailable: {
      en: 'Email sign-in is temporarily unavailable.',
      sv: 'Inloggning via mejl är tillfälligt otillgänglig.',
      de: 'E-Mail-Anmeldung ist vorübergehend nicht verfügbar.',
      fr: 'La connexion par e-mail est temporairement indisponible.',
      es: 'El inicio de sesión por correo no está disponible temporalmente.',
      it: 'L’accesso via email non è temporaneamente disponibile.',
      pl: 'Logowanie e-mailem jest tymczasowo niedostępne.',
      nl: 'Inloggen via e-mail is tijdelijk niet beschikbaar.',
      fi: 'Sähköpostikirjautuminen ei ole tilapäisesti käytettävissä.',
      da: 'Login via e-mail er midlertidigt utilgængeligt.',
    }[copyKey(locale)],
    tooManyAttempts: {
      en: 'Too many attempts. Wait a while and try again.',
      sv: 'För många försök. Vänta en stund och försök igen.',
      de: 'Zu viele Versuche. Warten Sie kurz und versuchen Sie es erneut.',
      fr: 'Trop de tentatives. Attendez un moment et réessayez.',
      es: 'Demasiados intentos. Espera un momento e inténtalo de nuevo.',
      it: 'Troppi tentativi. Attendi e riprova.',
      pl: 'Zbyt wiele prób. Poczekaj chwilę i spróbuj ponownie.',
      nl: 'Te veel pogingen. Wacht even en probeer opnieuw.',
      fi: 'Liian monta yritystä. Odota hetki ja yritä uudelleen.',
      da: 'For mange forsøg. Vent lidt og prøv igen.',
    }[copyKey(locale)],
    usedCode: {
      en: 'The code has already been used. Request a new code.',
      sv: 'Koden har redan använts. Begär en ny kod.',
      de: 'Der Code wurde bereits verwendet. Fordern Sie einen neuen Code an.',
      fr: 'Le code a déjà été utilisé. Demandez un nouveau code.',
      es: 'El código ya se ha usado. Solicita uno nuevo.',
      it: 'Il codice è già stato usato. Richiedi un nuovo codice.',
      pl: 'Kod został już użyty. Poproś o nowy kod.',
      nl: 'De code is al gebruikt. Vraag een nieuwe code aan.',
      fi: 'Koodi on jo käytetty. Pyydä uusi koodi.',
      da: 'Koden er allerede brugt. Anmod om en ny kode.',
    }[copyKey(locale)],
    recoveryUnavailable: {
      en: 'Password recovery is temporarily unavailable.',
      sv: 'Lösenordsåterställning är tillfälligt otillgänglig.',
      de: 'Passwort-Wiederherstellung ist vorübergehend nicht verfügbar.',
      fr: 'La réinitialisation du mot de passe est temporairement indisponible.',
      es: 'La recuperación de contraseña no está disponible temporalmente.',
      it: 'Il recupero password non è temporaneamente disponibile.',
      pl: 'Reset hasła jest tymczasowo niedostępny.',
      nl: 'Wachtwoordherstel is tijdelijk niet beschikbaar.',
      fi: 'Salasanan palautus ei ole tilapäisesti käytettävissä.',
      da: 'Nulstilling af adgangskode er midlertidigt utilgængelig.',
    }[copyKey(locale)],
  }
}
