import { translationLocale, type PublicLocale } from '@/lib/public-i18n'

export type BusinessPlanCopy = {
  intro: string
  recommended: string
  plans: Array<{
    name: 'Starter' | 'Growth' | 'Professional' | 'Enterprise'
    audience: string
    price: string
    period: string
    limit: string
    text: string
    cta: string
    hrefKind: 'register' | 'pricing' | 'contact'
    recommended?: boolean
    features: string[]
  }>
  faqs: Array<[string, string]>
}

const copies: Record<string, BusinessPlanCopy> = {
  en: {
    intro: 'Choose a plan based on inventory, team and the number of listings you need active at the same time.', recommended: 'Recommended',
    plans: [
      { name: 'Starter', audience: 'Small dealers', price: '499 kr', period: '/month', limit: '25 active listings', text: 'For smaller inventories that need a dealer profile and a more professional listing flow.', cta: 'Create account', hrefKind: 'register', features: ['Basic dealer profile', 'Logo and contact route', 'Standard enquiries', 'Manual listing publication', 'CSV import', 'Basic inventory management'] },
      { name: 'Growth', audience: 'Growing team', price: '999 kr', period: '/month', limit: '100 active listings', text: 'For companies where several sellers work in one account and publish continuously.', cta: 'View pricing', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 team accounts', 'Seller roles', 'Automatic inventory import', 'Import from the company website', 'Automatic price updates', 'Automatic inventory status updates', 'Daily synchronisation', 'Multiple users', 'Basic lead statistics'] },
      { name: 'Professional', audience: 'High volume', price: '1 999 kr', period: '/month', limit: '500 active listings', text: 'For larger inventories with high volume, more sellers and better follow-up.', cta: 'Compare plan', hrefKind: 'pricing', features: ['Dealer solutions Pro', '50+ team accounts', 'Reports and export', 'Website import', 'CSV and XML feed', 'API integration', 'Multiple locations', 'Synchronisation several times per day', 'Advanced lead and inventory statistics', 'Teams and roles', 'Priority support'] },
      { name: 'Enterprise', audience: 'Tailored', price: 'Custom', period: '', limit: 'Custom quota', text: 'For importers, groups and operators with specific volume and process requirements.', cta: 'Contact us', hrefKind: 'contact', features: ['Advanced dealer solution', 'Extended team', 'Enterprise support', 'Custom inventory integration', 'API, XML, CSV and DMS', 'Multiple companies and locations', 'Custom data mapping', 'Near real-time synchronisation where technically possible', 'Dedicated onboarding', 'Technical contact person', 'Custom commercial agreement', 'SLA as a separate contractual option'] },
    ],
    faqs: [['Which plan suits smaller dealers?', 'Starter suits companies that want a professional company page and up to 25 active listings without a larger team workflow.'], ['When do we need Growth?', 'Growth suits a growing inventory where several sellers work in the same account and automatic inventory updates are needed.'], ['What is different about Professional?', 'Professional is for larger inventories with multiple locations, integrations, advanced statistics and priority support.'], ['Is Enterprise available for groups and importers?', 'Yes. Enterprise is tailored for larger operators with specific needs for volume, integration, process, support and presentation.']],
  },
  sv: {
    intro: 'Välj plan efter lager, team och hur många annonser ni vill ha aktiva samtidigt.', recommended: 'Rekommenderad',
    plans: [
      { name: 'Starter', audience: 'Mindre handlare', price: '499 kr', period: '/mån', limit: '25 aktiva annonser', text: 'För mindre lager som behöver dealer-profil och ett mer professionellt annonsflöde.', cta: 'Skapa konto', hrefKind: 'register', features: ['Dealer-profil Basic', 'Logo och kontaktväg', 'Standardförfrågningar', 'Manuell annonspublicering', 'CSV-import', 'Grundläggande lagerhantering'] },
      { name: 'Growth', audience: 'Växande team', price: '999 kr', period: '/mån', limit: '100 aktiva annonser', text: 'För företag där flera säljare arbetar i samma konto och publicerar löpande.', cta: 'Se priser', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 teamkonton', 'Roller för säljare', 'Automatisk lagerimport', 'Import från företagets webbplats', 'Automatisk uppdatering av priser', 'Automatisk uppdatering av lagerstatus', 'Daglig synk', 'Flera användare', 'Grundläggande leadstatistik'] },
      { name: 'Professional', audience: 'Hög volym', price: '1 999 kr', period: '/mån', limit: '500 aktiva annonser', text: 'För större lager med hög volym, fler säljare och bättre uppföljning.', cta: 'Jämför plan', hrefKind: 'pricing', features: ['Dealer solutions Pro', '50+ teamkonton', 'Rapporter och export', 'Webbplatsimport', 'CSV- och XML-feed', 'API-integration', 'Flera anläggningar', 'Synk flera gånger per dag', 'Avancerad lead- och lagerstatistik', 'Team och roller', 'Prioriterad support'] },
      { name: 'Enterprise', audience: 'Anpassat', price: 'Anpassat', period: '', limit: 'Anpassad kvot', text: 'För importörer, kedjor och operatörer med särskilda behov för volym och process.', cta: 'Kontakta oss', hrefKind: 'contact', features: ['Avancerad dealer-lösning', 'Utökat team', 'Enterprise-support', 'Anpassad lagerintegration', 'API, XML, CSV och DMS', 'Flera bolag och anläggningar', 'Anpassad datamappning', 'Nära realtidssynk där det är tekniskt möjligt', 'Dedikerad onboarding', 'Teknisk kontaktperson', 'Anpassat kommersiellt avtal', 'SLA som separat avtalsmöjlighet'] },
    ],
    faqs: [['Vilken plan passar mindre handlare?', 'Starter passar företag som vill ha en professionell företagssida och upp till 25 aktiva annonser utan ett större teamflöde.'], ['När behöver vi Growth?', 'Growth passar när flera säljare arbetar i samma konto och lagret behöver uppdateras automatiskt.'], ['Vad är skillnaden med Professional?', 'Professional är för större lager med flera anläggningar, integrationer, avancerad statistik och prioriterad support.'], ['Finns Enterprise för kedjor och importörer?', 'Ja. Enterprise anpassas för större aktörer med särskilda behov kring volym, integration, process, support och presentation.']],
  },
  de: {
    intro: 'Wählen Sie den Plan passend zu Bestand, Team und der Anzahl gleichzeitig aktiver Anzeigen.', recommended: 'Empfohlen',
    plans: [
      { name: 'Starter', audience: 'Kleine Händler', price: '499 kr', period: '/Monat', limit: '25 aktive Anzeigen', text: 'Für kleinere Bestände, die ein Händlerprofil und einen professionelleren Anzeigenablauf benötigen.', cta: 'Konto erstellen', hrefKind: 'register', features: ['Basis-Händlerprofil', 'Logo und Kontaktweg', 'Standardanfragen', 'Manuelle Anzeigenveröffentlichung', 'CSV-Import', 'Grundlegende Bestandsverwaltung'] },
      { name: 'Growth', audience: 'Wachsendes Team', price: '999 kr', period: '/Monat', limit: '100 aktive Anzeigen', text: 'Für Unternehmen, in denen mehrere Verkäufer in einem Konto laufend veröffentlichen.', cta: 'Preise ansehen', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 Teamkonten', 'Verkäuferrollen', 'Automatischer Bestandsimport', 'Import von der Unternehmenswebsite', 'Automatische Preisaktualisierung', 'Automatische Aktualisierung des Bestandsstatus', 'Tägliche Synchronisierung', 'Mehrere Benutzer', 'Grundlegende Lead-Statistik'] },
      { name: 'Professional', audience: 'Hohes Volumen', price: '1 999 kr', period: '/Monat', limit: '500 aktive Anzeigen', text: 'Für größere Bestände mit hohem Volumen, mehr Verkäufern und besserer Auswertung.', cta: 'Plan vergleichen', hrefKind: 'pricing', features: ['Dealer solutions Pro', '50+ Teamkonten', 'Berichte und Export', 'Website-Import', 'CSV- und XML-Feed', 'API-Integration', 'Mehrere Standorte', 'Mehrmals tägliche Synchronisierung', 'Erweiterte Lead- und Bestandsstatistik', 'Teams und Rollen', 'Priorisierter Support'] },
      { name: 'Enterprise', audience: 'Individuell', price: 'Individuell', period: '', limit: 'Individuelles Kontingent', text: 'Für Importeure, Gruppen und Betreiber mit besonderen Anforderungen an Volumen und Prozesse.', cta: 'Kontakt aufnehmen', hrefKind: 'contact', features: ['Erweiterte Händlerlösung', 'Erweitertes Team', 'Enterprise-Support', 'Individuelle Bestandsintegration', 'API, XML, CSV und DMS', 'Mehrere Unternehmen und Standorte', 'Individuelles Datenmapping', 'Nahezu Echtzeit-Synchronisierung, soweit technisch möglich', 'Dediziertes Onboarding', 'Technische Kontaktperson', 'Individuelle kommerzielle Vereinbarung', 'SLA als separate Vertragsoption'] },
    ],
    faqs: [['Welcher Plan passt zu kleineren Händlern?', 'Starter eignet sich für Unternehmen mit professioneller Unternehmensseite und bis zu 25 aktiven Anzeigen ohne größeren Teamablauf.'], ['Wann benötigen wir Growth?', 'Growth eignet sich, wenn mehrere Verkäufer in einem Konto arbeiten und der Bestand automatisch aktualisiert werden soll.'], ['Was unterscheidet Professional?', 'Professional ist für größere Bestände mit mehreren Standorten, Integrationen, erweiterten Statistiken und priorisiertem Support.'], ['Gibt es Enterprise für Gruppen und Importeure?', 'Ja. Enterprise wird für größere Akteure mit besonderen Anforderungen an Volumen, Integration, Prozesse, Support und Präsentation angepasst.']],
  },
  fr: {
    intro: 'Choisissez un forfait selon votre stock, votre équipe et le nombre d’annonces actives simultanément.', recommended: 'Recommandé',
    plans: [
      { name: 'Starter', audience: 'Petits distributeurs', price: '499 kr', period: '/mois', limit: '25 annonces actives', text: 'Pour les petits stocks qui nécessitent un profil professionnel et un flux d’annonces plus structuré.', cta: 'Créer un compte', hrefKind: 'register', features: ['Profil distributeur Basic', 'Logo et moyen de contact', 'Demandes standard', 'Publication manuelle des annonces', 'Import CSV', 'Gestion de stock de base'] },
      { name: 'Growth', audience: 'Équipe en croissance', price: '999 kr', period: '/mois', limit: '100 annonces actives', text: 'Pour les entreprises où plusieurs vendeurs travaillent et publient depuis un même compte.', cta: 'Voir les tarifs', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 comptes d’équipe', 'Rôles vendeur', 'Import automatique du stock', 'Import depuis le site de l’entreprise', 'Mise à jour automatique des prix', 'Mise à jour automatique du statut du stock', 'Synchronisation quotidienne', 'Plusieurs utilisateurs', 'Statistiques de prospects de base'] },
      { name: 'Professional', audience: 'Volume élevé', price: '1 999 kr', period: '/mois', limit: '500 annonces actives', text: 'Pour les stocks importants, avec davantage de vendeurs et un meilleur suivi.', cta: 'Comparer le forfait', hrefKind: 'pricing', features: ['Dealer solutions Pro', '50+ comptes d’équipe', 'Rapports et export', 'Import depuis un site web', 'Flux CSV et XML', 'Intégration API', 'Plusieurs établissements', 'Synchronisation plusieurs fois par jour', 'Statistiques avancées des prospects et du stock', 'Équipes et rôles', 'Support prioritaire'] },
      { name: 'Enterprise', audience: 'Sur mesure', price: 'Sur mesure', period: '', limit: 'Quota personnalisé', text: 'Pour les importateurs, groupes et opérateurs ayant des besoins particuliers de volume et de processus.', cta: 'Nous contacter', hrefKind: 'contact', features: ['Solution distributeur avancée', 'Équipe étendue', 'Support Enterprise', 'Intégration de stock personnalisée', 'API, XML, CSV et DMS', 'Plusieurs sociétés et établissements', 'Mappage de données personnalisé', 'Synchronisation quasi instantanée lorsque cela est techniquement possible', 'Onboarding dédié', 'Interlocuteur technique', 'Accord commercial personnalisé', 'SLA comme option contractuelle séparée'] },
    ],
    faqs: [['Quel forfait convient aux petits distributeurs ?', 'Starter convient aux entreprises qui souhaitent une page professionnelle et jusqu’à 25 annonces actives sans flux d’équipe complexe.'], ['Quand avons-nous besoin de Growth ?', 'Growth convient lorsque plusieurs vendeurs travaillent dans le même compte et que le stock doit être mis à jour automatiquement.'], ['Quelle est la différence avec Professional ?', 'Professional est conçu pour les stocks importants avec plusieurs établissements, des intégrations, des statistiques avancées et un support prioritaire.'], ['Enterprise est-il disponible pour les groupes et importateurs ?', 'Oui. Enterprise est adapté aux acteurs importants ayant des besoins particuliers de volume, d’intégration, de processus, de support et de présentation.']],
  },
  es: {
    intro: 'Elige el plan según el inventario, el equipo y la cantidad de anuncios activos simultáneamente.', recommended: 'Recomendado',
    plans: [
      { name: 'Starter', audience: 'Concesionarios pequeños', price: '499 kr', period: '/mes', limit: '25 anuncios activos', text: 'Para inventarios pequeños que necesitan un perfil profesional y un flujo de anuncios más estructurado.', cta: 'Crear cuenta', hrefKind: 'register', features: ['Perfil de concesionario Basic', 'Logotipo y vía de contacto', 'Consultas estándar', 'Publicación manual de anuncios', 'Importación CSV', 'Gestión básica del inventario'] },
      { name: 'Growth', audience: 'Equipo en crecimiento', price: '999 kr', period: '/mes', limit: '100 anuncios activos', text: 'Para empresas donde varios vendedores trabajan y publican desde la misma cuenta.', cta: 'Ver precios', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 cuentas de equipo', 'Roles de vendedor', 'Importación automática del inventario', 'Importación desde la web de la empresa', 'Actualización automática de precios', 'Actualización automática del estado del inventario', 'Sincronización diaria', 'Varios usuarios', 'Estadísticas básicas de leads'] },
      { name: 'Professional', audience: 'Gran volumen', price: '1 999 kr', period: '/mes', limit: '500 anuncios activos', text: 'Para inventarios grandes, más vendedores y un seguimiento más completo.', cta: 'Comparar plan', hrefKind: 'pricing', features: ['Dealer solutions Pro', 'Más de 50 cuentas de equipo', 'Informes y exportación', 'Importación desde la web', 'Canales CSV y XML', 'Integración API', 'Varias instalaciones', 'Sincronización varias veces al día', 'Estadísticas avanzadas de leads e inventario', 'Equipos y roles', 'Soporte prioritario'] },
      { name: 'Enterprise', audience: 'A medida', price: 'A medida', period: '', limit: 'Cuota personalizada', text: 'Para importadores, grupos y operadores con requisitos específicos de volumen y proceso.', cta: 'Contactar', hrefKind: 'contact', features: ['Solución avanzada para concesionarios', 'Equipo ampliado', 'Soporte Enterprise', 'Integración de inventario personalizada', 'API, XML, CSV y DMS', 'Varias empresas e instalaciones', 'Mapeo de datos personalizado', 'Sincronización casi en tiempo real cuando sea técnicamente posible', 'Onboarding dedicado', 'Persona de contacto técnica', 'Acuerdo comercial personalizado', 'SLA como opción contractual separada'] },
    ],
    faqs: [['¿Qué plan conviene a los concesionarios pequeños?', 'Starter es adecuado para empresas que desean una página profesional y hasta 25 anuncios activos sin un flujo de equipo amplio.'], ['¿Cuándo necesitamos Growth?', 'Growth es adecuado cuando varios vendedores trabajan en la misma cuenta y el inventario debe actualizarse automáticamente.'], ['¿Qué diferencia a Professional?', 'Professional está pensado para inventarios grandes con varias instalaciones, integraciones, estadísticas avanzadas y soporte prioritario.'], ['¿Enterprise está disponible para grupos e importadores?', 'Sí. Enterprise se adapta a grandes operadores con necesidades específicas de volumen, integración, proceso, soporte y presentación.']],
  },
  it: {
    intro: 'Scegli il piano in base all’inventario, al team e al numero di annunci attivi contemporaneamente.', recommended: 'Consigliato',
    plans: [
      { name: 'Starter', audience: 'Rivenditori piccoli', price: '499 kr', period: '/mese', limit: '25 annunci attivi', text: 'Per inventari più piccoli che richiedono un profilo professionale e un flusso di annunci più strutturato.', cta: 'Crea account', hrefKind: 'register', features: ['Profilo rivenditore Basic', 'Logo e canale di contatto', 'Richieste standard', 'Pubblicazione manuale degli annunci', 'Importazione CSV', 'Gestione inventario di base'] },
      { name: 'Growth', audience: 'Team in crescita', price: '999 kr', period: '/mese', limit: '100 annunci attivi', text: 'Per aziende in cui più venditori lavorano e pubblicano dallo stesso account.', cta: 'Vedi prezzi', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 account del team', 'Ruoli venditore', 'Importazione automatica dell’inventario', 'Importazione dal sito aziendale', 'Aggiornamento automatico dei prezzi', 'Aggiornamento automatico dello stato dell’inventario', 'Sincronizzazione giornaliera', 'Più utenti', 'Statistiche lead di base'] },
      { name: 'Professional', audience: 'Volume elevato', price: '1 999 kr', period: '/mese', limit: '500 annunci attivi', text: 'Per inventari più grandi, più venditori e un monitoraggio più completo.', cta: 'Confronta piano', hrefKind: 'pricing', features: ['Dealer solutions Pro', 'Oltre 50 account del team', 'Report ed esportazione', 'Importazione dal sito web', 'Feed CSV e XML', 'Integrazione API', 'Più sedi', 'Sincronizzazione più volte al giorno', 'Statistiche avanzate su lead e inventario', 'Team e ruoli', 'Supporto prioritario'] },
      { name: 'Enterprise', audience: 'Su misura', price: 'Su misura', period: '', limit: 'Quota personalizzata', text: 'Per importatori, gruppi e operatori con esigenze specifiche di volume e processo.', cta: 'Contattaci', hrefKind: 'contact', features: ['Soluzione avanzata per rivenditori', 'Team esteso', 'Supporto Enterprise', 'Integrazione inventario personalizzata', 'API, XML, CSV e DMS', 'Più aziende e sedi', 'Mappatura dati personalizzata', 'Sincronizzazione quasi in tempo reale dove tecnicamente possibile', 'Onboarding dedicato', 'Referente tecnico', 'Accordo commerciale personalizzato', 'SLA come opzione contrattuale separata'] },
    ],
    faqs: [['Quale piano è adatto ai rivenditori più piccoli?', 'Starter è adatto alle aziende che desiderano una pagina professionale e fino a 25 annunci attivi senza un ampio flusso di team.'], ['Quando serve Growth?', 'Growth è adatto quando più venditori lavorano nello stesso account e l’inventario deve aggiornarsi automaticamente.'], ['Cosa distingue Professional?', 'Professional è pensato per grandi inventari con più sedi, integrazioni, statistiche avanzate e supporto prioritario.'], ['Enterprise è disponibile per gruppi e importatori?', 'Sì. Enterprise viene adattato agli operatori più grandi con esigenze specifiche di volume, integrazione, processo, supporto e presentazione.']],
  },
  nl: {
    intro: 'Kies een plan op basis van voorraad, team en het aantal advertenties dat tegelijk actief moet zijn.', recommended: 'Aanbevolen',
    plans: [
      { name: 'Starter', audience: 'Kleine dealers', price: '499 kr', period: '/maand', limit: '25 actieve advertenties', text: 'Voor kleinere voorraden die een professioneel dealerprofiel en advertentieproces nodig hebben.', cta: 'Account maken', hrefKind: 'register', features: ['Basic dealerprofiel', 'Logo en contactmogelijkheid', 'Standaardaanvragen', 'Handmatige publicatie van advertenties', 'CSV-import', 'Basisvoorraadbeheer'] },
      { name: 'Growth', audience: 'Groeiend team', price: '999 kr', period: '/maand', limit: '100 actieve advertenties', text: 'Voor bedrijven waar meerdere verkopers vanuit één account doorlopend publiceren.', cta: 'Prijzen bekijken', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 teamaccounts', 'Verkopersrollen', 'Automatische voorraadimport', 'Import vanaf de bedrijfswebsite', 'Automatische prijsupdates', 'Automatische updates van de voorraadstatus', 'Dagelijkse synchronisatie', 'Meerdere gebruikers', 'Basisstatistieken voor leads'] },
      { name: 'Professional', audience: 'Hoog volume', price: '1 999 kr', period: '/maand', limit: '500 actieve advertenties', text: 'Voor grotere voorraden met een hoog volume, meer verkopers en betere opvolging.', cta: 'Plan vergelijken', hrefKind: 'pricing', features: ['Dealer solutions Pro', '50+ teamaccounts', 'Rapporten en export', 'Website-import', 'CSV- en XML-feed', 'API-integratie', 'Meerdere vestigingen', 'Meerdere synchronisaties per dag', 'Geavanceerde lead- en voorraadstatistieken', 'Teams en rollen', 'Prioriteitsondersteuning'] },
      { name: 'Enterprise', audience: 'Op maat', price: 'Op maat', period: '', limit: 'Aangepast quotum', text: 'Voor importeurs, groepen en operators met specifieke volume- en procesbehoeften.', cta: 'Contact opnemen', hrefKind: 'contact', features: ['Geavanceerde dealeroplossing', 'Uitgebreid team', 'Enterprise-ondersteuning', 'Aangepaste voorraadintegratie', 'API, XML, CSV en DMS', 'Meerdere bedrijven en vestigingen', 'Aangepaste datamapping', 'Bijna realtime synchronisatie waar technisch mogelijk', 'Persoonlijke onboarding', 'Technisch contactpersoon', 'Aangepaste commerciële overeenkomst', 'SLA als afzonderlijke contractoptie'] },
    ],
    faqs: [['Welk plan past bij kleinere dealers?', 'Starter past bij bedrijven die een professionele bedrijfspagina en maximaal 25 actieve advertenties willen zonder uitgebreide teamworkflow.'], ['Wanneer hebben we Growth nodig?', 'Growth past wanneer meerdere verkopers in hetzelfde account werken en de voorraad automatisch moet worden bijgewerkt.'], ['Wat maakt Professional anders?', 'Professional is voor grotere voorraden met meerdere vestigingen, integraties, geavanceerde statistieken en prioriteitsondersteuning.'], ['Is Enterprise beschikbaar voor groepen en importeurs?', 'Ja. Enterprise wordt aangepast voor grotere partijen met specifieke behoeften rond volume, integratie, proces, ondersteuning en presentatie.']],
  },
  fi: {
    intro: 'Valitkaa sopimus varaston, tiimin ja samanaikaisesti aktiivisten ilmoitusten määrän mukaan.', recommended: 'Suositeltu',
    plans: [
      { name: 'Starter', audience: 'Pienet jälleenmyyjät', price: '499 kr', period: '/kk', limit: '25 aktiivista ilmoitusta', text: 'Pienemmille varastoille, jotka tarvitsevat ammattimaisen jälleenmyyjäprofiilin ja ilmoitusprosessin.', cta: 'Luo tili', hrefKind: 'register', features: ['Basic-jälleenmyyjäprofiili', 'Logo ja yhteydenottotapa', 'Vakiokyselyt', 'Ilmoitusten manuaalinen julkaisu', 'CSV-tuonti', 'Varaston perushallinta'] },
      { name: 'Growth', audience: 'Kasvava tiimi', price: '999 kr', period: '/kk', limit: '100 aktiivista ilmoitusta', text: 'Yrityksille, joissa useat myyjät työskentelevät ja julkaisevat samalla tilillä.', cta: 'Näytä hinnat', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 tiimitiliä', 'Myyjäroolit', 'Automaattinen varastotuonti', 'Tuonti yrityksen verkkosivustolta', 'Automaattiset hintapäivitykset', 'Varastotilan automaattinen päivitys', 'Päivittäinen synkronointi', 'Useita käyttäjiä', 'Leadien perustilastot'] },
      { name: 'Professional', audience: 'Suuri volyymi', price: '1 999 kr', period: '/kk', limit: '500 aktiivista ilmoitusta', text: 'Suurille varastoille, suurelle volyymille, useammille myyjille ja parempaan seurantaan.', cta: 'Vertaa sopimusta', hrefKind: 'pricing', features: ['Dealer solutions Pro', '50+ tiimitiliä', 'Raportit ja vienti', 'Verkkosivutuonti', 'CSV- ja XML-syöte', 'API-integraatio', 'Useita toimipisteitä', 'Synkronointi useita kertoja päivässä', 'Edistyneet lead- ja varastotilastot', 'Tiimit ja roolit', 'Priorisoitu tuki'] },
      { name: 'Enterprise', audience: 'Räätälöity', price: 'Räätälöity', period: '', limit: 'Räätälöity kiintiö', text: 'Maahantuojille, ketjuille ja toimijoille, joilla on erityisiä volyymi- ja prosessitarpeita.', cta: 'Ota yhteyttä', hrefKind: 'contact', features: ['Edistynyt jälleenmyyjäratkaisu', 'Laajennettu tiimi', 'Enterprise-tuki', 'Räätälöity varastointegraatio', 'API, XML, CSV ja DMS', 'Useita yrityksiä ja toimipisteitä', 'Räätälöity datamäppäys', 'Lähes reaaliaikainen synkronointi teknisten mahdollisuuksien mukaan', 'Omistettu onboarding', 'Tekninen yhteyshenkilö', 'Räätälöity kaupallinen sopimus', 'SLA erillisenä sopimusvaihtoehtona'] },
    ],
    faqs: [['Mikä sopimus sopii pienemmille jälleenmyyjille?', 'Starter sopii yrityksille, jotka haluavat ammattimaisen yrityssivun ja enintään 25 aktiivista ilmoitusta ilman laajaa tiimiprosessia.'], ['Milloin tarvitsemme Growth-sopimuksen?', 'Growth sopii, kun useat myyjät työskentelevät samalla tilillä ja varasto on päivitettävä automaattisesti.'], ['Miten Professional eroaa muista?', 'Professional on tarkoitettu suurille varastoille, joilla on useita toimipisteitä, integraatioita, edistyneet tilastot ja priorisoitu tuki.'], ['Onko Enterprise saatavilla ketjuille ja maahantuojille?', 'Kyllä. Enterprise räätälöidään suurille toimijoille, joilla on erityisiä volyymi-, integraatio-, prosessi-, tuki- ja esittelytarpeita.']],
  },
  da: {
    intro: 'Vælg plan efter lager, team og hvor mange annoncer der skal være aktive samtidig.', recommended: 'Anbefalet',
    plans: [
      { name: 'Starter', audience: 'Mindre forhandlere', price: '499 kr', period: '/md.', limit: '25 aktive annoncer', text: 'Til mindre lagre, der har brug for en professionel forhandlerprofil og annonceproces.', cta: 'Opret konto', hrefKind: 'register', features: ['Basic-forhandlerprofil', 'Logo og kontaktvej', 'Standardforespørgsler', 'Manuel annoncepublicering', 'CSV-import', 'Grundlæggende lagerstyring'] },
      { name: 'Growth', audience: 'Voksende team', price: '999 kr', period: '/md.', limit: '100 aktive annoncer', text: 'Til virksomheder, hvor flere sælgere arbejder og publicerer fra samme konto.', cta: 'Se priser', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 teamkonti', 'Sælgerroller', 'Automatisk lagerimport', 'Import fra virksomhedens hjemmeside', 'Automatiske prisopdateringer', 'Automatisk opdatering af lagerstatus', 'Daglig synkronisering', 'Flere brugere', 'Grundlæggende leadstatistik'] },
      { name: 'Professional', audience: 'Høj volumen', price: '1 999 kr', period: '/md.', limit: '500 aktive annoncer', text: 'Til større lagre med høj volumen, flere sælgere og bedre opfølgning.', cta: 'Sammenlign plan', hrefKind: 'pricing', features: ['Dealer solutions Pro', '50+ teamkonti', 'Rapporter og eksport', 'Hjemmesideimport', 'CSV- og XML-feed', 'API-integration', 'Flere lokationer', 'Synkronisering flere gange dagligt', 'Avanceret lead- og lagerstatistik', 'Teams og roller', 'Prioriteret support'] },
      { name: 'Enterprise', audience: 'Tilpasset', price: 'Tilpasset', period: '', limit: 'Tilpasset kvote', text: 'Til importører, kæder og operatører med særlige behov for volumen og processer.', cta: 'Kontakt os', hrefKind: 'contact', features: ['Avanceret forhandlerløsning', 'Udvidet team', 'Enterprise-support', 'Tilpasset lagerintegration', 'API, XML, CSV og DMS', 'Flere selskaber og lokationer', 'Tilpasset datamapping', 'Næsten realtidssynkronisering hvor teknisk muligt', 'Dedikeret onboarding', 'Teknisk kontaktperson', 'Tilpasset kommerciel aftale', 'SLA som separat kontraktmulighed'] },
    ],
    faqs: [['Hvilken plan passer til mindre forhandlere?', 'Starter passer til virksomheder, der ønsker en professionel virksomhedsside og op til 25 aktive annoncer uden et større teamflow.'], ['Hvornår har vi brug for Growth?', 'Growth passer, når flere sælgere arbejder på samme konto, og lageret skal opdateres automatisk.'], ['Hvad adskiller Professional?', 'Professional er til større lagre med flere lokationer, integrationer, avanceret statistik og prioriteret support.'], ['Findes Enterprise til kæder og importører?', 'Ja. Enterprise tilpasses større aktører med særlige behov for volumen, integration, processer, support og præsentation.']],
  },
  pl: {
    intro: 'Wybierz plan według zapasów, zespołu i liczby ogłoszeń aktywnych w tym samym czasie.', recommended: 'Polecany',
    plans: [
      { name: 'Starter', audience: 'Mniejsi dealerzy', price: '499 kr', period: '/mies.', limit: '25 aktywnych ogłoszeń', text: 'Dla mniejszych zapasów wymagających profesjonalnego profilu dealera i procesu publikacji.', cta: 'Utwórz konto', hrefKind: 'register', features: ['Profil dealera Basic', 'Logo i sposób kontaktu', 'Standardowe zapytania', 'Ręczna publikacja ogłoszeń', 'Import CSV', 'Podstawowe zarządzanie zapasami'] },
      { name: 'Growth', audience: 'Rosnący zespół', price: '999 kr', period: '/mies.', limit: '100 aktywnych ogłoszeń', text: 'Dla firm, w których wielu sprzedawców pracuje i publikuje z jednego konta.', cta: 'Zobacz ceny', hrefKind: 'pricing', recommended: true, features: ['Dealer solutions Plus', '10 kont zespołu', 'Role sprzedawców', 'Automatyczny import zapasów', 'Import z witryny firmy', 'Automatyczne aktualizacje cen', 'Automatyczne aktualizacje statusu zapasów', 'Codzienna synchronizacja', 'Wielu użytkowników', 'Podstawowe statystyki leadów'] },
      { name: 'Professional', audience: 'Duża skala', price: '1 999 kr', period: '/mies.', limit: '500 aktywnych ogłoszeń', text: 'Dla większych zapasów, większej liczby sprzedawców i dokładniejszego monitorowania.', cta: 'Porównaj plan', hrefKind: 'pricing', features: ['Dealer solutions Pro', 'Ponad 50 kont zespołu', 'Raporty i eksport', 'Import z witryny', 'Kanał CSV i XML', 'Integracja API', 'Wiele lokalizacji', 'Synchronizacja kilka razy dziennie', 'Zaawansowane statystyki leadów i zapasów', 'Zespoły i role', 'Priorytetowe wsparcie'] },
      { name: 'Enterprise', audience: 'Indywidualny', price: 'Indywidualna', period: '', limit: 'Indywidualny limit', text: 'Dla importerów, grup i operatorów o szczególnych potrzebach dotyczących skali i procesów.', cta: 'Skontaktuj się', hrefKind: 'contact', features: ['Zaawansowane rozwiązanie dla dealerów', 'Rozszerzony zespół', 'Wsparcie Enterprise', 'Indywidualna integracja zapasów', 'API, XML, CSV i DMS', 'Wiele spółek i lokalizacji', 'Indywidualne mapowanie danych', 'Synchronizacja niemal w czasie rzeczywistym, gdy jest to technicznie możliwe', 'Dedykowane wdrożenie', 'Techniczna osoba kontaktowa', 'Indywidualna umowa handlowa', 'SLA jako osobna opcja umowna'] },
    ],
    faqs: [['Który plan pasuje do mniejszych dealerów?', 'Starter pasuje do firm, które chcą profesjonalnej strony firmowej i maksymalnie 25 aktywnych ogłoszeń bez rozbudowanego procesu zespołowego.'], ['Kiedy potrzebujemy Growth?', 'Growth pasuje, gdy wielu sprzedawców pracuje na jednym koncie, a zapasy powinny aktualizować się automatycznie.'], ['Czym różni się Professional?', 'Professional jest przeznaczony dla większych zapasów z wieloma lokalizacjami, integracjami, zaawansowanymi statystykami i priorytetowym wsparciem.'], ['Czy Enterprise jest dostępny dla grup i importerów?', 'Tak. Enterprise jest dostosowywany do większych podmiotów o szczególnych potrzebach dotyczących skali, integracji, procesów, wsparcia i prezentacji.']],
  },
}

export function getBusinessPlanCopy(locale: PublicLocale): BusinessPlanCopy {
  return copies[translationLocale(locale)] || copies.en
}
