export type EuBuyerLanguage =
  | 'bg'
  | 'cs'
  | 'da'
  | 'de'
  | 'el'
  | 'en'
  | 'es'
  | 'et'
  | 'fi'
  | 'fr'
  | 'hr'
  | 'hu'
  | 'it'
  | 'lt'
  | 'lv'
  | 'nl'
  | 'pl'
  | 'pt'
  | 'ro'
  | 'sk'
  | 'sl'

export type EuBuyerCity = {
  slug: string
  name: string
  region: string
}

export type EuBuyerMarket = {
  code: string
  country: string
  countryLocal: string
  homeTitle?: string
  flag: string
  language: EuBuyerLanguage
  cities: EuBuyerCity[]
  demand: [string, string, string]
}

export type EuBuyerCopy = {
  dealerAccess: string
  countryTitle: (country: string) => string
  cityTitle: (city: string) => string
  intro: string
  apply: string
  login: string
  howItWorks: string
  liveMarket: string
  dealerDemand: string
  whyTitle: string
  whyText: string
  processTitle: string
  vehicleTitle: string
  vehicleText: string
  locationsTitle: string
  allMarkets: string
  verified: string
  dealerOnly: string
  inspected: string
  stepTitles: [string, string, string, string]
  standards: [string, string, string, string]
  faqTitle: string
  faq: Array<[string, string]>
  footer: string
}

const en: EuBuyerCopy = {
  dealerAccess: 'Autorell dealer access',
  countryTitle: (country) => `European vehicle sourcing for dealers in ${country}`,
  cityTitle: (city) => `A new vehicle sourcing channel for dealers in ${city}`,
  intro:
    'Bid on selected Swedish vehicles through one professional platform. Autorell coordinates the contract, cleared funds, on-site inspection, collection, documents and export.',
  apply: 'Apply for dealer access',
  login: 'Dealer login',
  howItWorks: 'How it works',
  liveMarket: 'Active marketplace',
  dealerDemand: 'Dealer demand',
  whyTitle: 'You place the bid. Autorell handles the transaction.',
  whyText:
    'Approved dealers receive structured vehicle data and a controlled cross-border process instead of fragmented listings and unknown counterparties.',
  processTitle: 'From access to delivery in four clear stages.',
  vehicleTitle: 'Modern vehicles selected for professional resale.',
  vehicleText:
    'Our focus is not limited to sports or luxury cars. We prioritise newer, relevant vehicles with marketable mileage, transparent condition and strong European demand.',
  locationsTitle: 'Important dealer markets',
  allMarkets: 'All European markets',
  verified: 'Verified businesses',
  dealerOnly: 'Dealer-only bidding',
  inspected: 'Inspection in Sweden',
  stepTitles: ['Get approved', 'Review and bid', 'Fund Autorell', 'Inspection and export'],
  standards: ['Model year 2018+', 'Below 100,000 km', 'Good declared condition', 'Modern and electrified'],
  faqTitle: 'Questions from professional dealers',
  faq: [
    ['Where are the vehicles located?', 'Current vehicle supply is sourced and qualified in Sweden. These pages recruit professional buyers; Autorell does not purchase vehicles locally in your country.'],
    ['Who can bid?', 'Only approved automotive businesses with verified company, VAT and contact information receive dealer access.'],
    ['What does Autorell handle?', 'Autorell coordinates contracts, receipt of buyer funds, inspection in Sweden, collection, export documents and agreed logistics.'],
    ['What happens if the declaration is incorrect?', 'The transaction is paused. The parties may agree a documented price adjustment, or Autorell may cancel under the contract.'],
  ],
  footer: 'Selected Swedish vehicles for professional European dealers.',
}

const copies: Record<EuBuyerLanguage, EuBuyerCopy> = {
  en,
  de: {
    ...en,
    dealerAccess: 'Autorell Händlerzugang',
    countryTitle: (country) => `Europäischer Fahrzeugeinkauf für Händler in ${country}`,
    cityTitle: (city) => `Ein neuer Einkaufskanal für Autohändler in ${city}`,
    intro: 'Bieten Sie auf ausgewählte schwedische Fahrzeuge über eine professionelle Plattform. Autorell koordiniert Vertrag, Zahlung, Vor-Ort-Prüfung, Abholung, Dokumente und Export.',
    apply: 'Händlerzugang beantragen',
    login: 'Händler-Login',
    howItWorks: 'So funktioniert es',
    liveMarket: 'Aktiver Marktplatz',
    dealerDemand: 'Händlernachfrage',
    whyTitle: 'Sie bieten. Autorell führt die Transaktion aus.',
    whyText: 'Geprüfte Händler erhalten strukturierte Fahrzeugdaten und einen kontrollierten grenzüberschreitenden Prozess.',
    processTitle: 'Vom Zugang bis zur Lieferung in vier klaren Schritten.',
    vehicleTitle: 'Moderne Fahrzeuge für den professionellen Wiederverkauf.',
    vehicleText: 'Wir priorisieren jüngere Fahrzeuge mit marktgerechter Laufleistung, transparenter Deklaration und europäischer Nachfrage.',
    locationsTitle: 'Wichtige Händlermärkte',
    allMarkets: 'Alle europäischen Märkte',
    verified: 'Geprüfte Unternehmen',
    dealerOnly: 'Nur für Händler',
    inspected: 'Prüfung in Schweden',
    stepTitles: ['Freigabe erhalten', 'Prüfen und bieten', 'Zahlung an Autorell', 'Prüfung und Export'],
    standards: ['Baujahr 2018+', 'Unter 100.000 km', 'Guter deklarierter Zustand', 'Modern und elektrifiziert'],
    faqTitle: 'Fragen professioneller Händler',
    faq: [
      ['Wo befinden sich die Fahrzeuge?', 'Das aktuelle Angebot wird in Schweden beschafft und qualifiziert. Autorell kauft in Ihrem Land keine Fahrzeuge an.'],
      ['Wer darf bieten?', 'Nur geprüfte Fahrzeugunternehmen mit bestätigten Unternehmens-, Umsatzsteuer- und Kontaktdaten erhalten Zugang.'],
      ['Was übernimmt Autorell?', 'Vertrag, Zahlungseingang, Prüfung in Schweden, Abholung, Exportdokumente und vereinbarte Logistik.'],
      ['Was geschieht bei einer Abweichung?', 'Die Transaktion wird pausiert. Die Parteien können eine dokumentierte Preisanpassung vereinbaren oder Autorell kann abbrechen.'],
    ],
    footer: 'Ausgewählte schwedische Fahrzeuge für professionelle europäische Händler.',
  },
  pl: {
    ...en,
    dealerAccess: 'Dostęp dealerski Autorell',
    countryTitle: (country) => `Europejskie samochody dla dealerów w ${country}`,
    cityTitle: (city) => `Nowe źródło samochodów dla dealerów w ${city}`,
    intro: 'Licytuj wyselekcjonowane samochody ze Szwecji na profesjonalnej platformie. Autorell koordynuje umowę, płatność, kontrolę, odbiór, dokumenty i eksport.',
    apply: 'Złóż wniosek o dostęp',
    login: 'Logowanie dealera',
    howItWorks: 'Jak to działa',
    liveMarket: 'Aktywny rynek',
    dealerDemand: 'Popyt dealerów',
    whyTitle: 'Ty składasz ofertę. Autorell obsługuje transakcję.',
    whyText: 'Zweryfikowani dealerzy otrzymują uporządkowane dane pojazdu i kontrolowany proces transgraniczny.',
    processTitle: 'Od dostępu do dostawy w czterech etapach.',
    vehicleTitle: 'Nowoczesne samochody wybrane do profesjonalnej odsprzedaży.',
    vehicleText: 'Koncentrujemy się na nowszych pojazdach z rozsądnym przebiegiem, przejrzystym stanem i popytem w Europie.',
    locationsTitle: 'Ważne rynki dealerskie',
    allMarkets: 'Wszystkie rynki europejskie',
    verified: 'Zweryfikowane firmy',
    dealerOnly: 'Licytacje B2B',
    inspected: 'Kontrola w Szwecji',
    stepTitles: ['Uzyskaj dostęp', 'Sprawdź i licytuj', 'Wpłać środki do Autorell', 'Kontrola i eksport'],
    standards: ['Rok 2018+', 'Poniżej 100 000 km', 'Dobry zadeklarowany stan', 'Nowoczesne i zelektryfikowane'],
    faqTitle: 'Pytania dealerów',
    faq: [
      ['Gdzie znajdują się samochody?', 'Obecna podaż jest pozyskiwana i kwalifikowana w Szwecji. Autorell nie skupuje samochodów lokalnie w Polsce.'],
      ['Kto może licytować?', 'Dostęp otrzymują wyłącznie zweryfikowane firmy motoryzacyjne z ważnym numerem VAT.'],
      ['Co obsługuje Autorell?', 'Umowę, płatność, kontrolę w Szwecji, odbiór, dokumenty eksportowe i uzgodnioną logistykę.'],
      ['Co w przypadku niezgodności?', 'Transakcja zostaje wstrzymana do uzgodnienia ceny lub anulowania zgodnie z umową.'],
    ],
    footer: 'Wyselekcjonowane szwedzkie samochody dla europejskich dealerów.',
  },
  nl: {
    ...en,
    dealerAccess: 'Autorell dealertoegang',
    countryTitle: (country) => `Europese voertuiginkoop voor dealers in ${country}`,
    cityTitle: (city) => `Een nieuw inkoopkanaal voor autodealers in ${city}`,
    intro: 'Bied op geselecteerde Zweedse voertuigen via één professioneel platform. Autorell regelt contract, betaling, inspectie, ophaling, documenten en export.',
    apply: 'Dealertoegang aanvragen',
    login: 'Dealerlogin',
    howItWorks: 'Zo werkt het',
    liveMarket: 'Actieve marktplaats',
    dealerDemand: 'Dealervraag',
    whyTitle: 'U biedt. Autorell regelt de transactie.',
    whyText: 'Goedgekeurde dealers krijgen gestructureerde voertuigdata en een gecontroleerd grensoverschrijdend proces.',
    processTitle: 'Van toegang tot levering in vier stappen.',
    vehicleTitle: 'Moderne voertuigen geselecteerd voor professionele wederverkoop.',
    vehicleText: 'Wij richten ons op jongere voertuigen met marktconforme kilometerstand, transparante staat en Europese vraag.',
    locationsTitle: 'Belangrijke dealermarkten',
    allMarkets: 'Alle Europese markten',
    verified: 'Geverifieerde bedrijven',
    dealerOnly: 'Alleen voor dealers',
    inspected: 'Inspectie in Zweden',
    stepTitles: ['Toegang krijgen', 'Beoordelen en bieden', 'Betalen aan Autorell', 'Inspectie en export'],
    standards: ['Bouwjaar 2018+', 'Minder dan 100.000 km', 'Goede aangegeven staat', 'Modern en geëlektrificeerd'],
    faqTitle: 'Vragen van dealers',
    faq: [
      ['Waar staan de voertuigen?', 'De huidige voertuigen worden in Zweden verworven en gekwalificeerd. Autorell koopt geen voertuigen lokaal in uw land.'],
      ['Wie kan bieden?', 'Alleen geverifieerde automotive bedrijven met geldige bedrijfs- en btw-gegevens.'],
      ['Wat regelt Autorell?', 'Contract, betaling, inspectie in Zweden, ophaling, exportdocumenten en afgesproken logistiek.'],
      ['Wat gebeurt er bij een afwijking?', 'De transactie wordt gepauzeerd voor een schriftelijke prijsaanpassing of annulering.'],
    ],
    footer: 'Geselecteerde Zweedse voertuigen voor professionele Europese dealers.',
  },
  fr: {
    ...en,
    dealerAccess: 'Accès professionnel Autorell',
    countryTitle: (country) => `Approvisionnement automobile européen pour les négociants en ${country}`,
    cityTitle: (city) => `Une nouvelle source de véhicules pour les professionnels à ${city}`,
    intro: 'Enchérissez sur des véhicules suédois sélectionnés via une plateforme professionnelle. Autorell coordonne contrat, paiement, inspection, enlèvement, documents et export.',
    apply: 'Demander un accès professionnel',
    login: 'Connexion professionnel',
    howItWorks: 'Comment ça marche',
    liveMarket: 'Marché actif',
    dealerDemand: 'Demande professionnelle',
    whyTitle: 'Vous enchérissez. Autorell gère la transaction.',
    whyText: 'Les professionnels vérifiés disposent de données structurées et d’un processus transfrontalier contrôlé.',
    processTitle: 'De l’accès à la livraison en quatre étapes.',
    vehicleTitle: 'Des véhicules récents sélectionnés pour la revente professionnelle.',
    vehicleText: 'Nous privilégions les véhicules récents, au kilométrage adapté, à l’état déclaré clairement et recherchés en Europe.',
    locationsTitle: 'Principaux marchés professionnels',
    allMarkets: 'Tous les marchés européens',
    verified: 'Entreprises vérifiées',
    dealerOnly: 'Enchères professionnelles',
    inspected: 'Inspection en Suède',
    stepTitles: ['Obtenir l’accès', 'Examiner et enchérir', 'Payer Autorell', 'Inspection et export'],
    standards: ['Année 2018+', 'Moins de 100 000 km', 'Bon état déclaré', 'Récent et électrifié'],
    faqTitle: 'Questions des professionnels',
    faq: [
      ['Où se trouvent les véhicules ?', 'L’offre actuelle est sourcée et qualifiée en Suède. Autorell n’achète pas de véhicules localement dans votre pays.'],
      ['Qui peut enchérir ?', 'Uniquement les entreprises automobiles vérifiées avec des informations de société et de TVA valides.'],
      ['Que gère Autorell ?', 'Le contrat, le paiement, l’inspection en Suède, l’enlèvement, les documents d’export et la logistique convenue.'],
      ['Que se passe-t-il en cas d’écart ?', 'La transaction est suspendue pour convenir par écrit d’un nouveau prix ou être annulée.'],
    ],
    footer: 'Véhicules suédois sélectionnés pour les professionnels européens.',
  },
  es: {
    ...en,
    dealerAccess: 'Acceso profesional Autorell',
    countryTitle: (country) => `Compra europea de vehículos para profesionales en ${country}`,
    cityTitle: (city) => `Un nuevo canal de vehículos para profesionales en ${city}`,
    intro: 'Puja por vehículos suecos seleccionados en una plataforma profesional. Autorell coordina contrato, pago, inspección, recogida, documentos y exportación.',
    apply: 'Solicitar acceso profesional',
    login: 'Acceso de profesionales',
    howItWorks: 'Cómo funciona',
    liveMarket: 'Mercado activo',
    dealerDemand: 'Demanda profesional',
    whyTitle: 'Tú pujas. Autorell gestiona la transacción.',
    whyText: 'Los profesionales verificados reciben datos estructurados y un proceso transfronterizo controlado.',
    processTitle: 'Del acceso a la entrega en cuatro pasos.',
    vehicleTitle: 'Vehículos modernos seleccionados para reventa profesional.',
    vehicleText: 'Priorizamos vehículos recientes con kilometraje comercial, estado transparente y demanda europea.',
    locationsTitle: 'Mercados profesionales importantes',
    allMarkets: 'Todos los mercados europeos',
    verified: 'Empresas verificadas',
    dealerOnly: 'Pujas solo B2B',
    inspected: 'Inspección en Suecia',
    stepTitles: ['Obtener acceso', 'Revisar y pujar', 'Pagar a Autorell', 'Inspección y exportación'],
    standards: ['Año 2018+', 'Menos de 100.000 km', 'Buen estado declarado', 'Moderno y electrificado'],
    faqTitle: 'Preguntas de profesionales',
    faq: [
      ['¿Dónde están los vehículos?', 'La oferta actual se compra y verifica en Suecia. Autorell no compra vehículos localmente en su país.'],
      ['¿Quién puede pujar?', 'Solo empresas de automoción verificadas con datos societarios y fiscales válidos.'],
      ['¿Qué gestiona Autorell?', 'Contrato, pago, inspección en Suecia, recogida, documentación de exportación y logística acordada.'],
      ['¿Qué ocurre si hay diferencias?', 'La transacción se pausa para acordar un precio por escrito o cancelarla según el contrato.'],
    ],
    footer: 'Vehículos suecos seleccionados para profesionales europeos.',
  },
  it: {
    ...en,
    dealerAccess: 'Accesso rivenditori Autorell',
    countryTitle: (country) => `Approvvigionamento europeo per rivenditori in ${country}`,
    cityTitle: (city) => `Un nuovo canale di veicoli per rivenditori a ${city}`,
    intro: 'Fai offerte su veicoli svedesi selezionati tramite una piattaforma professionale. Autorell coordina contratto, pagamento, ispezione, ritiro, documenti ed esportazione.',
    apply: 'Richiedi accesso rivenditore',
    login: 'Login rivenditore',
    howItWorks: 'Come funziona',
    liveMarket: 'Marketplace attivo',
    dealerDemand: 'Domanda dei rivenditori',
    whyTitle: 'Tu fai l’offerta. Autorell gestisce la transazione.',
    whyText: 'I rivenditori verificati ricevono dati strutturati e un processo transfrontaliero controllato.',
    processTitle: 'Dall’accesso alla consegna in quattro fasi.',
    vehicleTitle: 'Veicoli moderni selezionati per la rivendita professionale.',
    vehicleText: 'Privilegiamo veicoli recenti con chilometraggio commerciale, condizioni trasparenti e domanda europea.',
    locationsTitle: 'Principali mercati dei rivenditori',
    allMarkets: 'Tutti i mercati europei',
    verified: 'Aziende verificate',
    dealerOnly: 'Aste solo B2B',
    inspected: 'Ispezione in Svezia',
    stepTitles: ['Ottieni accesso', 'Valuta e offri', 'Paga Autorell', 'Ispezione ed export'],
    standards: ['Anno 2018+', 'Meno di 100.000 km', 'Buone condizioni dichiarate', 'Moderno ed elettrificato'],
    faqTitle: 'Domande dei rivenditori',
    faq: [
      ['Dove si trovano i veicoli?', 'L’offerta attuale viene acquistata e qualificata in Svezia. Autorell non acquista veicoli localmente nel tuo paese.'],
      ['Chi può fare offerte?', 'Solo aziende automobilistiche verificate con dati societari e IVA validi.'],
      ['Cosa gestisce Autorell?', 'Contratto, pagamento, ispezione in Svezia, ritiro, documenti di esportazione e logistica concordata.'],
      ['Cosa accade in caso di difformità?', 'La transazione viene sospesa per concordare un nuovo prezzo o annullarla secondo il contratto.'],
    ],
    footer: 'Veicoli svedesi selezionati per rivenditori europei.',
  },
  pt: {
    ...en,
    dealerAccess: 'Acesso profissional Autorell',
    countryTitle: (country) => `Compra europeia de veículos para profissionais em ${country}`,
    cityTitle: (city) => `Um novo canal de veículos para profissionais em ${city}`,
    intro: 'Licite veículos suecos selecionados numa plataforma profissional. A Autorell coordena contrato, pagamento, inspeção, recolha, documentos e exportação.',
    apply: 'Pedir acesso profissional',
    login: 'Login profissional',
    howItWorks: 'Como funciona',
    liveMarket: 'Mercado ativo',
    dealerDemand: 'Procura profissional',
    whyTitle: 'Você licita. A Autorell gere a transação.',
    whyText: 'Profissionais verificados recebem dados estruturados e um processo transfronteiriço controlado.',
    processTitle: 'Do acesso à entrega em quatro etapas.',
    vehicleTitle: 'Veículos modernos selecionados para revenda profissional.',
    vehicleText: 'Priorizamos veículos recentes, quilometragem adequada, estado transparente e procura europeia.',
    locationsTitle: 'Mercados profissionais importantes',
    allMarkets: 'Todos os mercados europeus',
    verified: 'Empresas verificadas',
    dealerOnly: 'Licitação apenas B2B',
    inspected: 'Inspeção na Suécia',
    stepTitles: ['Obter acesso', 'Analisar e licitar', 'Pagar à Autorell', 'Inspeção e exportação'],
    standards: ['Ano 2018+', 'Menos de 100.000 km', 'Bom estado declarado', 'Moderno e eletrificado'],
    faqTitle: 'Perguntas de profissionais',
    faq: [
      ['Onde estão os veículos?', 'A oferta atual é selecionada e qualificada na Suécia. A Autorell não compra veículos localmente em Portugal.'],
      ['Quem pode licitar?', 'Apenas empresas automóveis aprovadas com dados empresariais, fiscais e de contacto verificados.'],
      ['O que trata a Autorell?', 'Coordenamos contrato, recebimento dos fundos, inspeção na Suécia, recolha, documentos de exportação e logística acordada.'],
      ['E se a declaração estiver incorreta?', 'A transação é suspensa. Pode ser acordado um ajuste documentado ou o negócio pode ser cancelado nos termos do contrato.'],
    ],
    footer: 'Veículos suecos selecionados para profissionais europeus.',
  },
  da: {
    ...en,
    dealerAccess: 'Autorell-forhandleradgang',
    countryTitle: (country) => `Europæisk bilindkøb for forhandlere i ${country}`,
    cityTitle: (city) => `En ny indkøbskanal for bilforhandlere i ${city}`,
    intro: 'Byd på udvalgte svenske biler via én professionel platform. Autorell koordinerer aftale, betaling, inspektion, afhentning, dokumenter og eksport.',
    apply: 'Ansøg om forhandleradgang',
    login: 'Forhandlerlogin',
    howItWorks: 'Sådan fungerer det',
    liveMarket: 'Aktiv markedsplads',
    dealerDemand: 'Forhandlerefterspørgsel',
    whyTitle: 'Du byder. Autorell håndterer transaktionen.',
    whyText: 'Godkendte forhandlere får strukturerede bildata og en kontrolleret grænseoverskridende proces.',
    processTitle: 'Fra adgang til levering i fire trin.',
    vehicleTitle: 'Moderne biler udvalgt til professionelt videresalg.',
    vehicleText: 'Vi prioriterer nyere biler med attraktiv kilometerstand, transparent stand og europæisk efterspørgsel.',
    locationsTitle: 'Vigtige forhandlermarkeder',
    allMarkets: 'Alle europæiske markeder',
    verified: 'Verificerede virksomheder',
    dealerOnly: 'Kun for forhandlere',
    inspected: 'Inspektion i Sverige',
    stepTitles: ['Bliv godkendt', 'Vurder og byd', 'Betal Autorell', 'Inspektion og eksport'],
    standards: ['Årgang 2018+', 'Under 100.000 km', 'God deklareret stand', 'Moderne og elektrificeret'],
    faqTitle: 'Spørgsmål fra forhandlere',
    faq: [
      ['Hvor befinder bilerne sig?', 'Det aktuelle udbud udvælges og kvalificeres i Sverige. Autorell køber ikke biler lokalt i Danmark.'],
      ['Hvem kan byde?', 'Kun godkendte bilvirksomheder med verificerede virksomheds-, moms- og kontaktoplysninger.'],
      ['Hvad håndterer Autorell?', 'Vi koordinerer kontrakt, modtagelse af betaling, inspektion i Sverige, afhentning, eksportdokumenter og aftalt logistik.'],
      ['Hvad sker der ved forkerte oplysninger?', 'Handlen sættes på pause. Parterne kan aftale en dokumenteret prisjustering, eller handlen kan annulleres efter kontrakten.'],
    ],
    footer: 'Udvalgte svenske biler til professionelle europæiske forhandlere.',
  },
  fi: {
    ...en,
    dealerAccess: 'Autorell-jälleenmyyjäpääsy',
    countryTitle: (country) => `Eurooppalainen ajoneuvohankinta jälleenmyyjille: ${country}`,
    cityTitle: (city) => `Uusi ajoneuvojen hankintakanava jälleenmyyjille: ${city}`,
    intro: 'Tarjoa valikoiduista ruotsalaisista autoista ammattimaisella alustalla. Autorell hoitaa sopimuksen, maksun, tarkastuksen, noudon, asiakirjat ja viennin.',
    apply: 'Hae jälleenmyyjäksi',
    login: 'Jälleenmyyjän kirjautuminen',
    howItWorks: 'Näin se toimii',
    liveMarket: 'Aktiivinen markkinapaikka',
    dealerDemand: 'Jälleenmyyjien kysyntä',
    whyTitle: 'Sinä tarjoat. Autorell hoitaa kaupan.',
    whyText: 'Hyväksytyt jälleenmyyjät saavat jäsennellyt ajoneuvotiedot ja hallitun rajat ylittävän prosessin.',
    processTitle: 'Pääsystä toimitukseen neljässä vaiheessa.',
    vehicleTitle: 'Nykyaikaisia ajoneuvoja ammattimaiseen jälleenmyyntiin.',
    vehicleText: 'Painotamme uudempia ajoneuvoja, kohtuullista ajomäärää, läpinäkyvää kuntoa ja eurooppalaista kysyntää.',
    locationsTitle: 'Tärkeät jälleenmyyjämarkkinat',
    allMarkets: 'Kaikki Euroopan markkinat',
    verified: 'Vahvistetut yritykset',
    dealerOnly: 'Vain jälleenmyyjille',
    inspected: 'Tarkastus Ruotsissa',
    stepTitles: ['Hanki hyväksyntä', 'Arvioi ja tarjoa', 'Maksa Autorellille', 'Tarkastus ja vienti'],
    standards: ['Vuosimalli 2018+', 'Alle 100 000 km', 'Hyvä ilmoitettu kunto', 'Moderni ja sähköistetty'],
    faqTitle: 'Jälleenmyyjien kysymykset',
    faq: [
      ['Missä ajoneuvot sijaitsevat?', 'Nykyinen tarjonta valitaan ja tarkastetaan Ruotsissa. Autorell ei osta ajoneuvoja paikallisesti Suomessa.'],
      ['Kuka voi tehdä tarjouksia?', 'Vain hyväksytyt autoalan yritykset, joiden yritys-, ALV- ja yhteystiedot on vahvistettu.'],
      ['Mitä Autorell hoitaa?', 'Koordinoimme sopimuksen, maksun vastaanoton, tarkastuksen Ruotsissa, noudon, vientiasiakirjat ja sovitun logistiikan.'],
      ['Mitä jos ilmoitus ei vastaa autoa?', 'Kauppa keskeytetään. Hinnasta voidaan sopia kirjallisesti uudelleen tai kauppa voidaan perua sopimusehtojen mukaisesti.'],
    ],
    footer: 'Valikoidut ruotsalaiset autot eurooppalaisille jälleenmyyjille.',
  },
  cs: {
    ...en,
    dealerAccess: 'Přístup pro prodejce Autorell',
    countryTitle: (country) => `Evropský nákup vozidel pro prodejce v ${country}`,
    cityTitle: (city) => `Nový zdroj vozidel pro prodejce v ${city}`,
    intro: 'Nabízejte na vybraná švédská vozidla prostřednictvím profesionální platformy. Autorell koordinuje smlouvu, platbu, kontrolu, vyzvednutí, dokumenty a export.',
    apply: 'Požádat o přístup',
    login: 'Přihlášení prodejce',
    howItWorks: 'Jak to funguje',
    liveMarket: 'Aktivní tržiště',
    dealerDemand: 'Poptávka prodejců',
    whyTitle: 'Vy nabídnete cenu. Autorell zajistí transakci.',
    whyText: 'Ověření prodejci získají strukturovaná data a kontrolovaný přeshraniční proces.',
    processTitle: 'Od přístupu k dodání ve čtyřech krocích.',
    vehicleTitle: 'Moderní vozidla vybraná pro profesionální prodej.',
    vehicleText: 'Upřednostňujeme novější vozidla s prodejným nájezdem, transparentním stavem a evropskou poptávkou.',
    locationsTitle: 'Důležité dealerské trhy',
    allMarkets: 'Všechny evropské trhy',
    verified: 'Ověřené firmy',
    dealerOnly: 'Pouze B2B',
    inspected: 'Kontrola ve Švédsku',
    stepTitles: ['Získejte přístup', 'Prověřte a nabídněte', 'Zaplaťte Autorellu', 'Kontrola a export'],
    standards: ['Rok 2018+', 'Pod 100 000 km', 'Dobrý deklarovaný stav', 'Moderní a elektrifikované'],
    faqTitle: 'Otázky prodejců',
    faq: [
      ['Kde se vozidla nacházejí?', 'Aktuální nabídka je vybírána a prověřována ve Švédsku. Autorell nevykupuje vozidla lokálně v Česku.'],
      ['Kdo může přihazovat?', 'Pouze schválené automobilové firmy s ověřenými firemními, daňovými a kontaktními údaji.'],
      ['Co zajišťuje Autorell?', 'Koordinujeme smlouvu, přijetí platby, kontrolu ve Švédsku, vyzvednutí, exportní dokumenty a dohodnutou logistiku.'],
      ['Co když deklarace nesouhlasí?', 'Transakce se pozastaví. Lze písemně upravit cenu nebo obchod zrušit podle smluvních podmínek.'],
    ],
    footer: 'Vybraná švédská vozidla pro evropské prodejce.',
  },
  sk: {
    ...en,
    dealerAccess: 'Prístup pre predajcov Autorell',
    countryTitle: (country) => `Európsky nákup vozidiel pre predajcov v ${country}`,
    cityTitle: (city) => `Nový zdroj vozidiel pre predajcov v ${city}`,
    intro: 'Ponúkajte na vybrané švédske vozidlá cez profesionálnu platformu. Autorell koordinuje zmluvu, platbu, kontrolu, vyzdvihnutie, dokumenty a export.',
    apply: 'Požiadať o prístup',
    login: 'Prihlásenie predajcu',
    howItWorks: 'Ako to funguje',
    liveMarket: 'Aktívne trhovisko',
    dealerDemand: 'Dopyt predajcov',
    whyTitle: 'Vy ponúkate. Autorell riadi transakciu.',
    whyText: 'Overení predajcovia získajú štruktúrované údaje a kontrolovaný cezhraničný proces.',
    processTitle: 'Od prístupu po dodanie v štyroch krokoch.',
    vehicleTitle: 'Moderné vozidlá vybrané na profesionálny predaj.',
    vehicleText: 'Uprednostňujeme novšie vozidlá s predajným nájazdom, transparentným stavom a európskym dopytom.',
    locationsTitle: 'Dôležité dealerské trhy',
    allMarkets: 'Všetky európske trhy',
    verified: 'Overené firmy',
    dealerOnly: 'Len B2B',
    inspected: 'Kontrola vo Švédsku',
    stepTitles: ['Získajte prístup', 'Skontrolujte a ponúknite', 'Zaplaťte Autorellu', 'Kontrola a export'],
    standards: ['Rok 2018+', 'Pod 100 000 km', 'Dobrý deklarovaný stav', 'Moderné a elektrifikované'],
    faqTitle: 'Otázky predajcov',
    faq: [
      ['Kde sa vozidlá nachádzajú?', 'Aktuálna ponuka je vyberaná a preverovaná vo Švédsku. Autorell nevykupuje vozidlá lokálne na Slovensku.'],
      ['Kto môže ponúkať?', 'Iba schválené automobilové firmy s overenými firemnými, daňovými a kontaktnými údajmi.'],
      ['Čo zabezpečuje Autorell?', 'Koordinujeme zmluvu, prijatie platby, kontrolu vo Švédsku, vyzdvihnutie, exportné dokumenty a dohodnutú logistiku.'],
      ['Čo ak deklarácia nesúhlasí?', 'Transakcia sa pozastaví. Cenu možno písomne upraviť alebo obchod zrušiť podľa zmluvných podmienok.'],
    ],
    footer: 'Vybrané švédske vozidlá pre európskych predajcov.',
  },
  hu: {
    ...en,
    dealerAccess: 'Autorell kereskedői hozzáférés',
    countryTitle: (country) => `Európai járműbeszerzés kereskedőknek itt: ${country}`,
    cityTitle: (city) => `Új járműbeszerzési csatorna kereskedőknek itt: ${city}`,
    intro: 'Licitáljon válogatott svéd járművekre professzionális platformon. Az Autorell koordinálja a szerződést, fizetést, ellenőrzést, átvételt, dokumentumokat és exportot.',
    apply: 'Kereskedői hozzáférés igénylése',
    login: 'Kereskedői belépés',
    howItWorks: 'Hogyan működik',
    liveMarket: 'Aktív piactér',
    dealerDemand: 'Kereskedői kereslet',
    whyTitle: 'Ön licitál. Az Autorell kezeli a tranzakciót.',
    whyText: 'Az ellenőrzött kereskedők strukturált adatokat és ellenőrzött határon átnyúló folyamatot kapnak.',
    processTitle: 'A hozzáféréstől a szállításig négy lépésben.',
    vehicleTitle: 'Modern járművek professzionális továbbértékesítésre.',
    vehicleText: 'Fiatalabb, piacképes futásteljesítményű és átlátható állapotú járműveket választunk.',
    locationsTitle: 'Fontos kereskedői piacok',
    allMarkets: 'Minden európai piac',
    verified: 'Ellenőrzött cégek',
    dealerOnly: 'Csak B2B',
    inspected: 'Ellenőrzés Svédországban',
    stepTitles: ['Hozzáférés', 'Ellenőrzés és licit', 'Fizetés az Autorellnek', 'Ellenőrzés és export'],
    standards: ['2018-as vagy újabb', '100 000 km alatt', 'Jó bejelentett állapot', 'Modern és elektromosított'],
    faqTitle: 'Kereskedői kérdések',
    faq: [
      ['Hol találhatók a járművek?', 'A jelenlegi kínálatot Svédországban választjuk ki és ellenőrizzük. Az Autorell nem vásárol helyben járműveket Magyarországon.'],
      ['Ki licitálhat?', 'Csak jóváhagyott autóipari vállalkozások, ellenőrzött cég-, adó- és kapcsolattartási adatokkal.'],
      ['Mit intéz az Autorell?', 'Koordináljuk a szerződést, a fizetés fogadását, a svédországi ellenőrzést, az átvételt, az exportdokumentumokat és a logisztikát.'],
      ['Mi történik eltérés esetén?', 'A tranzakciót felfüggesztjük. Írásos árkorrekció állapítható meg, vagy az ügylet a szerződés szerint megszüntethető.'],
    ],
    footer: 'Válogatott svéd járművek európai kereskedőknek.',
  },
  ro: {
    ...en,
    dealerAccess: 'Acces dealer Autorell',
    countryTitle: (country) => `Achiziții auto europene pentru dealeri în ${country}`,
    cityTitle: (city) => `Un nou canal de vehicule pentru dealerii din ${city}`,
    intro: 'Licitați vehicule suedeze selectate printr-o platformă profesională. Autorell coordonează contractul, plata, inspecția, ridicarea, documentele și exportul.',
    apply: 'Solicită acces dealer',
    login: 'Autentificare dealer',
    howItWorks: 'Cum funcționează',
    liveMarket: 'Piață activă',
    dealerDemand: 'Cererea dealerilor',
    whyTitle: 'Dumneavoastră licitați. Autorell gestionează tranzacția.',
    whyText: 'Dealerii verificați primesc date structurate și un proces transfrontalier controlat.',
    processTitle: 'De la acces la livrare în patru pași.',
    vehicleTitle: 'Vehicule moderne selectate pentru revânzare profesională.',
    vehicleText: 'Prioritizăm vehicule mai noi, cu kilometraj vandabil, stare transparentă și cerere europeană.',
    locationsTitle: 'Piețe importante pentru dealeri',
    allMarkets: 'Toate piețele europene',
    verified: 'Companii verificate',
    dealerOnly: 'Licitații doar B2B',
    inspected: 'Inspecție în Suedia',
    stepTitles: ['Obține acces', 'Verifică și licitează', 'Plătește Autorell', 'Inspecție și export'],
    standards: ['An 2018+', 'Sub 100.000 km', 'Stare declarată bună', 'Modern și electrificat'],
    faqTitle: 'Întrebări de la dealeri',
    faq: [
      ['Unde se află vehiculele?', 'Oferta actuală este selectată și verificată în Suedia. Autorell nu cumpără vehicule local în România.'],
      ['Cine poate licita?', 'Doar companii auto aprobate, cu date de firmă, TVA și contact verificate.'],
      ['Ce gestionează Autorell?', 'Coordonăm contractul, încasarea plății, inspecția în Suedia, preluarea, documentele de export și logistica agreată.'],
      ['Ce se întâmplă dacă declarația este greșită?', 'Tranzacția este suspendată. Se poate conveni o ajustare documentată a prețului sau tranzacția poate fi anulată conform contractului.'],
    ],
    footer: 'Vehicule suedeze selectate pentru dealerii europeni.',
  },
  bg: {
    ...en,
    dealerAccess: 'Дилърски достъп Autorell',
    countryTitle: (country) => `Европейски автомобили за дилъри в ${country}`,
    cityTitle: (city) => `Нов канал за автомобили за дилъри в ${city}`,
    intro: 'Наддавайте за подбрани шведски автомобили чрез професионална платформа. Autorell координира договора, плащането, проверката, вземането, документите и износа.',
    apply: 'Кандидатствайте за достъп',
    login: 'Вход за дилъри',
    howItWorks: 'Как работи',
    liveMarket: 'Активен пазар',
    dealerDemand: 'Търсене от дилъри',
    whyTitle: 'Вие наддавате. Autorell управлява сделката.',
    whyText: 'Проверените дилъри получават структурирани данни и контролиран трансграничен процес.',
    processTitle: 'От достъп до доставка в четири стъпки.',
    vehicleTitle: 'Модерни автомобили за професионална препродажба.',
    vehicleText: 'Фокусираме се върху по-нови автомобили с подходящ пробег, прозрачно състояние и европейско търсене.',
    locationsTitle: 'Важни дилърски пазари',
    allMarkets: 'Всички европейски пазари',
    verified: 'Проверени компании',
    dealerOnly: 'Само B2B',
    inspected: 'Проверка в Швеция',
    stepTitles: ['Получете достъп', 'Прегледайте и наддайте', 'Платете на Autorell', 'Проверка и износ'],
    standards: ['Година 2018+', 'Под 100 000 км', 'Добро декларирано състояние', 'Модерни и електрифицирани'],
    faqTitle: 'Въпроси от дилъри',
    faq: [
      ['Къде се намират автомобилите?', 'Настоящите автомобили се подбират и проверяват в Швеция. Autorell не изкупува автомобили на местно ниво в България.'],
      ['Кой може да наддава?', 'Само одобрени автомобилни компании с проверени фирмени, ДДС и контактни данни.'],
      ['Какво управлява Autorell?', 'Координираме договора, плащането, проверката в Швеция, получаването, експортните документи и договорената логистика.'],
      ['Какво става при грешна декларация?', 'Сделката се спира. Може да се договори писмена корекция на цената или сделката да бъде прекратена според договора.'],
    ],
    footer: 'Подбрани шведски автомобили за европейски дилъри.',
  },
  hr: {
    ...en,
    dealerAccess: 'Autorell pristup za trgovce',
    countryTitle: (country) => `Europska nabava vozila za trgovce u ${country}`,
    cityTitle: (city) => `Novi kanal nabave vozila za trgovce u ${city}`,
    intro: 'Licitirajte za odabrana švedska vozila putem profesionalne platforme. Autorell koordinira ugovor, plaćanje, pregled, preuzimanje, dokumente i izvoz.',
    apply: 'Zatražite pristup',
    login: 'Prijava trgovca',
    howItWorks: 'Kako funkcionira',
    liveMarket: 'Aktivno tržište',
    dealerDemand: 'Potražnja trgovaca',
    whyTitle: 'Vi licitirate. Autorell vodi transakciju.',
    whyText: 'Provjereni trgovci dobivaju strukturirane podatke i kontroliran prekogranični proces.',
    processTitle: 'Od pristupa do isporuke u četiri koraka.',
    vehicleTitle: 'Moderna vozila odabrana za profesionalnu preprodaju.',
    vehicleText: 'Prednost dajemo novijim vozilima s tržišnom kilometražom, transparentnim stanjem i europskom potražnjom.',
    locationsTitle: 'Važna tržišta trgovaca',
    allMarkets: 'Sva europska tržišta',
    verified: 'Provjerene tvrtke',
    dealerOnly: 'Samo B2B',
    inspected: 'Pregled u Švedskoj',
    stepTitles: ['Dobijte pristup', 'Pregledajte i licitirajte', 'Platite Autorellu', 'Pregled i izvoz'],
    standards: ['Godište 2018+', 'Ispod 100.000 km', 'Dobro deklarirano stanje', 'Moderno i elektrificirano'],
    faqTitle: 'Pitanja trgovaca',
    faq: [
      ['Gdje se vozila nalaze?', 'Trenutna ponuda odabire se i provjerava u Švedskoj. Autorell ne otkupljuje vozila lokalno u Hrvatskoj.'],
      ['Tko može licitirati?', 'Samo odobrene automobilske tvrtke s provjerenim podacima o tvrtki, PDV-u i kontaktima.'],
      ['Što Autorell preuzima?', 'Koordiniramo ugovor, primitak plaćanja, pregled u Švedskoj, preuzimanje, izvozne dokumente i dogovorenu logistiku.'],
      ['Što ako deklaracija nije točna?', 'Transakcija se zaustavlja. Može se pisano dogovoriti nova cijena ili se posao može otkazati prema ugovoru.'],
    ],
    footer: 'Odabrana švedska vozila za europske trgovce.',
  },
  sl: {
    ...en,
    dealerAccess: 'Dostop za trgovce Autorell',
    countryTitle: (country) => `Evropska nabava vozil za trgovce v ${country}`,
    cityTitle: (city) => `Nov kanal vozil za trgovce v ${city}`,
    intro: 'Licitirajte za izbrana švedska vozila na profesionalni platformi. Autorell usklajuje pogodbo, plačilo, pregled, prevzem, dokumente in izvoz.',
    apply: 'Zaprosite za dostop',
    login: 'Prijava trgovca',
    howItWorks: 'Kako deluje',
    liveMarket: 'Aktivna tržnica',
    dealerDemand: 'Povpraševanje trgovcev',
    whyTitle: 'Vi licitirate. Autorell vodi transakcijo.',
    whyText: 'Preverjeni trgovci dobijo strukturirane podatke in nadzorovan čezmejni postopek.',
    processTitle: 'Od dostopa do dostave v štirih korakih.',
    vehicleTitle: 'Sodobna vozila za profesionalno nadaljnjo prodajo.',
    vehicleText: 'Prednost imajo novejša vozila s tržno kilometrino, preglednim stanjem in evropskim povpraševanjem.',
    locationsTitle: 'Pomembni trgovski trgi',
    allMarkets: 'Vsi evropski trgi',
    verified: 'Preverjena podjetja',
    dealerOnly: 'Samo B2B',
    inspected: 'Pregled na Švedskem',
    stepTitles: ['Pridobite dostop', 'Preglejte in licitirajte', 'Plačajte Autorellu', 'Pregled in izvoz'],
    standards: ['Letnik 2018+', 'Pod 100.000 km', 'Dobro prijavljeno stanje', 'Sodobno in elektrificirano'],
    faqTitle: 'Vprašanja trgovcev',
    faq: [
      ['Kje se vozila nahajajo?', 'Trenutna ponudba je izbrana in preverjena na Švedskem. Autorell vozil ne odkupuje lokalno v Sloveniji.'],
      ['Kdo lahko odda ponudbo?', 'Samo odobrena avtomobilska podjetja s preverjenimi podatki podjetja, DDV in kontaktnimi podatki.'],
      ['Kaj ureja Autorell?', 'Usklajujemo pogodbo, prejem plačila, pregled na Švedskem, prevzem, izvozne dokumente in dogovorjeno logistiko.'],
      ['Kaj če deklaracija ni pravilna?', 'Transakcija se začasno ustavi. Pisno se lahko dogovori nova cena ali pa se posel prekliče po pogodbi.'],
    ],
    footer: 'Izbrana švedska vozila za evropske trgovce.',
  },
  et: {
    ...en,
    dealerAccess: 'Autorelli edasimüüja juurdepääs',
    countryTitle: (country) => `Euroopa sõidukite hankimine edasimüüjatele: ${country}`,
    cityTitle: (city) => `Uus sõidukite hankekanal edasimüüjatele: ${city}`,
    intro: 'Tehke pakkumisi valitud Rootsi sõidukitele professionaalsel platvormil. Autorell korraldab lepingu, makse, kontrolli, äraveo, dokumendid ja ekspordi.',
    apply: 'Taotle juurdepääsu',
    login: 'Edasimüüja sisselogimine',
    howItWorks: 'Kuidas see toimib',
    liveMarket: 'Aktiivne turg',
    dealerDemand: 'Edasimüüjate nõudlus',
    whyTitle: 'Teie pakute. Autorell juhib tehingut.',
    whyText: 'Kontrollitud edasimüüjad saavad struktureeritud andmed ja kontrollitud piiriülese protsessi.',
    processTitle: 'Juurdepääsust tarneni nelja sammuga.',
    vehicleTitle: 'Kaasaegsed sõidukid professionaalseks edasimüügiks.',
    vehicleText: 'Eelistame uuemaid sõidukeid sobiva läbisõidu, läbipaistva seisukorra ja Euroopa nõudlusega.',
    locationsTitle: 'Olulised edasimüüjate turud',
    allMarkets: 'Kõik Euroopa turud',
    verified: 'Kontrollitud ettevõtted',
    dealerOnly: 'Ainult B2B',
    inspected: 'Kontroll Rootsis',
    stepTitles: ['Saa juurdepääs', 'Vaata ja paku', 'Maksa Autorellile', 'Kontroll ja eksport'],
    standards: ['Aasta 2018+', 'Alla 100 000 km', 'Hea deklareeritud seisukord', 'Kaasaegne ja elektrifitseeritud'],
    faqTitle: 'Edasimüüjate küsimused',
    faq: [
      ['Kus sõidukid asuvad?', 'Praegune valik valitakse ja kontrollitakse Rootsis. Autorell ei osta sõidukeid kohapeal Eestis.'],
      ['Kes saab pakkuda?', 'Ainult heakskiidetud autoettevõtted, kelle ettevõtte-, käibemaksu- ja kontaktandmed on kontrollitud.'],
      ['Mida Autorell korraldab?', 'Koordineerime lepingut, makse laekumist, kontrolli Rootsis, äravedu, ekspordidokumente ja kokkulepitud logistikat.'],
      ['Mis juhtub vale deklaratsiooni korral?', 'Tehing peatatakse. Kirjalikult saab kokku leppida hinnamuutuse või tehingu lepingutingimustel tühistada.'],
    ],
    footer: 'Valitud Rootsi sõidukid Euroopa edasimüüjatele.',
  },
  lv: {
    ...en,
    dealerAccess: 'Autorell tirgotāju piekļuve',
    countryTitle: (country) => `Eiropas auto iegāde tirgotājiem: ${country}`,
    cityTitle: (city) => `Jauns auto iegādes kanāls tirgotājiem: ${city}`,
    intro: 'Soliet par atlasītiem Zviedrijas auto profesionālā platformā. Autorell koordinē līgumu, maksājumu, pārbaudi, saņemšanu, dokumentus un eksportu.',
    apply: 'Pieteikties piekļuvei',
    login: 'Tirgotāja pieslēgšanās',
    howItWorks: 'Kā tas darbojas',
    liveMarket: 'Aktīvs tirgus',
    dealerDemand: 'Tirgotāju pieprasījums',
    whyTitle: 'Jūs solāt. Autorell vada darījumu.',
    whyText: 'Pārbaudīti tirgotāji saņem strukturētus datus un kontrolētu pārrobežu procesu.',
    processTitle: 'No piekļuves līdz piegādei četros soļos.',
    vehicleTitle: 'Mūsdienīgi auto profesionālai tālākpārdošanai.',
    vehicleText: 'Prioritāte ir jaunākiem auto ar tirgum piemērotu nobraukumu, caurspīdīgu stāvokli un Eiropas pieprasījumu.',
    locationsTitle: 'Svarīgi tirgotāju tirgi',
    allMarkets: 'Visi Eiropas tirgi',
    verified: 'Pārbaudīti uzņēmumi',
    dealerOnly: 'Tikai B2B',
    inspected: 'Pārbaude Zviedrijā',
    stepTitles: ['Saņemiet piekļuvi', 'Pārbaudiet un soliet', 'Maksājiet Autorell', 'Pārbaude un eksports'],
    standards: ['Gads 2018+', 'Zem 100 000 km', 'Labs deklarētais stāvoklis', 'Moderns un elektrificēts'],
    faqTitle: 'Tirgotāju jautājumi',
    faq: [
      ['Kur atrodas automašīnas?', 'Pašreizējais piedāvājums tiek atlasīts un pārbaudīts Zviedrijā. Autorell neiepērk automašīnas uz vietas Latvijā.'],
      ['Kas var solīt?', 'Tikai apstiprināti auto uzņēmumi ar pārbaudītiem uzņēmuma, PVN un kontaktinformācijas datiem.'],
      ['Ko nodrošina Autorell?', 'Koordinējam līgumu, maksājuma saņemšanu, pārbaudi Zviedrijā, savākšanu, eksporta dokumentus un saskaņoto loģistiku.'],
      ['Kas notiek nepareizas deklarācijas gadījumā?', 'Darījums tiek apturēts. Var rakstiski vienoties par cenas korekciju vai darījumu atcelt saskaņā ar līgumu.'],
    ],
    footer: 'Atlasīti Zviedrijas auto Eiropas tirgotājiem.',
  },
  lt: {
    ...en,
    dealerAccess: 'Autorell prieiga prekybininkams',
    countryTitle: (country) => `Europinių automobilių tiekimas prekybininkams: ${country}`,
    cityTitle: (city) => `Naujas automobilių tiekimo kanalas prekybininkams: ${city}`,
    intro: 'Siūlykite kainą už atrinktus švediškus automobilius profesionalioje platformoje. Autorell koordinuoja sutartį, mokėjimą, patikrą, paėmimą, dokumentus ir eksportą.',
    apply: 'Prašyti prieigos',
    login: 'Prekybininko prisijungimas',
    howItWorks: 'Kaip tai veikia',
    liveMarket: 'Aktyvi rinka',
    dealerDemand: 'Prekybininkų paklausa',
    whyTitle: 'Jūs siūlote. Autorell valdo sandorį.',
    whyText: 'Patikrinti prekybininkai gauna struktūrizuotus duomenis ir kontroliuojamą tarpvalstybinį procesą.',
    processTitle: 'Nuo prieigos iki pristatymo keturiais etapais.',
    vehicleTitle: 'Modernūs automobiliai profesionaliam perpardavimui.',
    vehicleText: 'Pirmenybę teikiame naujesniems automobiliams su rinkai tinkama rida, skaidria būkle ir paklausa Europoje.',
    locationsTitle: 'Svarbios prekybininkų rinkos',
    allMarkets: 'Visos Europos rinkos',
    verified: 'Patikrintos įmonės',
    dealerOnly: 'Tik B2B',
    inspected: 'Patikra Švedijoje',
    stepTitles: ['Gaukite prieigą', 'Peržiūrėkite ir siūlykite', 'Mokėkite Autorell', 'Patikra ir eksportas'],
    standards: ['Metai 2018+', 'Mažiau nei 100 000 km', 'Gera deklaruota būklė', 'Modernus ir elektrifikuotas'],
    faqTitle: 'Prekybininkų klausimai',
    faq: [
      ['Kur yra automobiliai?', 'Dabartinė pasiūla atrenkama ir tikrinama Švedijoje. Autorell vietoje Lietuvoje automobilių neperka.'],
      ['Kas gali siūlyti kainą?', 'Tik patvirtintos automobilių įmonės su patikrintais įmonės, PVM ir kontaktiniais duomenimis.'],
      ['Ką tvarko Autorell?', 'Koordinuojame sutartį, mokėjimo gavimą, patikrą Švedijoje, paėmimą, eksporto dokumentus ir sutartą logistiką.'],
      ['Kas nutinka, jei deklaracija neteisinga?', 'Sandoris sustabdomas. Raštu galima sutarti dėl kainos pakeitimo arba sandorį nutraukti pagal sutartį.'],
    ],
    footer: 'Atrinkti švediški automobiliai Europos prekybininkams.',
  },
  el: {
    ...en,
    dealerAccess: 'Πρόσβαση εμπόρων Autorell',
    countryTitle: (country) => `Ευρωπαϊκή προμήθεια οχημάτων για εμπόρους στην ${country}`,
    cityTitle: (city) => `Νέο κανάλι οχημάτων για εμπόρους στην ${city}`,
    intro: 'Υποβάλετε προσφορές για επιλεγμένα σουηδικά οχήματα σε επαγγελματική πλατφόρμα. Η Autorell συντονίζει σύμβαση, πληρωμή, έλεγχο, παραλαβή, έγγραφα και εξαγωγή.',
    apply: 'Αίτηση πρόσβασης',
    login: 'Σύνδεση εμπόρου',
    howItWorks: 'Πώς λειτουργεί',
    liveMarket: 'Ενεργή αγορά',
    dealerDemand: 'Ζήτηση εμπόρων',
    whyTitle: 'Εσείς προσφέρετε. Η Autorell διαχειρίζεται τη συναλλαγή.',
    whyText: 'Οι επαληθευμένοι έμποροι λαμβάνουν δομημένα δεδομένα και ελεγχόμενη διασυνοριακή διαδικασία.',
    processTitle: 'Από την πρόσβαση στην παράδοση σε τέσσερα βήματα.',
    vehicleTitle: 'Σύγχρονα οχήματα για επαγγελματική μεταπώληση.',
    vehicleText: 'Εστιάζουμε σε νεότερα οχήματα με εμπορεύσιμα χιλιόμετρα, διαφανή κατάσταση και ευρωπαϊκή ζήτηση.',
    locationsTitle: 'Σημαντικές αγορές εμπόρων',
    allMarkets: 'Όλες οι ευρωπαϊκές αγορές',
    verified: 'Επαληθευμένες εταιρείες',
    dealerOnly: 'Μόνο B2B',
    inspected: 'Έλεγχος στη Σουηδία',
    stepTitles: ['Αποκτήστε πρόσβαση', 'Ελέγξτε και προσφέρετε', 'Πληρώστε την Autorell', 'Έλεγχος και εξαγωγή'],
    standards: ['Έτος 2018+', 'Κάτω από 100.000 km', 'Καλή δηλωμένη κατάσταση', 'Σύγχρονα και ηλεκτροκίνητα'],
    faqTitle: 'Ερωτήσεις εμπόρων',
    faq: [
      ['Πού βρίσκονται τα οχήματα;', 'Η τρέχουσα προσφορά επιλέγεται και ελέγχεται στη Σουηδία. Η Autorell δεν αγοράζει οχήματα τοπικά στη χώρα σας.'],
      ['Ποιος μπορεί να υποβάλει προσφορά;', 'Μόνο εγκεκριμένες επιχειρήσεις αυτοκινήτου με επαληθευμένα εταιρικά, φορολογικά και στοιχεία επικοινωνίας.'],
      ['Τι αναλαμβάνει η Autorell;', 'Συντονίζουμε τη σύμβαση, την πληρωμή, τον έλεγχο στη Σουηδία, την παραλαβή, τα έγγραφα εξαγωγής και τη συμφωνημένη μεταφορά.'],
      ['Τι γίνεται αν η δήλωση είναι λανθασμένη;', 'Η συναλλαγή παγώνει. Μπορεί να συμφωνηθεί γραπτή προσαρμογή τιμής ή να ακυρωθεί βάσει της σύμβασης.'],
    ],
    footer: 'Επιλεγμένα σουηδικά οχήματα για Ευρωπαίους εμπόρους.',
  },
}

export const euBuyerMarkets: EuBuyerMarket[] = [
  { code: 'at', country: 'Austria', countryLocal: 'Österreich', flag: '🇦🇹', language: 'de', cities: [['wien','Wien','Wien'],['graz','Graz','Steiermark'],['linz','Linz','Oberösterreich'],['salzburg','Salzburg','Salzburg']].map(([slug,name,region])=>({slug,name,region})), demand: ['Premium & Kombi','Elektro & Hybrid','SUV & Allrad'] },
  { code: 'be', country: 'Belgium', countryLocal: 'België', flag: '🇧🇪', language: 'nl', cities: [['brussel','Brussel','Brussels Hoofdstedelijk Gewest'],['antwerpen','Antwerpen','Vlaanderen'],['gent','Gent','Oost-Vlaanderen'],['luik','Luik','Wallonië']].map(([slug,name,region])=>({slug,name,region})), demand: ['Bedrijfswagens','Plug-in hybride','Premium estates'] },
  { code: 'bg', country: 'Bulgaria', countryLocal: 'България', flag: '🇧🇬', language: 'bg', cities: [['sofia','София','София-град'],['plovdiv','Пловдив','Пловдив'],['varna','Варна','Варна']].map(([slug,name,region])=>({slug,name,region})), demand: ['Млади автомобили','SUV','Икономични двигатели'] },
  { code: 'hr', country: 'Croatia', countryLocal: 'Hrvatska', homeTitle: 'Europska nabava vozila za trgovce u Hrvatskoj', flag: '🇭🇷', language: 'hr', cities: [['zagreb','Zagreb','Grad Zagreb'],['split','Split','Dalmacija'],['rijeka','Rijeka','Primorje']].map(([slug,name,region])=>({slug,name,region})), demand: ['Kompaktni SUV','Hibridi','Flotna vozila'] },
  { code: 'cy', country: 'Cyprus', countryLocal: 'Κύπρος', homeTitle: 'Ευρωπαϊκή προμήθεια οχημάτων για εμπόρους στην Κύπρο', flag: '🇨🇾', language: 'el', cities: [['nicosia','Λευκωσία','Λευκωσία'],['limassol','Λεμεσός','Λεμεσός'],['larnaca','Λάρνακα','Λάρνακα']].map(([slug,name,region])=>({slug,name,region})), demand: ['Συμβατά οχήματα','Υβριδικά','SUV'] },
  { code: 'cz', country: 'Czechia', countryLocal: 'Česko', homeTitle: 'Evropský nákup vozidel pro prodejce v Česku', flag: '🇨🇿', language: 'cs', cities: [['praha','Praha','Praha'],['brno','Brno','Jihomoravský kraj'],['ostrava','Ostrava','Moravskoslezský kraj'],['plzen','Plzeň','Plzeňský kraj']].map(([slug,name,region])=>({slug,name,region})), demand: ['Kombi','SUV','Firemní vozy'] },
  { code: 'dk', country: 'Denmark', countryLocal: 'Danmark', flag: '🇩🇰', language: 'da', cities: [['koebenhavn','København','Hovedstaden'],['aarhus','Aarhus','Midtjylland'],['odense','Odense','Syddanmark'],['aalborg','Aalborg','Nordjylland']].map(([slug,name,region])=>({slug,name,region})), demand: ['Elbiler','Kompakte SUV','Effektive hybrider'] },
  { code: 'ee', country: 'Estonia', countryLocal: 'Eesti', flag: '🇪🇪', language: 'et', cities: [['tallinn','Tallinn','Harjumaa'],['tartu','Tartu','Tartumaa'],['paernu','Pärnu','Pärnumaa']].map(([slug,name,region])=>({slug,name,region})), demand: ['Põhjamaine varustus','Elektriautod','Nelikvedu'] },
  { code: 'fi', country: 'Finland', countryLocal: 'Suomi', flag: '🇫🇮', language: 'fi', cities: [['helsinki','Helsinki','Uusimaa'],['tampere','Tampere','Pirkanmaa'],['turku','Turku','Varsinais-Suomi'],['oulu','Oulu','Pohjois-Pohjanmaa']].map(([slug,name,region])=>({slug,name,region})), demand: ['Neliveto','Sähkö & hybridi','Farmariautot'] },
  { code: 'fr', country: 'France', countryLocal: 'France', flag: '🇫🇷', language: 'fr', cities: [['paris','Paris','Île-de-France'],['lyon','Lyon','Auvergne-Rhône-Alpes'],['lille','Lille','Hauts-de-France'],['marseille','Marseille','Provence'],['bordeaux','Bordeaux','Nouvelle-Aquitaine']].map(([slug,name,region])=>({slug,name,region})), demand: ['Électrique','Compactes','SUV familiaux'] },
  { code: 'gr', country: 'Greece', countryLocal: 'Ελλάδα', flag: '🇬🇷', language: 'el', cities: [['athina','Αθήνα','Αττική'],['thessaloniki','Θεσσαλονίκη','Κεντρική Μακεδονία'],['patra','Πάτρα','Δυτική Ελλάδα']].map(([slug,name,region])=>({slug,name,region})), demand: ['Υβριδικά','Compact SUV','Οικονομικά οχήματα'] },
  { code: 'hu', country: 'Hungary', countryLocal: 'Magyarország', flag: '🇭🇺', language: 'hu', cities: [['budapest','Budapest','Közép-Magyarország'],['debrecen','Debrecen','Hajdú-Bihar'],['gyor','Győr','Győr-Moson-Sopron']].map(([slug,name,region])=>({slug,name,region})), demand: ['Fiatal használt','SUV','Hibrid'] },
  { code: 'ie', country: 'Ireland', countryLocal: 'Ireland', flag: '🇮🇪', language: 'en', cities: [['dublin','Dublin','Leinster'],['cork','Cork','Munster'],['galway','Galway','Connacht']].map(([slug,name,region])=>({slug,name,region})), demand: ['Compatible specifications','Electric vehicles','Family SUV'] },
  { code: 'it', country: 'Italy', countryLocal: 'Italia', flag: '🇮🇹', language: 'it', cities: [['milano','Milano','Lombardia'],['roma','Roma','Lazio'],['torino','Torino','Piemonte'],['bologna','Bologna','Emilia-Romagna'],['verona','Verona','Veneto']].map(([slug,name,region])=>({slug,name,region})), demand: ['Premium compatte','Ibride','Crossover urbani'] },
  { code: 'lv', country: 'Latvia', countryLocal: 'Latvija', flag: '🇱🇻', language: 'lv', cities: [['riga','Rīga','Rīga'],['daugavpils','Daugavpils','Latgale'],['liepaja','Liepāja','Kurzeme']].map(([slug,name,region])=>({slug,name,region})), demand: ['Jauni lietoti auto','SUV & universāļi','Premium'] },
  { code: 'lt', country: 'Lithuania', countryLocal: 'Lietuva', flag: '🇱🇹', language: 'lt', cities: [['vilnius','Vilnius','Vilniaus apskritis'],['kaunas','Kaunas','Kauno apskritis'],['klaipeda','Klaipėda','Klaipėdos apskritis']].map(([slug,name,region])=>({slug,name,region})), demand: ['Prekybininkų atsargos','SUV','Modernūs premium'] },
  { code: 'lu', country: 'Luxembourg', countryLocal: 'Luxembourg', flag: '🇱🇺', language: 'fr', cities: [['luxembourg','Luxembourg','Centre'],['esch-sur-alzette','Esch-sur-Alzette','Sud']].map(([slug,name,region])=>({slug,name,region})), demand: ['Véhicules de société','Électrique','SUV premium'] },
  { code: 'mt', country: 'Malta', countryLocal: 'Malta', flag: '🇲🇹', language: 'en', cities: [['valletta','Valletta','South Eastern'],['birkirkara','Birkirkara','Central'],['sliema','Sliema','Northern Harbour']].map(([slug,name,region])=>({slug,name,region})), demand: ['Compatible specifications','Compact cars','Hybrid vehicles'] },
  { code: 'nl', country: 'Netherlands', countryLocal: 'Nederland', flag: '🇳🇱', language: 'nl', cities: [['amsterdam','Amsterdam','Noord-Holland'],['rotterdam','Rotterdam','Zuid-Holland'],['utrecht','Utrecht','Utrecht'],['eindhoven','Eindhoven','Noord-Brabant'],['zwolle','Zwolle','Overijssel']].map(([slug,name,region])=>({slug,name,region})), demand: ['Elektrische auto’s','Efficiënte hybrides','Compacte modellen'] },
  { code: 'pl', country: 'Poland', countryLocal: 'Polska', homeTitle: 'Europejskie samochody dla dealerów w Polsce', flag: '🇵🇱', language: 'pl', cities: [['warszawa','Warszawa','Mazowieckie'],['krakow','Kraków','Małopolskie'],['wroclaw','Wrocław','Dolnośląskie'],['poznan','Poznań','Wielkopolskie'],['gdansk','Gdańsk','Pomorskie'],['katowice','Katowice','Śląskie']].map(([slug,name,region])=>({slug,name,region})), demand: ['Młode używane','SUV & kombi','Diesel & hybryda'] },
  { code: 'pt', country: 'Portugal', countryLocal: 'Portugal', flag: '🇵🇹', language: 'pt', cities: [['lisboa','Lisboa','Lisboa'],['porto','Porto','Norte'],['braga','Braga','Norte']].map(([slug,name,region])=>({slug,name,region})), demand: ['Compactos eficientes','Híbridos','SUV urbano'] },
  { code: 'ro', country: 'Romania', countryLocal: 'România', flag: '🇷🇴', language: 'ro', cities: [['bucuresti','București','București-Ilfov'],['cluj-napoca','Cluj-Napoca','Cluj'],['timisoara','Timișoara','Timiș'],['iasi','Iași','Iași']].map(([slug,name,region])=>({slug,name,region})), demand: ['Vehicule rulate tinere','Motoare eficiente','SUV familial'] },
  { code: 'sk', country: 'Slovakia', countryLocal: 'Slovensko', homeTitle: 'Európsky nákup vozidiel pre predajcov na Slovensku', flag: '🇸🇰', language: 'sk', cities: [['bratislava','Bratislava','Bratislavský kraj'],['kosice','Košice','Košický kraj'],['zilina','Žilina','Žilinský kraj']].map(([slug,name,region])=>({slug,name,region})), demand: ['Kombi','SUV','Firemné vozidlá'] },
  { code: 'si', country: 'Slovenia', countryLocal: 'Slovenija', homeTitle: 'Evropska nabava vozil za trgovce v Sloveniji', flag: '🇸🇮', language: 'sl', cities: [['ljubljana','Ljubljana','Osrednjeslovenska'],['maribor','Maribor','Podravska'],['koper','Koper','Obalno-kraška']].map(([slug,name,region])=>({slug,name,region})), demand: ['Kombi & SUV','Hibridi','Mlajša vozila'] },
  { code: 'es', country: 'Spain', countryLocal: 'España', flag: '🇪🇸', language: 'es', cities: [['madrid','Madrid','Comunidad de Madrid'],['barcelona','Barcelona','Cataluña'],['valencia','Valencia','Comunidad Valenciana'],['bilbao','Bilbao','País Vasco'],['sevilla','Sevilla','Andalucía']].map(([slug,name,region])=>({slug,name,region})), demand: ['Gasolina eficiente','Híbridos','SUV & crossover'] },
]

export function getEuBuyerMarket(code: string) {
  return euBuyerMarkets.find((market) => market.code === code)
}

export function getEuBuyerMarketByCountrySlug(slug: string) {
  return euBuyerMarkets.find(
    (market) => market.country.toLowerCase() === slug.toLowerCase(),
  )
}

export function getEuBuyerCopy(language: EuBuyerLanguage) {
  return copies[language]
}

export function getEuBuyerPath(market: EuBuyerMarket, citySlug?: string) {
  return citySlug
    ? `/${market.code}/dealers/${citySlug}`
    : `/${market.code}`
}

export function getEuBuyerHreflang(market: EuBuyerMarket) {
  return `${market.language}-${market.code.toUpperCase()}`
}

export function getEuBuyerHubAlternates() {
  return Object.fromEntries([
    ['en', 'https://www.autorell.com/'],
    ...euBuyerMarkets.map((market) => [
      getEuBuyerHreflang(market),
      `https://www.autorell.com${getEuBuyerPath(market)}`,
    ]),
    ['x-default', 'https://www.autorell.com/dealers'],
  ])
}

export function getAllEuBuyerPaths() {
  return euBuyerMarkets.flatMap((market) => [
    getEuBuyerPath(market),
    ...market.cities.map((city) => getEuBuyerPath(market, city.slug)),
  ])
}
