import { translationLocale, type PublicLocale } from '@/lib/public-i18n'
import type { BusinessPilotLocale } from '@/lib/business-pilot-i18n'

export type InventoryMethod = 'website' | 'xml' | 'csv' | 'api' | 'dms'

type MethodCopy = { key: InventoryMethod; title: string; text: string; status?: string; selectable?: boolean }

export type InventoryImportErrorCopy = {
  rateLimited: string
  permission: string
  verification: string
  approval: string
  details: string
  unavailable: string
  sourceProblem: string
}

export type InventoryImportCopy = {
  publicPage: {
    metaTitle: string
    metaDescription: string
    eyebrow: string
    title: string
    intro: string
    primaryCta: string
    secondaryCta: string
    methodsTitle: string
    methodsIntro: string
    methods: MethodCopy[]
    syncTitle: string
    syncIntro: string
    syncRules: string[]
    safetyTitle: string
    safetyBody: string
  }
  portal: {
    navLabel: string
    title: string
    description: string
    addSource: string
    metrics: string[]
    pilotActive: string
    noAutomaticPayment: string
    sourcesTitle: string
    noSources: string
    sourceLabels: string[]
    actions: string[]
    statuses: Record<string, string>
  }
  wizard: {
    title: string
    intro: string
    steps: string[]
    methodTitle: string
    detailsTitle: string
    verificationTitle: string
    verificationIntro: string
    analysisTitle: string
    analysisIntro: string
    previewTitle: string
    previewIntro: string
    previewColumns: [string, string, string, string]
    approvalTitle: string
    approvalIntro: string
    fields: string[]
    verificationMethods: string[]
    analysisChecks: string[]
    previewEmpty: string
    consents: string[]
    back: string
    next: string
    saveSource: string
    saving: string
    verify: string
    startAnalysis: string
    approve: string
    close: string
    selectOption: string
    success: string
    onboardingSuccess: string
    generateVerificationToken: string
    analysisQueued: string
    genericError: string
    deleteConfirm: string
  }
  errors: InventoryImportErrorCopy
}

type InventoryImportCopySource = Omit<InventoryImportCopy, 'errors' | 'wizard'> & {
  wizard: Omit<InventoryImportCopy['wizard'], 'onboardingSuccess' | 'generateVerificationToken' | 'analysisQueued'>
}

const copies: Record<BusinessPilotLocale, InventoryImportCopySource> = {
  en: {
    publicPage: {
      metaTitle: 'Automatic dealer inventory import | Autorell',
      metaDescription: 'Connect an existing vehicle inventory to Autorell through a verified website, XML, CSV, API or a tailored DMS onboarding.',
      eyebrow: 'Autorell inventory connection',
      title: 'Connect your existing vehicle inventory',
      intro: 'Do not publish the same vehicles manually on another platform. Autorell can import your existing inventory and keep prices, images and stock status automatically updated.',
      primaryCta: 'Apply for the free pilot',
      secondaryCta: 'Contact our business team',
      methodsTitle: 'Five ways to connect',
      methodsIntro: 'We choose the source that provides the most reliable data and keep every connection under your company’s control.',
      methods: [
        { key: 'website', title: 'Website import', text: 'Autorell analyses the company’s verified website and finds its vehicle inventory pages.' },
        { key: 'xml', title: 'XML feed', text: 'The company provides a structured XML feed with agreed fields and update frequency.' },
        { key: 'csv', title: 'CSV import', text: 'Upload a CSV file in Autorell’s format, with support for scheduled delivery later.' },
        { key: 'api', title: 'API', text: 'Autorell connects to the company’s or system provider’s API through a reviewed server-side integration.' },
        { key: 'dms', title: 'DMS integration', text: 'A tailored onboarding case is created for the company’s DMS or inventory system.' },
      ],
      syncTitle: 'Automatic and controlled synchronisation',
      syncIntro: 'Successful synchronisations keep the inventory current without letting a temporary source failure remove all listings.',
      syncRules: ['An approved new source vehicle creates a new Autorell listing.', 'A price change updates the linked listing.', 'Changed images and vehicle properties are synchronised.', 'A sold or removed vehicle is paused after confirmed checks.', 'A temporary website outage never unpublishes the full inventory.'],
      safetyTitle: 'Verification comes before publication',
      safetyBody: 'Autorell verifies the source, previews the data and records the company’s rights and consent before any imported listing can be published.',
    },
    portal: {
      navLabel: 'Inventory connection', title: 'Inventory connection', description: 'Manage verified import sources, previews, synchronisation and pilot status for your company.', addSource: 'Add import source',
      metrics: ['Active sources', 'Imported vehicles', 'Published vehicles', 'Needs review', 'Sync errors', 'Last successful sync', 'Next scheduled sync', 'Connected locations'],
      pilotActive: 'Pilot active', noAutomaticPayment: 'No automatic payment', sourcesTitle: 'Import sources', noSources: 'No import source has been added yet.',
      sourceLabels: ['Type', 'Source', 'Status', 'Verification', 'Found', 'Published', 'Last sync', 'Next sync', 'Errors'],
      actions: ['View source', 'Start sync', 'Pause sync', 'Resume sync', 'View sync log', 'Edit mapping', 'Delete source'],
      statuses: { draft: 'Draft', analyzing: 'Analysing', ready: 'Ready', active: 'Active', paused: 'Paused', error: 'Error', disabled: 'Disabled', unverified: 'Not verified', pending: 'Pending', verified: 'Verified', failed: 'Failed', manual_review: 'Manual review' },
    },
    wizard: {
      title: 'Add import source', intro: 'Create the source first, verify it, inspect the analysis and approve publication separately.',
      steps: ['Method', 'Details', 'Verification', 'Analysis', 'Preview', 'Approval'], methodTitle: 'Choose connection method', detailsTitle: 'Enter source details', verificationTitle: 'Verify the source', verificationIntro: 'Website domains must be verified by DNS, HTML file, meta tag or an Autorell administrator.', analysisTitle: 'Analyse the source', analysisIntro: 'Autorell checks the verified source for sitemaps, vehicle pages and deterministic structured data.', previewTitle: 'Preview vehicles', previewIntro: 'Review at least ten examples, their data quality and any warnings before approval.', previewColumns: ['Title', 'Price', 'Quality', 'Status'], approvalTitle: 'Approve rights and synchronisation', approvalIntro: 'Nothing can be published until all confirmations have been accepted.',
      fields: ['Source name', 'Website URL', 'Specific inventory URL', 'Feed URL', 'Documentation URL', 'Sync every (hours)', 'System provider', 'Technical contact', 'Authentication method', 'Optional subdomains', 'Location', 'Import limit'],
      verificationMethods: ['DNS record', 'HTML file', 'Meta tag', 'Manual admin verification'], analysisChecks: ['Domain verified', 'Sitemap found', 'Inventory pages found', 'Vehicle listings found', 'Ready for import', 'Needs review'], previewEmpty: 'No preview is available yet. Verify the source and complete an analysis first.',
      consents: ['The company owns or may use the vehicle information.', 'The company may publish the images.', 'Autorell may store and display the information.', 'Autorell may keep the inventory automatically synchronised.', 'The company accepts the pilot terms.'],
      back: 'Back', next: 'Next', saveSource: 'Save source', saving: 'Saving', verify: 'Check verification', startAnalysis: 'Start analysis', approve: 'Approve source', close: 'Close', selectOption: 'Select an option', success: 'The source has been saved. No listing is published automatically.', genericError: 'The action could not be completed. Check the details and try again.', deleteConfirm: 'Delete this source? Imported listings are not removed automatically.',
    },
  },
  sv: {
    publicPage: {
      metaTitle: 'Automatisk lagerimport för fordonsföretag | Autorell', metaDescription: 'Anslut ett befintligt fordonslager till Autorell via verifierad webbplats, XML, CSV, API eller anpassad DMS-onboarding.', eyebrow: 'Autorell lageranslutning', title: 'Anslut ert befintliga fordonslager', intro: 'Publicera inte samma fordon manuellt på ännu en plattform. Autorell kan importera ert befintliga lager och automatiskt hålla priser, bilder och lagerstatus uppdaterade.', primaryCta: 'Ansök om kostnadsfri pilot', secondaryCta: 'Kontakta vårt företagsteam', methodsTitle: 'Fem sätt att ansluta', methodsIntro: 'Vi väljer den källa som ger tillförlitligast data och låter företaget behålla kontrollen över varje anslutning.',
      methods: [
        { key: 'website', title: 'Webbplatsimport', text: 'Autorell analyserar företagets verifierade webbplats och hittar lagrets fordonssidor.' },
        { key: 'xml', title: 'XML-feed', text: 'Företaget tillhandahåller en strukturerad XML-feed med överenskomna fält och intervall.' },
        { key: 'csv', title: 'CSV-import', text: 'Ladda upp en CSV-fil enligt Autorells format, med stöd för schemalagd leverans senare.' },
        { key: 'api', title: 'API', text: 'Autorell ansluter till företagets eller systemleverantörens API via en granskad serverintegration.' },
        { key: 'dms', title: 'DMS-integration', text: 'Ett anpassat onboardingärende skapas för företagets DMS- eller lagersystem.' },
      ],
      syncTitle: 'Automatisk och kontrollerad synk', syncIntro: 'Lyckade synkningar håller lagret aktuellt utan att ett tillfälligt källfel kan ta bort alla annonser.', syncRules: ['Ett godkänt nytt källfordon skapar en ny annons på Autorell.', 'En prisändring uppdaterar den kopplade annonsen.', 'Ändrade bilder och fordonsegenskaper synkas.', 'Ett sålt eller borttaget fordon pausas efter bekräftade kontroller.', 'Ett tillfälligt webbplatsfel avpublicerar aldrig hela lagret.'], safetyTitle: 'Verifiering före publicering', safetyBody: 'Autorell verifierar källan, förhandsgranskar datan och registrerar företagets rättigheter och samtycke innan en importerad annons kan publiceras.',
    },
    portal: {
      navLabel: 'Lageranslutning', title: 'Lageranslutning', description: 'Hantera verifierade importkällor, förhandsgranskning, synk och pilotstatus för ert företag.', addSource: 'Lägg till importkälla', metrics: ['Aktiva källor', 'Importerade fordon', 'Publicerade fordon', 'Behöver granskas', 'Synkfel', 'Senaste lyckade synk', 'Nästa planerade synk', 'Anslutna anläggningar'], pilotActive: 'Pilot aktiv', noAutomaticPayment: 'Ingen automatisk betalning', sourcesTitle: 'Importkällor', noSources: 'Ingen importkälla har lagts till ännu.', sourceLabels: ['Typ', 'Källa', 'Status', 'Verifiering', 'Hittade', 'Publicerade', 'Senaste synk', 'Nästa synk', 'Fel'], actions: ['Visa källa', 'Starta synk', 'Pausa synk', 'Återuppta synk', 'Visa synklogg', 'Ändra mappning', 'Ta bort källa'], statuses: { draft: 'Utkast', analyzing: 'Analyserar', ready: 'Klar', active: 'Aktiv', paused: 'Pausad', error: 'Fel', disabled: 'Inaktiverad', unverified: 'Ej verifierad', pending: 'Väntar', verified: 'Verifierad', failed: 'Misslyckad', manual_review: 'Manuell granskning' },
    },
    wizard: {
      title: 'Lägg till importkälla', intro: 'Skapa först källan, verifiera den, granska analysen och godkänn publicering separat.', steps: ['Metod', 'Uppgifter', 'Verifiering', 'Analys', 'Förhandsgranskning', 'Godkännande'], methodTitle: 'Välj anslutningsmetod', detailsTitle: 'Ange källuppgifter', verificationTitle: 'Verifiera källan', verificationIntro: 'Webbplatsdomäner måste verifieras via DNS, HTML-fil, meta-tagg eller en Autorell-administratör.', analysisTitle: 'Analysera källan', analysisIntro: 'Autorell kontrollerar den verifierade källan efter sitemaps, fordonssidor och deterministisk strukturerad data.', previewTitle: 'Förhandsgranska fordon', previewIntro: 'Granska minst tio exempel, datakvaliteten och eventuella varningar före godkännande.', previewColumns: ['Titel', 'Pris', 'Kvalitet', 'Status'], approvalTitle: 'Godkänn rättigheter och synk', approvalIntro: 'Inget kan publiceras innan alla bekräftelser har godkänts.', fields: ['Källans namn', 'Webbplatsens URL', 'Specifik lager-URL', 'Feed-URL', 'Dokumentationslänk', 'Synka var (timmar)', 'Systemleverantör', 'Teknisk kontakt', 'Autentiseringsmetod', 'Valbara underdomäner', 'Anläggning', 'Importgräns'], verificationMethods: ['DNS-post', 'HTML-fil', 'Meta-tagg', 'Manuell adminverifiering'], analysisChecks: ['Domän verifierad', 'Sitemap hittad', 'Lagersidor hittade', 'Fordonsannonser hittade', 'Klara för import', 'Behöver granskas'], previewEmpty: 'Ingen förhandsgranskning finns ännu. Verifiera källan och slutför en analys först.', consents: ['Företaget äger eller får använda fordonsinformationen.', 'Företaget har rätt att publicera bilderna.', 'Autorell får lagra och visa informationen.', 'Autorell får hålla lagret automatiskt synkroniserat.', 'Företaget godkänner pilotvillkoren.'], back: 'Tillbaka', next: 'Nästa', saveSource: 'Spara källa', saving: 'Sparar', verify: 'Kontrollera verifiering', startAnalysis: 'Starta analys', approve: 'Godkänn källa', close: 'Stäng', selectOption: 'Välj ett alternativ', success: 'Källan har sparats. Ingen annons publiceras automatiskt.', genericError: 'Åtgärden kunde inte genomföras. Kontrollera uppgifterna och försök igen.', deleteConfirm: 'Ta bort källan? Importerade annonser tas inte bort automatiskt.',
    },
  },
  de: {
    publicPage: {
      metaTitle: 'Automatischer Fahrzeugbestandsimport | Autorell', metaDescription: 'Verbinden Sie Ihren Fahrzeugbestand über eine verifizierte Website, XML, CSV, API oder individuelles DMS-Onboarding mit Autorell.', eyebrow: 'Autorell Bestandsanbindung', title: 'Verbinden Sie Ihren bestehenden Fahrzeugbestand', intro: 'Veröffentlichen Sie dieselben Fahrzeuge nicht manuell auf einer weiteren Plattform. Autorell kann Ihren Bestand importieren und Preise, Bilder und Verfügbarkeit automatisch aktuell halten.', primaryCta: 'Für kostenlosen Pilot bewerben', secondaryCta: 'Unser Unternehmensteam kontaktieren', methodsTitle: 'Fünf Wege zur Anbindung', methodsIntro: 'Wir wählen die zuverlässigste Datenquelle und Ihr Unternehmen behält die Kontrolle über jede Verbindung.', methods: [
        { key: 'website', title: 'Website-Import', text: 'Autorell analysiert die verifizierte Unternehmenswebsite und findet die Fahrzeugseiten.' }, { key: 'xml', title: 'XML-Feed', text: 'Das Unternehmen stellt einen strukturierten XML-Feed mit vereinbarten Feldern und Intervallen bereit.' }, { key: 'csv', title: 'CSV-Import', text: 'Laden Sie eine CSV-Datei im Autorell-Format hoch; eine geplante Lieferung kann später ergänzt werden.' }, { key: 'api', title: 'API', text: 'Autorell verbindet sich über eine geprüfte serverseitige Integration mit der API des Unternehmens oder Systemanbieters.' }, { key: 'dms', title: 'DMS-Integration', text: 'Für das DMS oder Bestandssystem wird ein individuelles Onboarding angelegt.' },
      ], syncTitle: 'Automatische und kontrollierte Synchronisierung', syncIntro: 'Erfolgreiche Synchronisierungen halten den Bestand aktuell, ohne dass ein vorübergehender Quellfehler alle Anzeigen entfernt.', syncRules: ['Ein genehmigtes neues Quellfahrzeug erzeugt eine neue Autorell-Anzeige.', 'Eine Preisänderung aktualisiert die verknüpfte Anzeige.', 'Geänderte Bilder und Fahrzeugeigenschaften werden synchronisiert.', 'Ein verkauftes oder entferntes Fahrzeug wird nach bestätigten Prüfungen pausiert.', 'Ein vorübergehender Website-Ausfall deaktiviert nie den gesamten Bestand.'], safetyTitle: 'Verifizierung vor Veröffentlichung', safetyBody: 'Autorell verifiziert die Quelle, zeigt eine Vorschau und erfasst Rechte sowie Einwilligung, bevor importierte Anzeigen veröffentlicht werden können.',
    },
    portal: { navLabel: 'Bestandsanbindung', title: 'Bestandsanbindung', description: 'Verifizierte Importquellen, Vorschauen, Synchronisierung und Pilotstatus verwalten.', addSource: 'Importquelle hinzufügen', metrics: ['Aktive Quellen', 'Importierte Fahrzeuge', 'Veröffentlichte Fahrzeuge', 'Prüfung nötig', 'Synchronisierungsfehler', 'Letzte erfolgreiche Synchronisierung', 'Nächste Synchronisierung', 'Verbundene Standorte'], pilotActive: 'Pilot aktiv', noAutomaticPayment: 'Keine automatische Zahlung', sourcesTitle: 'Importquellen', noSources: 'Noch keine Importquelle hinzugefügt.', sourceLabels: ['Typ', 'Quelle', 'Status', 'Verifizierung', 'Gefunden', 'Veröffentlicht', 'Letzte Synchronisierung', 'Nächste Synchronisierung', 'Fehler'], actions: ['Quelle öffnen', 'Synchronisierung starten', 'Pausieren', 'Fortsetzen', 'Protokoll anzeigen', 'Zuordnung ändern', 'Quelle löschen'], statuses: { draft: 'Entwurf', analyzing: 'Analyse', ready: 'Bereit', active: 'Aktiv', paused: 'Pausiert', error: 'Fehler', disabled: 'Deaktiviert', unverified: 'Nicht verifiziert', pending: 'Ausstehend', verified: 'Verifiziert', failed: 'Fehlgeschlagen', manual_review: 'Manuelle Prüfung' } },
    wizard: { title: 'Importquelle hinzufügen', intro: 'Quelle anlegen, verifizieren, Analyse prüfen und Veröffentlichung separat freigeben.', steps: ['Methode', 'Angaben', 'Verifizierung', 'Analyse', 'Vorschau', 'Freigabe'], methodTitle: 'Verbindungsmethode wählen', detailsTitle: 'Quelldaten eingeben', verificationTitle: 'Quelle verifizieren', verificationIntro: 'Website-Domains müssen per DNS, HTML-Datei, Meta-Tag oder durch Autorell verifiziert werden.', analysisTitle: 'Quelle analysieren', analysisIntro: 'Autorell prüft die verifizierte Quelle auf Sitemaps, Fahrzeugseiten und deterministische strukturierte Daten.', previewTitle: 'Fahrzeuge prüfen', previewIntro: 'Prüfen Sie mindestens zehn Beispiele, Datenqualität und Warnungen vor der Freigabe.', previewColumns: ['Titel', 'Preis', 'Qualität', 'Status'], approvalTitle: 'Rechte und Synchronisierung freigeben', approvalIntro: 'Vor Annahme aller Bestätigungen kann nichts veröffentlicht werden.', fields: ['Quellenname', 'Website-URL', 'Bestands-URL', 'Feed-URL', 'Dokumentations-URL', 'Intervall (Stunden)', 'Systemanbieter', 'Technischer Kontakt', 'Authentifizierung', 'Optionale Subdomains', 'Standort', 'Importgrenze'], verificationMethods: ['DNS-Eintrag', 'HTML-Datei', 'Meta-Tag', 'Manuelle Admin-Verifizierung'], analysisChecks: ['Domain verifiziert', 'Sitemap gefunden', 'Bestandsseiten gefunden', 'Fahrzeuganzeigen gefunden', 'Importbereit', 'Prüfung nötig'], previewEmpty: 'Noch keine Vorschau. Verifizieren Sie die Quelle und schließen Sie eine Analyse ab.', consents: ['Das Unternehmen besitzt oder darf die Fahrzeugdaten nutzen.', 'Das Unternehmen darf die Bilder veröffentlichen.', 'Autorell darf die Daten speichern und anzeigen.', 'Autorell darf den Bestand automatisch synchronisieren.', 'Das Unternehmen akzeptiert die Pilotbedingungen.'], back: 'Zurück', next: 'Weiter', saveSource: 'Quelle speichern', saving: 'Speichern', verify: 'Verifizierung prüfen', startAnalysis: 'Analyse starten', approve: 'Quelle freigeben', close: 'Schließen', selectOption: 'Option wählen', success: 'Die Quelle wurde gespeichert. Keine Anzeige wird automatisch veröffentlicht.', genericError: 'Die Aktion konnte nicht abgeschlossen werden. Prüfen Sie die Angaben.', deleteConfirm: 'Quelle löschen? Importierte Anzeigen werden nicht automatisch entfernt.' },
  },
  fr: {
    publicPage: { metaTitle: 'Import automatique du stock automobile | Autorell', metaDescription: 'Connectez un stock de véhicules via un site vérifié, XML, CSV, API ou un accompagnement DMS sur mesure.', eyebrow: 'Connexion de stock Autorell', title: 'Connectez votre stock de véhicules existant', intro: 'Ne publiez pas manuellement les mêmes véhicules sur une plateforme supplémentaire. Autorell peut importer votre stock et actualiser automatiquement les prix, images et disponibilités.', primaryCta: 'Candidater au pilote gratuit', secondaryCta: 'Contacter notre équipe entreprises', methodsTitle: 'Cinq modes de connexion', methodsIntro: 'Nous choisissons la source la plus fiable tout en laissant à votre entreprise le contrôle de chaque connexion.', methods: [
        { key: 'website', title: 'Import depuis le site', text: 'Autorell analyse le site vérifié de l’entreprise et identifie les pages de véhicules.' }, { key: 'xml', title: 'Flux XML', text: 'L’entreprise fournit un flux XML structuré avec les champs et la fréquence convenus.' }, { key: 'csv', title: 'Import CSV', text: 'Téléversez un fichier CSV au format Autorell, avec une livraison planifiée possible ultérieurement.' }, { key: 'api', title: 'API', text: 'Autorell se connecte à l’API de l’entreprise ou du fournisseur via une intégration serveur contrôlée.' }, { key: 'dms', title: 'Intégration DMS', text: 'Un dossier d’intégration sur mesure est créé pour le DMS ou le système de stock.' },
      ], syncTitle: 'Synchronisation automatique et contrôlée', syncIntro: 'Les synchronisations réussies maintiennent le stock à jour sans qu’une panne temporaire puisse retirer toutes les annonces.', syncRules: ['Un nouveau véhicule source approuvé crée une nouvelle annonce Autorell.', 'Un changement de prix met à jour l’annonce liée.', 'Les images et caractéristiques modifiées sont synchronisées.', 'Un véhicule vendu ou retiré est suspendu après des contrôles confirmés.', 'Une panne temporaire du site ne dépublie jamais tout le stock.'], safetyTitle: 'Vérification avant publication', safetyBody: 'Autorell vérifie la source, présente les données et enregistre les droits et consentements avant toute publication.' },
    portal: { navLabel: 'Connexion du stock', title: 'Connexion du stock', description: 'Gérez les sources vérifiées, les aperçus, la synchronisation et le statut du pilote.', addSource: 'Ajouter une source', metrics: ['Sources actives', 'Véhicules importés', 'Véhicules publiés', 'À vérifier', 'Erreurs de synchronisation', 'Dernière synchronisation réussie', 'Prochaine synchronisation', 'Sites connectés'], pilotActive: 'Pilote actif', noAutomaticPayment: 'Aucun paiement automatique', sourcesTitle: 'Sources d’import', noSources: 'Aucune source d’import ajoutée.', sourceLabels: ['Type', 'Source', 'Statut', 'Vérification', 'Trouvés', 'Publiés', 'Dernière synchro', 'Prochaine synchro', 'Erreurs'], actions: ['Ouvrir la source', 'Lancer la synchro', 'Suspendre', 'Reprendre', 'Voir le journal', 'Modifier le mapping', 'Supprimer'], statuses: { draft: 'Brouillon', analyzing: 'Analyse', ready: 'Prête', active: 'Active', paused: 'Suspendue', error: 'Erreur', disabled: 'Désactivée', unverified: 'Non vérifiée', pending: 'En attente', verified: 'Vérifiée', failed: 'Échec', manual_review: 'Vérification manuelle' } },
    wizard: { title: 'Ajouter une source d’import', intro: 'Créez la source, vérifiez-la, examinez l’analyse puis approuvez la publication séparément.', steps: ['Méthode', 'Détails', 'Vérification', 'Analyse', 'Aperçu', 'Approbation'], methodTitle: 'Choisir la méthode', detailsTitle: 'Renseigner la source', verificationTitle: 'Vérifier la source', verificationIntro: 'Le domaine doit être vérifié par DNS, fichier HTML, balise meta ou un administrateur Autorell.', analysisTitle: 'Analyser la source', analysisIntro: 'Autorell recherche les sitemaps, pages de véhicules et données structurées déterministes.', previewTitle: 'Prévisualiser les véhicules', previewIntro: 'Examinez au moins dix exemples, la qualité des données et les avertissements.', previewColumns: ['Titre', 'Prix', 'Qualité', 'Statut'], approvalTitle: 'Approuver les droits et la synchronisation', approvalIntro: 'Rien ne peut être publié avant toutes les confirmations.', fields: ['Nom de la source', 'URL du site', 'URL du stock', 'URL du flux', 'URL de documentation', 'Intervalle (heures)', 'Fournisseur système', 'Contact technique', 'Authentification', 'Sous-domaines autorisés', 'Site', 'Limite d’import'], verificationMethods: ['Enregistrement DNS', 'Fichier HTML', 'Balise meta', 'Vérification manuelle'], analysisChecks: ['Domaine vérifié', 'Sitemap trouvée', 'Pages de stock trouvées', 'Annonces trouvées', 'Prêtes à importer', 'À vérifier'], previewEmpty: 'Aucun aperçu disponible. Vérifiez la source et terminez une analyse.', consents: ['L’entreprise possède ou peut utiliser les informations.', 'L’entreprise peut publier les images.', 'Autorell peut stocker et afficher les informations.', 'Autorell peut synchroniser automatiquement le stock.', 'L’entreprise accepte les conditions du pilote.'], back: 'Retour', next: 'Suivant', saveSource: 'Enregistrer la source', saving: 'Enregistrement', verify: 'Vérifier', startAnalysis: 'Lancer l’analyse', approve: 'Approuver la source', close: 'Fermer', selectOption: 'Choisir une option', success: 'La source est enregistrée. Aucune annonce n’est publiée automatiquement.', genericError: 'Action impossible. Vérifiez les informations et réessayez.', deleteConfirm: 'Supprimer cette source ? Les annonces importées ne seront pas supprimées automatiquement.' },
  },
  es: {
    publicPage: { metaTitle: 'Importación automática de inventario | Autorell', metaDescription: 'Conecta el inventario mediante un sitio verificado, XML, CSV, API o una incorporación DMS a medida.', eyebrow: 'Conexión de inventario Autorell', title: 'Conecta tu inventario de vehículos existente', intro: 'No publiques manualmente los mismos vehículos en otra plataforma. Autorell puede importar el inventario y mantener actualizados automáticamente precios, imágenes y disponibilidad.', primaryCta: 'Solicitar el piloto gratuito', secondaryCta: 'Contactar con el equipo de empresas', methodsTitle: 'Cinco formas de conexión', methodsIntro: 'Elegimos la fuente más fiable y la empresa conserva el control de cada conexión.', methods: [
        { key: 'website', title: 'Importación del sitio web', text: 'Autorell analiza el sitio verificado de la empresa y encuentra las páginas de vehículos.' }, { key: 'xml', title: 'Feed XML', text: 'La empresa proporciona un feed XML estructurado con los campos y frecuencia acordados.' }, { key: 'csv', title: 'Importación CSV', text: 'Sube un CSV con el formato de Autorell; más adelante podrá programarse su entrega.' }, { key: 'api', title: 'API', text: 'Autorell conecta con la API de la empresa o proveedor mediante una integración de servidor revisada.' }, { key: 'dms', title: 'Integración DMS', text: 'Se crea una incorporación a medida para el DMS o sistema de inventario.' },
      ], syncTitle: 'Sincronización automática y controlada', syncIntro: 'Las sincronizaciones correctas mantienen el inventario al día sin que un fallo temporal retire todos los anuncios.', syncRules: ['Un vehículo nuevo aprobado crea un nuevo anuncio en Autorell.', 'Un cambio de precio actualiza el anuncio vinculado.', 'Se sincronizan imágenes y características modificadas.', 'Un vehículo vendido o retirado se pausa tras comprobaciones confirmadas.', 'Una caída temporal del sitio nunca despublica todo el inventario.'], safetyTitle: 'Verificación antes de publicar', safetyBody: 'Autorell verifica la fuente, muestra una vista previa y registra los derechos y consentimientos antes de publicar.' },
    portal: { navLabel: 'Conexión de inventario', title: 'Conexión de inventario', description: 'Gestiona fuentes verificadas, vistas previas, sincronización y estado del piloto.', addSource: 'Añadir fuente', metrics: ['Fuentes activas', 'Vehículos importados', 'Vehículos publicados', 'Requiere revisión', 'Errores de sincronización', 'Última sincronización correcta', 'Próxima sincronización', 'Ubicaciones conectadas'], pilotActive: 'Piloto activo', noAutomaticPayment: 'Sin pago automático', sourcesTitle: 'Fuentes de importación', noSources: 'Todavía no hay fuentes.', sourceLabels: ['Tipo', 'Fuente', 'Estado', 'Verificación', 'Encontrados', 'Publicados', 'Última sync', 'Próxima sync', 'Errores'], actions: ['Abrir fuente', 'Iniciar sync', 'Pausar', 'Reanudar', 'Ver registro', 'Editar mapeo', 'Eliminar'], statuses: { draft: 'Borrador', analyzing: 'Analizando', ready: 'Lista', active: 'Activa', paused: 'Pausada', error: 'Error', disabled: 'Desactivada', unverified: 'No verificada', pending: 'Pendiente', verified: 'Verificada', failed: 'Fallida', manual_review: 'Revisión manual' } },
    wizard: { title: 'Añadir fuente de importación', intro: 'Crea la fuente, verifícala, revisa el análisis y aprueba la publicación por separado.', steps: ['Método', 'Datos', 'Verificación', 'Análisis', 'Vista previa', 'Aprobación'], methodTitle: 'Elige el método', detailsTitle: 'Introduce los datos', verificationTitle: 'Verifica la fuente', verificationIntro: 'El dominio debe verificarse por DNS, archivo HTML, metaetiqueta o un administrador.', analysisTitle: 'Analiza la fuente', analysisIntro: 'Autorell busca sitemaps, páginas de vehículos y datos estructurados deterministas.', previewTitle: 'Vista previa de vehículos', previewIntro: 'Revisa al menos diez ejemplos, su calidad y advertencias.', previewColumns: ['Título', 'Precio', 'Calidad', 'Estado'], approvalTitle: 'Aprueba derechos y sincronización', approvalIntro: 'Nada se publica hasta aceptar todas las confirmaciones.', fields: ['Nombre de la fuente', 'URL del sitio', 'URL del inventario', 'URL del feed', 'URL de documentación', 'Intervalo (horas)', 'Proveedor del sistema', 'Contacto técnico', 'Autenticación', 'Subdominios opcionales', 'Ubicación', 'Límite de importación'], verificationMethods: ['Registro DNS', 'Archivo HTML', 'Metaetiqueta', 'Verificación manual'], analysisChecks: ['Dominio verificado', 'Sitemap encontrada', 'Páginas encontradas', 'Anuncios encontrados', 'Listos para importar', 'Requiere revisión'], previewEmpty: 'Aún no hay vista previa. Verifica la fuente y completa un análisis.', consents: ['La empresa posee o puede usar la información.', 'La empresa puede publicar las imágenes.', 'Autorell puede almacenar y mostrar la información.', 'Autorell puede sincronizar el inventario.', 'La empresa acepta las condiciones del piloto.'], back: 'Atrás', next: 'Siguiente', saveSource: 'Guardar fuente', saving: 'Guardando', verify: 'Comprobar verificación', startAnalysis: 'Iniciar análisis', approve: 'Aprobar fuente', close: 'Cerrar', selectOption: 'Selecciona una opción', success: 'La fuente se ha guardado. No se publica ningún anuncio automáticamente.', genericError: 'No se pudo completar la acción. Revisa los datos.', deleteConfirm: '¿Eliminar la fuente? Los anuncios importados no se eliminan automáticamente.' },
  },
  it: {
    publicPage: { metaTitle: 'Importazione automatica inventario veicoli | Autorell', metaDescription: 'Collega l’inventario tramite sito verificato, XML, CSV, API o onboarding DMS personalizzato.', eyebrow: 'Collegamento inventario Autorell', title: 'Collega il tuo inventario di veicoli', intro: 'Non pubblicare manualmente gli stessi veicoli su un’altra piattaforma. Autorell può importare l’inventario e aggiornare automaticamente prezzi, immagini e disponibilità.', primaryCta: 'Candidati al progetto gratuito', secondaryCta: 'Contatta il team aziende', methodsTitle: 'Cinque modalità di collegamento', methodsIntro: 'Scegliamo la fonte più affidabile e l’azienda mantiene il controllo di ogni collegamento.', methods: [
        { key: 'website', title: 'Importazione dal sito', text: 'Autorell analizza il sito verificato dell’azienda e individua le pagine dei veicoli.' }, { key: 'xml', title: 'Feed XML', text: 'L’azienda fornisce un feed XML strutturato con campi e frequenza concordati.' }, { key: 'csv', title: 'Importazione CSV', text: 'Carica un CSV nel formato Autorell, predisposto per consegne programmate future.' }, { key: 'api', title: 'API', text: 'Autorell si collega all’API aziendale o del fornitore tramite un’integrazione server verificata.' }, { key: 'dms', title: 'Integrazione DMS', text: 'Viene creato un onboarding personalizzato per il DMS o sistema inventario.' },
      ], syncTitle: 'Sincronizzazione automatica e controllata', syncIntro: 'Le sincronizzazioni riuscite mantengono aggiornato l’inventario senza rimuovere tutto in caso di guasto temporaneo.', syncRules: ['Un nuovo veicolo approvato genera un nuovo annuncio Autorell.', 'Una variazione di prezzo aggiorna l’annuncio collegato.', 'Immagini e caratteristiche modificate vengono sincronizzate.', 'Un veicolo venduto o rimosso viene sospeso dopo controlli confermati.', 'Un guasto temporaneo non rimuove mai l’intero inventario.'], safetyTitle: 'Verifica prima della pubblicazione', safetyBody: 'Autorell verifica la fonte, mostra l’anteprima e registra diritti e consensi prima della pubblicazione.' },
    portal: { navLabel: 'Collegamento inventario', title: 'Collegamento inventario', description: 'Gestisci fonti verificate, anteprime, sincronizzazione e stato del progetto pilota.', addSource: 'Aggiungi fonte', metrics: ['Fonti attive', 'Veicoli importati', 'Veicoli pubblicati', 'Da verificare', 'Errori di sincronizzazione', 'Ultima sincronizzazione riuscita', 'Prossima sincronizzazione', 'Sedi collegate'], pilotActive: 'Pilota attivo', noAutomaticPayment: 'Nessun pagamento automatico', sourcesTitle: 'Fonti di importazione', noSources: 'Nessuna fonte aggiunta.', sourceLabels: ['Tipo', 'Fonte', 'Stato', 'Verifica', 'Trovati', 'Pubblicati', 'Ultima sync', 'Prossima sync', 'Errori'], actions: ['Apri fonte', 'Avvia sync', 'Sospendi', 'Riprendi', 'Mostra registro', 'Modifica mappatura', 'Elimina'], statuses: { draft: 'Bozza', analyzing: 'Analisi', ready: 'Pronta', active: 'Attiva', paused: 'Sospesa', error: 'Errore', disabled: 'Disabilitata', unverified: 'Non verificata', pending: 'In attesa', verified: 'Verificata', failed: 'Fallita', manual_review: 'Verifica manuale' } },
    wizard: { title: 'Aggiungi fonte di importazione', intro: 'Crea la fonte, verificala, esamina l’analisi e approva separatamente la pubblicazione.', steps: ['Metodo', 'Dettagli', 'Verifica', 'Analisi', 'Anteprima', 'Approvazione'], methodTitle: 'Scegli il metodo', detailsTitle: 'Inserisci i dettagli', verificationTitle: 'Verifica la fonte', verificationIntro: 'Il dominio va verificato tramite DNS, file HTML, meta tag o un amministratore.', analysisTitle: 'Analizza la fonte', analysisIntro: 'Autorell cerca sitemap, pagine veicolo e dati strutturati deterministici.', previewTitle: 'Anteprima veicoli', previewIntro: 'Controlla almeno dieci esempi, qualità e avvisi.', previewColumns: ['Titolo', 'Prezzo', 'Qualità', 'Stato'], approvalTitle: 'Approva diritti e sincronizzazione', approvalIntro: 'Nulla viene pubblicato prima di tutte le conferme.', fields: ['Nome fonte', 'URL sito', 'URL inventario', 'URL feed', 'URL documentazione', 'Intervallo (ore)', 'Fornitore sistema', 'Contatto tecnico', 'Autenticazione', 'Sottodomini opzionali', 'Sede', 'Limite importazione'], verificationMethods: ['Record DNS', 'File HTML', 'Meta tag', 'Verifica manuale'], analysisChecks: ['Dominio verificato', 'Sitemap trovata', 'Pagine inventario trovate', 'Annunci trovati', 'Pronti da importare', 'Da verificare'], previewEmpty: 'Nessuna anteprima disponibile. Verifica la fonte e completa un’analisi.', consents: ['L’azienda possiede o può usare le informazioni.', 'L’azienda può pubblicare le immagini.', 'Autorell può archiviare e mostrare le informazioni.', 'Autorell può sincronizzare l’inventario.', 'L’azienda accetta i termini del progetto pilota.'], back: 'Indietro', next: 'Avanti', saveSource: 'Salva fonte', saving: 'Salvataggio', verify: 'Controlla verifica', startAnalysis: 'Avvia analisi', approve: 'Approva fonte', close: 'Chiudi', selectOption: 'Seleziona', success: 'La fonte è stata salvata. Nessun annuncio viene pubblicato automaticamente.', genericError: 'Impossibile completare l’azione. Controlla i dati.', deleteConfirm: 'Eliminare la fonte? Gli annunci importati non vengono eliminati automaticamente.' },
  },
  nl: {
    publicPage: { metaTitle: 'Automatische voertuigvoorraadimport | Autorell', metaDescription: 'Koppel voorraad via een geverifieerde website, XML, CSV, API of DMS-onboarding op maat.', eyebrow: 'Autorell voorraadkoppeling', title: 'Koppel uw bestaande voertuigvoorraad', intro: 'Publiceer dezelfde voertuigen niet handmatig op nog een platform. Autorell kan uw voorraad importeren en prijzen, afbeeldingen en voorraadstatus automatisch bijwerken.', primaryCta: 'Aanmelden voor gratis pilot', secondaryCta: 'Neem contact op met ons bedrijfsteam', methodsTitle: 'Vijf manieren om te koppelen', methodsIntro: 'We kiezen de betrouwbaarste bron en uw bedrijf houdt controle over elke koppeling.', methods: [
        { key: 'website', title: 'Website-import', text: 'Autorell analyseert de geverifieerde bedrijfswebsite en vindt de voertuigpagina’s.' }, { key: 'xml', title: 'XML-feed', text: 'Het bedrijf levert een gestructureerde XML-feed met afgesproken velden en frequentie.' }, { key: 'csv', title: 'CSV-import', text: 'Upload een CSV volgens het Autorell-formaat; geplande levering kan later worden toegevoegd.' }, { key: 'api', title: 'API', text: 'Autorell koppelt via een gecontroleerde serverintegratie met de API van het bedrijf of de leverancier.' }, { key: 'dms', title: 'DMS-integratie', text: 'Voor het DMS of voorraadsysteem wordt een onboarding op maat aangemaakt.' },
      ], syncTitle: 'Automatische en gecontroleerde synchronisatie', syncIntro: 'Geslaagde synchronisaties houden de voorraad actueel zonder dat een tijdelijke bronstoring alle advertenties verwijdert.', syncRules: ['Een goedgekeurd nieuw bronvoertuig maakt een nieuwe Autorell-advertentie.', 'Een prijswijziging werkt de gekoppelde advertentie bij.', 'Gewijzigde afbeeldingen en eigenschappen worden gesynchroniseerd.', 'Een verkocht of verwijderd voertuig wordt na bevestigde controles gepauzeerd.', 'Een tijdelijke websitestoring haalt nooit de hele voorraad offline.'], safetyTitle: 'Verificatie vóór publicatie', safetyBody: 'Autorell verifieert de bron, toont een voorbeeld en registreert rechten en toestemming vóór publicatie.' },
    portal: { navLabel: 'Voorraadkoppeling', title: 'Voorraadkoppeling', description: 'Beheer geverifieerde bronnen, voorbeelden, synchronisatie en pilotstatus.', addSource: 'Importbron toevoegen', metrics: ['Actieve bronnen', 'Geïmporteerde voertuigen', 'Gepubliceerde voertuigen', 'Controle nodig', 'Synchronisatiefouten', 'Laatste geslaagde synchronisatie', 'Volgende synchronisatie', 'Gekoppelde locaties'], pilotActive: 'Pilot actief', noAutomaticPayment: 'Geen automatische betaling', sourcesTitle: 'Importbronnen', noSources: 'Nog geen importbron toegevoegd.', sourceLabels: ['Type', 'Bron', 'Status', 'Verificatie', 'Gevonden', 'Gepubliceerd', 'Laatste sync', 'Volgende sync', 'Fouten'], actions: ['Bron openen', 'Sync starten', 'Pauzeren', 'Hervatten', 'Log bekijken', 'Mapping wijzigen', 'Bron verwijderen'], statuses: { draft: 'Concept', analyzing: 'Analyseren', ready: 'Gereed', active: 'Actief', paused: 'Gepauzeerd', error: 'Fout', disabled: 'Uitgeschakeld', unverified: 'Niet geverifieerd', pending: 'In behandeling', verified: 'Geverifieerd', failed: 'Mislukt', manual_review: 'Handmatige controle' } },
    wizard: { title: 'Importbron toevoegen', intro: 'Maak de bron, verifieer deze, bekijk de analyse en keur publicatie apart goed.', steps: ['Methode', 'Gegevens', 'Verificatie', 'Analyse', 'Voorbeeld', 'Goedkeuring'], methodTitle: 'Kies de methode', detailsTitle: 'Voer brongegevens in', verificationTitle: 'Verifieer de bron', verificationIntro: 'Het domein moet via DNS, HTML-bestand, metatag of een Autorell-beheerder worden geverifieerd.', analysisTitle: 'Analyseer de bron', analysisIntro: 'Autorell zoekt naar sitemaps, voertuigpagina’s en deterministische gestructureerde gegevens.', previewTitle: 'Voertuigen bekijken', previewIntro: 'Controleer minstens tien voorbeelden, datakwaliteit en waarschuwingen.', previewColumns: ['Titel', 'Prijs', 'Kwaliteit', 'Status'], approvalTitle: 'Rechten en synchronisatie goedkeuren', approvalIntro: 'Niets wordt gepubliceerd voordat alle bevestigingen zijn geaccepteerd.', fields: ['Bronnaam', 'Website-URL', 'Voorraad-URL', 'Feed-URL', 'Documentatie-URL', 'Interval (uren)', 'Systeemleverancier', 'Technisch contact', 'Authenticatie', 'Optionele subdomeinen', 'Locatie', 'Importlimiet'], verificationMethods: ['DNS-record', 'HTML-bestand', 'Metatag', 'Handmatige verificatie'], analysisChecks: ['Domein geverifieerd', 'Sitemap gevonden', 'Voorraadpagina’s gevonden', 'Advertenties gevonden', 'Importgereed', 'Controle nodig'], previewEmpty: 'Nog geen voorbeeld. Verifieer de bron en voltooi een analyse.', consents: ['Het bedrijf bezit of mag de informatie gebruiken.', 'Het bedrijf mag de afbeeldingen publiceren.', 'Autorell mag de informatie opslaan en tonen.', 'Autorell mag de voorraad synchroniseren.', 'Het bedrijf accepteert de pilotvoorwaarden.'], back: 'Terug', next: 'Volgende', saveSource: 'Bron opslaan', saving: 'Opslaan', verify: 'Verificatie controleren', startAnalysis: 'Analyse starten', approve: 'Bron goedkeuren', close: 'Sluiten', selectOption: 'Kies een optie', success: 'De bron is opgeslagen. Er wordt niets automatisch gepubliceerd.', genericError: 'De actie kon niet worden voltooid. Controleer de gegevens.', deleteConfirm: 'Bron verwijderen? Geïmporteerde advertenties worden niet automatisch verwijderd.' },
  },
  fi: {
    publicPage: { metaTitle: 'Automaattinen ajoneuvovaraston tuonti | Autorell', metaDescription: 'Yhdistä varasto vahvistetun verkkosivuston, XML:n, CSV:n, API:n tai räätälöidyn DMS-käyttöönoton kautta.', eyebrow: 'Autorell-varastoyhteys', title: 'Yhdistä nykyinen ajoneuvovarastonne', intro: 'Älkää julkaisko samoja ajoneuvoja käsin vielä yhdellä alustalla. Autorell voi tuoda varaston ja pitää hinnat, kuvat ja varastotilan automaattisesti ajan tasalla.', primaryCta: 'Hae maksuttomaan pilottiin', secondaryCta: 'Ota yhteyttä yritystiimiin', methodsTitle: 'Viisi tapaa muodostaa yhteys', methodsIntro: 'Valitsemme luotettavimman lähteen, ja yritys säilyttää jokaisen yhteyden hallinnan.', methods: [
        { key: 'website', title: 'Verkkosivutuonti', text: 'Autorell analysoi vahvistetun yrityssivuston ja löytää ajoneuvosivut.' }, { key: 'xml', title: 'XML-syöte', text: 'Yritys toimittaa rakenteisen XML-syötteen sovituilla kentillä ja päivitysvälillä.' }, { key: 'csv', title: 'CSV-tuonti', text: 'Lataa Autorell-muotoinen CSV; ajastettu toimitus voidaan lisätä myöhemmin.' }, { key: 'api', title: 'API', text: 'Autorell muodostaa tarkistetun palvelinyhteyden yrityksen tai järjestelmätoimittajan APIin.' }, { key: 'dms', title: 'DMS-integraatio', text: 'DMS- tai varastojärjestelmälle luodaan räätälöity käyttöönottotapaus.' },
      ], syncTitle: 'Automaattinen ja hallittu synkronointi', syncIntro: 'Onnistuneet synkronoinnit pitävät varaston ajan tasalla ilman, että tilapäinen lähdevirhe poistaa kaikki ilmoitukset.', syncRules: ['Hyväksytty uusi lähdeajoneuvo luo uuden Autorell-ilmoituksen.', 'Hintamuutos päivittää linkitetyn ilmoituksen.', 'Muuttuneet kuvat ja ominaisuudet synkronoidaan.', 'Myyty tai poistettu ajoneuvo keskeytetään vahvistettujen tarkistusten jälkeen.', 'Tilapäinen verkkosivuhäiriö ei koskaan poista koko varastoa julkaisusta.'], safetyTitle: 'Vahvistus ennen julkaisua', safetyBody: 'Autorell vahvistaa lähteen, näyttää esikatselun ja kirjaa oikeudet sekä suostumukset ennen julkaisua.' },
    portal: { navLabel: 'Varastoyhteys', title: 'Varastoyhteys', description: 'Hallitse vahvistettuja lähteitä, esikatseluja, synkronointia ja pilotin tilaa.', addSource: 'Lisää tuontilähde', metrics: ['Aktiiviset lähteet', 'Tuodut ajoneuvot', 'Julkaistut ajoneuvot', 'Tarkistettavat', 'Synkronointivirheet', 'Viimeisin onnistunut synkronointi', 'Seuraava synkronointi', 'Yhdistetyt toimipisteet'], pilotActive: 'Pilotti aktiivinen', noAutomaticPayment: 'Ei automaattista maksua', sourcesTitle: 'Tuontilähteet', noSources: 'Tuontilähteitä ei ole vielä lisätty.', sourceLabels: ['Tyyppi', 'Lähde', 'Tila', 'Vahvistus', 'Löydetty', 'Julkaistu', 'Viimeisin synkronointi', 'Seuraava synkronointi', 'Virheet'], actions: ['Avaa lähde', 'Aloita synkronointi', 'Keskeytä', 'Jatka', 'Näytä loki', 'Muuta kenttäkarttaa', 'Poista lähde'], statuses: { draft: 'Luonnos', analyzing: 'Analysoidaan', ready: 'Valmis', active: 'Aktiivinen', paused: 'Keskeytetty', error: 'Virhe', disabled: 'Poistettu käytöstä', unverified: 'Ei vahvistettu', pending: 'Odottaa', verified: 'Vahvistettu', failed: 'Epäonnistui', manual_review: 'Manuaalinen tarkistus' } },
    wizard: { title: 'Lisää tuontilähde', intro: 'Luo lähde, vahvista se, tarkista analyysi ja hyväksy julkaisu erikseen.', steps: ['Menetelmä', 'Tiedot', 'Vahvistus', 'Analyysi', 'Esikatselu', 'Hyväksyntä'], methodTitle: 'Valitse menetelmä', detailsTitle: 'Anna lähdetiedot', verificationTitle: 'Vahvista lähde', verificationIntro: 'Verkkotunnus vahvistetaan DNS-tietueella, HTML-tiedostolla, metatunnisteella tai ylläpitäjän avulla.', analysisTitle: 'Analysoi lähde', analysisIntro: 'Autorell etsii sivustokarttoja, ajoneuvosivuja ja determinististä rakenteista dataa.', previewTitle: 'Esikatsele ajoneuvoja', previewIntro: 'Tarkista vähintään kymmenen esimerkkiä, datan laatu ja varoitukset.', previewColumns: ['Otsikko', 'Hinta', 'Laatu', 'Tila'], approvalTitle: 'Hyväksy oikeudet ja synkronointi', approvalIntro: 'Mitään ei julkaista ennen kaikkia vahvistuksia.', fields: ['Lähteen nimi', 'Sivuston URL', 'Varaston URL', 'Syötteen URL', 'Dokumentaation URL', 'Aikaväli (tuntia)', 'Järjestelmätoimittaja', 'Tekninen yhteyshenkilö', 'Tunnistautuminen', 'Valinnaiset aliverkkotunnukset', 'Toimipiste', 'Tuontiraja'], verificationMethods: ['DNS-tietue', 'HTML-tiedosto', 'Metatunniste', 'Manuaalinen vahvistus'], analysisChecks: ['Verkkotunnus vahvistettu', 'Sivustokartta löytyi', 'Varastosivut löytyivät', 'Ilmoitukset löytyivät', 'Valmiit tuontiin', 'Tarkistettavat'], previewEmpty: 'Esikatselua ei ole. Vahvista lähde ja suorita analyysi.', consents: ['Yritys omistaa tiedot tai saa käyttää niitä.', 'Yritys saa julkaista kuvat.', 'Autorell saa tallentaa ja näyttää tiedot.', 'Autorell saa synkronoida varaston.', 'Yritys hyväksyy pilottiehdot.'], back: 'Takaisin', next: 'Seuraava', saveSource: 'Tallenna lähde', saving: 'Tallennetaan', verify: 'Tarkista vahvistus', startAnalysis: 'Aloita analyysi', approve: 'Hyväksy lähde', close: 'Sulje', selectOption: 'Valitse vaihtoehto', success: 'Lähde on tallennettu. Mitään ilmoitusta ei julkaista automaattisesti.', genericError: 'Toimintoa ei voitu suorittaa. Tarkista tiedot.', deleteConfirm: 'Poistetaanko lähde? Tuotuja ilmoituksia ei poisteta automaattisesti.' },
  },
  da: {
    publicPage: { metaTitle: 'Automatisk import af køretøjslager | Autorell', metaDescription: 'Forbind lageret via verificeret hjemmeside, XML, CSV, API eller tilpasset DMS-onboarding.', eyebrow: 'Autorell lagerforbindelse', title: 'Forbind jeres eksisterende køretøjslager', intro: 'Udgiv ikke de samme køretøjer manuelt på endnu en platform. Autorell kan importere lageret og automatisk holde priser, billeder og lagerstatus opdateret.', primaryCta: 'Ansøg om gratis pilot', secondaryCta: 'Kontakt vores virksomhedsteam', methodsTitle: 'Fem måder at forbinde', methodsIntro: 'Vi vælger den mest pålidelige kilde, og virksomheden bevarer kontrollen over hver forbindelse.', methods: [
        { key: 'website', title: 'Hjemmesideimport', text: 'Autorell analyserer virksomhedens verificerede hjemmeside og finder køretøjssiderne.' }, { key: 'xml', title: 'XML-feed', text: 'Virksomheden leverer et struktureret XML-feed med aftalte felter og frekvens.' }, { key: 'csv', title: 'CSV-import', text: 'Upload en CSV i Autorell-format; planlagt levering kan tilføjes senere.' }, { key: 'api', title: 'API', text: 'Autorell forbinder til virksomhedens eller leverandørens API gennem en kontrolleret serverintegration.' }, { key: 'dms', title: 'DMS-integration', text: 'Der oprettes et tilpasset onboardingforløb til DMS- eller lagersystemet.' },
      ], syncTitle: 'Automatisk og kontrolleret synkronisering', syncIntro: 'Vellykkede synkroniseringer holder lageret aktuelt uden at en midlertidig kildefejl fjerner alle annoncer.', syncRules: ['Et godkendt nyt kildekøretøj opretter en ny Autorell-annonce.', 'En prisændring opdaterer den tilknyttede annonce.', 'Ændrede billeder og egenskaber synkroniseres.', 'Et solgt eller fjernet køretøj sættes på pause efter bekræftede kontroller.', 'En midlertidig hjemmesidefejl afpublicerer aldrig hele lageret.'], safetyTitle: 'Verificering før publicering', safetyBody: 'Autorell verificerer kilden, viser en forhåndsvisning og registrerer rettigheder og samtykke før publicering.' },
    portal: { navLabel: 'Lagerforbindelse', title: 'Lagerforbindelse', description: 'Administrer verificerede kilder, forhåndsvisninger, synkronisering og pilotstatus.', addSource: 'Tilføj importkilde', metrics: ['Aktive kilder', 'Importerede køretøjer', 'Publicerede køretøjer', 'Kræver gennemgang', 'Synkroniseringsfejl', 'Seneste vellykkede synkronisering', 'Næste synkronisering', 'Forbundne lokationer'], pilotActive: 'Pilot aktiv', noAutomaticPayment: 'Ingen automatisk betaling', sourcesTitle: 'Importkilder', noSources: 'Der er endnu ikke tilføjet en importkilde.', sourceLabels: ['Type', 'Kilde', 'Status', 'Verificering', 'Fundet', 'Publiceret', 'Seneste synk', 'Næste synk', 'Fejl'], actions: ['Åbn kilde', 'Start synk', 'Sæt på pause', 'Genoptag', 'Vis log', 'Rediger mapping', 'Slet kilde'], statuses: { draft: 'Kladde', analyzing: 'Analyserer', ready: 'Klar', active: 'Aktiv', paused: 'På pause', error: 'Fejl', disabled: 'Deaktiveret', unverified: 'Ikke verificeret', pending: 'Afventer', verified: 'Verificeret', failed: 'Mislykket', manual_review: 'Manuel gennemgang' } },
    wizard: { title: 'Tilføj importkilde', intro: 'Opret kilden, verificer den, gennemgå analysen og godkend publicering separat.', steps: ['Metode', 'Oplysninger', 'Verificering', 'Analyse', 'Forhåndsvisning', 'Godkendelse'], methodTitle: 'Vælg metode', detailsTitle: 'Angiv kildeoplysninger', verificationTitle: 'Verificer kilden', verificationIntro: 'Domænet skal verificeres via DNS, HTML-fil, meta-tag eller en Autorell-administrator.', analysisTitle: 'Analyser kilden', analysisIntro: 'Autorell søger efter sitemaps, køretøjssider og deterministiske strukturerede data.', previewTitle: 'Forhåndsvis køretøjer', previewIntro: 'Gennemgå mindst ti eksempler, datakvalitet og advarsler.', previewColumns: ['Titel', 'Pris', 'Kvalitet', 'Status'], approvalTitle: 'Godkend rettigheder og synkronisering', approvalIntro: 'Intet publiceres før alle bekræftelser er accepteret.', fields: ['Kildenavn', 'Hjemmeside-URL', 'Lager-URL', 'Feed-URL', 'Dokumentations-URL', 'Interval (timer)', 'Systemleverandør', 'Teknisk kontakt', 'Godkendelsesmetode', 'Valgfrie underdomæner', 'Lokation', 'Importgrænse'], verificationMethods: ['DNS-post', 'HTML-fil', 'Meta-tag', 'Manuel verificering'], analysisChecks: ['Domæne verificeret', 'Sitemap fundet', 'Lagersider fundet', 'Annoncer fundet', 'Klar til import', 'Kræver gennemgang'], previewEmpty: 'Ingen forhåndsvisning endnu. Verificer kilden og gennemfør en analyse.', consents: ['Virksomheden ejer eller må bruge oplysningerne.', 'Virksomheden må publicere billederne.', 'Autorell må lagre og vise oplysningerne.', 'Autorell må synkronisere lageret.', 'Virksomheden accepterer pilotvilkårene.'], back: 'Tilbage', next: 'Næste', saveSource: 'Gem kilde', saving: 'Gemmer', verify: 'Kontrollér verificering', startAnalysis: 'Start analyse', approve: 'Godkend kilde', close: 'Luk', selectOption: 'Vælg en mulighed', success: 'Kilden er gemt. Ingen annonce publiceres automatisk.', genericError: 'Handlingen kunne ikke gennemføres. Kontrollér oplysningerne.', deleteConfirm: 'Slet kilden? Importerede annoncer slettes ikke automatisk.' },
  },
  pl: {
    publicPage: { metaTitle: 'Automatyczny import zapasów pojazdów | Autorell', metaDescription: 'Połącz zapasy przez zweryfikowaną witrynę, XML, CSV, API lub indywidualne wdrożenie DMS.', eyebrow: 'Połączenie zapasów Autorell', title: 'Połącz istniejące zapasy pojazdów', intro: 'Nie publikuj ręcznie tych samych pojazdów na kolejnej platformie. Autorell może zaimportować zapasy i automatycznie aktualizować ceny, zdjęcia oraz dostępność.', primaryCta: 'Zgłoś się do bezpłatnego pilotażu', secondaryCta: 'Skontaktuj się z zespołem firmowym', methodsTitle: 'Pięć sposobów połączenia', methodsIntro: 'Wybieramy najbardziej wiarygodne źródło, a firma zachowuje kontrolę nad każdym połączeniem.', methods: [
        { key: 'website', title: 'Import z witryny', text: 'Autorell analizuje zweryfikowaną witrynę firmy i znajduje strony pojazdów.' }, { key: 'xml', title: 'Kanał XML', text: 'Firma udostępnia ustrukturyzowany kanał XML z uzgodnionymi polami i częstotliwością.' }, { key: 'csv', title: 'Import CSV', text: 'Prześlij plik CSV w formacie Autorell; później można dodać cykliczne dostarczanie.' }, { key: 'api', title: 'API', text: 'Autorell łączy się z API firmy lub dostawcy przez sprawdzoną integrację serwerową.' }, { key: 'dms', title: 'Integracja DMS', text: 'Dla systemu DMS lub magazynowego tworzony jest indywidualny proces wdrożenia.' },
      ], syncTitle: 'Automatyczna i kontrolowana synchronizacja', syncIntro: 'Udane synchronizacje aktualizują zapasy, a chwilowa awaria źródła nie usuwa wszystkich ogłoszeń.', syncRules: ['Zatwierdzony nowy pojazd źródłowy tworzy nowe ogłoszenie Autorell.', 'Zmiana ceny aktualizuje powiązane ogłoszenie.', 'Zmienione zdjęcia i właściwości są synchronizowane.', 'Sprzedany lub usunięty pojazd jest wstrzymywany po potwierdzonych kontrolach.', 'Chwilowa awaria witryny nigdy nie wycofuje całych zapasów.'], safetyTitle: 'Weryfikacja przed publikacją', safetyBody: 'Autorell weryfikuje źródło, pokazuje podgląd oraz rejestruje prawa i zgody przed publikacją.' },
    portal: { navLabel: 'Połączenie zapasów', title: 'Połączenie zapasów', description: 'Zarządzaj zweryfikowanymi źródłami, podglądami, synchronizacją i statusem pilotażu.', addSource: 'Dodaj źródło importu', metrics: ['Aktywne źródła', 'Zaimportowane pojazdy', 'Opublikowane pojazdy', 'Wymaga przeglądu', 'Błędy synchronizacji', 'Ostatnia udana synchronizacja', 'Następna synchronizacja', 'Połączone lokalizacje'], pilotActive: 'Pilotaż aktywny', noAutomaticPayment: 'Brak automatycznej płatności', sourcesTitle: 'Źródła importu', noSources: 'Nie dodano jeszcze źródła importu.', sourceLabels: ['Typ', 'Źródło', 'Status', 'Weryfikacja', 'Znaleziono', 'Opublikowano', 'Ostatnia synchronizacja', 'Następna synchronizacja', 'Błędy'], actions: ['Otwórz źródło', 'Uruchom synchronizację', 'Wstrzymaj', 'Wznów', 'Pokaż dziennik', 'Edytuj mapowanie', 'Usuń źródło'], statuses: { draft: 'Szkic', analyzing: 'Analiza', ready: 'Gotowe', active: 'Aktywne', paused: 'Wstrzymane', error: 'Błąd', disabled: 'Wyłączone', unverified: 'Niezweryfikowane', pending: 'Oczekuje', verified: 'Zweryfikowane', failed: 'Nieudane', manual_review: 'Ręczna weryfikacja' } },
    wizard: { title: 'Dodaj źródło importu', intro: 'Utwórz źródło, zweryfikuj je, sprawdź analizę i osobno zatwierdź publikację.', steps: ['Metoda', 'Dane', 'Weryfikacja', 'Analiza', 'Podgląd', 'Zatwierdzenie'], methodTitle: 'Wybierz metodę', detailsTitle: 'Podaj dane źródła', verificationTitle: 'Zweryfikuj źródło', verificationIntro: 'Domena musi zostać zweryfikowana przez DNS, plik HTML, metatag lub administratora Autorell.', analysisTitle: 'Przeanalizuj źródło', analysisIntro: 'Autorell wyszukuje mapy witryn, strony pojazdów i deterministyczne dane strukturalne.', previewTitle: 'Podgląd pojazdów', previewIntro: 'Sprawdź co najmniej dziesięć przykładów, jakość danych i ostrzeżenia.', previewColumns: ['Tytuł', 'Cena', 'Jakość', 'Status'], approvalTitle: 'Zatwierdź prawa i synchronizację', approvalIntro: 'Nic nie zostanie opublikowane przed wszystkimi potwierdzeniami.', fields: ['Nazwa źródła', 'URL witryny', 'URL zapasów', 'URL kanału', 'URL dokumentacji', 'Interwał (godziny)', 'Dostawca systemu', 'Kontakt techniczny', 'Uwierzytelnianie', 'Opcjonalne subdomeny', 'Lokalizacja', 'Limit importu'], verificationMethods: ['Rekord DNS', 'Plik HTML', 'Metatag', 'Ręczna weryfikacja'], analysisChecks: ['Domena zweryfikowana', 'Mapa witryny znaleziona', 'Strony zapasów znalezione', 'Ogłoszenia znalezione', 'Gotowe do importu', 'Wymaga przeglądu'], previewEmpty: 'Brak podglądu. Zweryfikuj źródło i zakończ analizę.', consents: ['Firma posiada informacje lub może ich używać.', 'Firma może publikować zdjęcia.', 'Autorell może przechowywać i wyświetlać informacje.', 'Autorell może synchronizować zapasy.', 'Firma akceptuje warunki pilotażu.'], back: 'Wstecz', next: 'Dalej', saveSource: 'Zapisz źródło', saving: 'Zapisywanie', verify: 'Sprawdź weryfikację', startAnalysis: 'Rozpocznij analizę', approve: 'Zatwierdź źródło', close: 'Zamknij', selectOption: 'Wybierz opcję', success: 'Źródło zostało zapisane. Żadne ogłoszenie nie jest publikowane automatycznie.', genericError: 'Nie udało się wykonać działania. Sprawdź dane.', deleteConfirm: 'Usunąć źródło? Zaimportowane ogłoszenia nie zostaną automatycznie usunięte.' },
  },
}

const dmsOnboardingSuccess: Record<BusinessPilotLocale, string> = {
  en: 'Your DMS onboarding request has been saved. Autorell will contact the technical contact before any connection starts.',
  sv: 'Ert DMS-onboardingärende har sparats. Autorell kontaktar den tekniska kontaktpersonen innan någon anslutning startar.',
  de: 'Ihre DMS-Onboarding-Anfrage wurde gespeichert. Autorell kontaktiert die technische Kontaktperson, bevor eine Verbindung startet.',
  fr: 'Votre demande d’onboarding DMS a été enregistrée. Autorell contactera l’interlocuteur technique avant toute connexion.',
  es: 'La solicitud de incorporación DMS se ha guardado. Autorell contactará con la persona técnica antes de iniciar cualquier conexión.',
  it: 'La richiesta di onboarding DMS è stata salvata. Autorell contatterà il referente tecnico prima di avviare qualsiasi collegamento.',
  nl: 'De DMS-onboardingaanvraag is opgeslagen. Autorell neemt contact op met de technische contactpersoon voordat een koppeling start.',
  fi: 'DMS-käyttöönoton pyyntö on tallennettu. Autorell ottaa yhteyttä tekniseen yhteyshenkilöön ennen yhteyden käynnistämistä.',
  da: 'DMS-onboardinganmodningen er gemt. Autorell kontakter den tekniske kontaktperson, før en forbindelse startes.',
  pl: 'Wniosek o wdrożenie DMS został zapisany. Autorell skontaktuje się z osobą techniczną przed uruchomieniem połączenia.',
}

const flowCopy: Record<BusinessPilotLocale, {
  pilotAvailable: string
  comingSoon: string
  adminOnboarding: string
  generateVerificationToken: string
  analysisQueued: string
  approvalStarted: string
}> = {
  en: { pilotAvailable: 'Available in the pilot', comingSoon: 'Coming soon', adminOnboarding: 'Admin onboarding', generateVerificationToken: 'Create verification code', analysisQueued: 'The analysis is running. The preview updates automatically.', approvalStarted: 'The source is approved and the first controlled import has started.' },
  sv: { pilotAvailable: 'Tillgänglig i piloten', comingSoon: 'Kommer snart', adminOnboarding: 'Administrativ onboarding', generateVerificationToken: 'Skapa verifieringskod', analysisQueued: 'Analysen körs. Förhandsgranskningen uppdateras automatiskt.', approvalStarted: 'Källan är godkänd och den första kontrollerade importen har startat.' },
  de: { pilotAvailable: 'Im Pilot verfügbar', comingSoon: 'Demnächst verfügbar', adminOnboarding: 'Onboarding durch Autorell', generateVerificationToken: 'Verifizierungscode erstellen', analysisQueued: 'Die Analyse läuft. Die Vorschau wird automatisch aktualisiert.', approvalStarted: 'Die Quelle ist freigegeben und der erste kontrollierte Import wurde gestartet.' },
  fr: { pilotAvailable: 'Disponible dans le pilote', comingSoon: 'Bientôt disponible', adminOnboarding: 'Onboarding par Autorell', generateVerificationToken: 'Créer le code de vérification', analysisQueued: 'L’analyse est en cours. L’aperçu se met à jour automatiquement.', approvalStarted: 'La source est approuvée et le premier import contrôlé a démarré.' },
  es: { pilotAvailable: 'Disponible en el piloto', comingSoon: 'Próximamente', adminOnboarding: 'Incorporación por Autorell', generateVerificationToken: 'Crear código de verificación', analysisQueued: 'El análisis está en curso. La vista previa se actualiza automáticamente.', approvalStarted: 'La fuente está aprobada y ha comenzado la primera importación controlada.' },
  it: { pilotAvailable: 'Disponibile nel progetto pilota', comingSoon: 'Prossimamente', adminOnboarding: 'Onboarding con Autorell', generateVerificationToken: 'Crea codice di verifica', analysisQueued: 'L’analisi è in corso. L’anteprima si aggiorna automaticamente.', approvalStarted: 'La fonte è approvata ed è iniziata la prima importazione controllata.' },
  nl: { pilotAvailable: 'Beschikbaar in de pilot', comingSoon: 'Binnenkort', adminOnboarding: 'Onboarding door Autorell', generateVerificationToken: 'Verificatiecode maken', analysisQueued: 'De analyse wordt uitgevoerd. Het voorbeeld wordt automatisch bijgewerkt.', approvalStarted: 'De bron is goedgekeurd en de eerste gecontroleerde import is gestart.' },
  fi: { pilotAvailable: 'Saatavilla pilotissa', comingSoon: 'Tulossa pian', adminOnboarding: 'Autorellin käyttöönotto', generateVerificationToken: 'Luo vahvistuskoodi', analysisQueued: 'Analyysi on käynnissä. Esikatselu päivittyy automaattisesti.', approvalStarted: 'Lähde on hyväksytty ja ensimmäinen hallittu tuonti on alkanut.' },
  da: { pilotAvailable: 'Tilgængelig i piloten', comingSoon: 'Kommer snart', adminOnboarding: 'Onboarding med Autorell', generateVerificationToken: 'Opret verificeringskode', analysisQueued: 'Analysen kører. Forhåndsvisningen opdateres automatisk.', approvalStarted: 'Kilden er godkendt, og den første kontrollerede import er startet.' },
  pl: { pilotAvailable: 'Dostępne w pilotażu', comingSoon: 'Wkrótce', adminOnboarding: 'Wdrożenie przez Autorell', generateVerificationToken: 'Utwórz kod weryfikacyjny', analysisQueued: 'Analiza jest w toku. Podgląd aktualizuje się automatycznie.', approvalStarted: 'Źródło zostało zatwierdzone i rozpoczął się pierwszy kontrolowany import.' },
}

const extras: Record<BusinessPilotLocale, { statuses: Record<string, string>; errors: InventoryImportErrorCopy }> = {
  en: { statuses: { import_pending: 'Ready to import', import_review: 'Needs review', source_missing: 'Missing from source', sold: 'Sold', import_error: 'Import error', deleted: 'Deleted', queued: 'Queued', running: 'Running', completed: 'Completed', completed_with_warnings: 'Completed with warnings', cancelled: 'Cancelled' }, errors: { rateLimited: 'Too many attempts. Wait a moment and try again.', permission: 'A company manager role is required for this action.', verification: 'Verify the source before continuing.', approval: 'Required approval or accepted pilot terms are missing.', details: 'Check the source details, URLs and verified domain.', unavailable: 'This connection method is not enabled for your pilot.', sourceProblem: 'The source could not be reached or updated. Try again later.' } },
  sv: { statuses: { import_pending: 'Klar för import', import_review: 'Kräver granskning', source_missing: 'Saknas i källan', sold: 'Såld', import_error: 'Importfel', deleted: 'Borttagen', queued: 'Köad', running: 'Körs', completed: 'Slutförd', completed_with_warnings: 'Slutförd med varningar', cancelled: 'Avbruten' }, errors: { rateLimited: 'För många försök. Vänta en stund och försök igen.', permission: 'En företagsansvarig roll krävs för den här åtgärden.', verification: 'Verifiera källan innan ni fortsätter.', approval: 'Nödvändigt godkännande eller accepterade pilotvillkor saknas.', details: 'Kontrollera källuppgifterna, adresserna och den verifierade domänen.', unavailable: 'Den här anslutningsmetoden är inte aktiverad för er pilot.', sourceProblem: 'Källan kunde inte nås eller uppdateras. Försök igen senare.' } },
  de: { statuses: { import_pending: 'Importbereit', import_review: 'Prüfung erforderlich', source_missing: 'In der Quelle nicht gefunden', sold: 'Verkauft', import_error: 'Importfehler', deleted: 'Gelöscht', queued: 'In Warteschlange', running: 'Wird ausgeführt', completed: 'Abgeschlossen', completed_with_warnings: 'Mit Warnungen abgeschlossen', cancelled: 'Abgebrochen' }, errors: { rateLimited: 'Zu viele Versuche. Warten Sie kurz und versuchen Sie es erneut.', permission: 'Für diese Aktion ist eine Unternehmens-Managerrolle erforderlich.', verification: 'Verifizieren Sie die Quelle, bevor Sie fortfahren.', approval: 'Eine erforderliche Zustimmung oder akzeptierte Pilotbedingungen fehlen.', details: 'Prüfen Sie Quelldaten, URLs und die verifizierte Domain.', unavailable: 'Diese Verbindungsmethode ist für Ihren Piloten nicht aktiviert.', sourceProblem: 'Die Quelle konnte nicht erreicht oder aktualisiert werden. Versuchen Sie es später erneut.' } },
  fr: { statuses: { import_pending: 'Prêt à importer', import_review: 'Contrôle requis', source_missing: 'Absent de la source', sold: 'Vendu', import_error: 'Erreur d’import', deleted: 'Supprimé', queued: 'En attente', running: 'En cours', completed: 'Terminé', completed_with_warnings: 'Terminé avec avertissements', cancelled: 'Annulé' }, errors: { rateLimited: 'Trop de tentatives. Patientez puis réessayez.', permission: 'Un rôle de gestionnaire de l’entreprise est requis pour cette action.', verification: 'Vérifiez la source avant de continuer.', approval: 'Une autorisation requise ou l’acceptation des conditions du pilote manque.', details: 'Vérifiez les informations de la source, les URL et le domaine vérifié.', unavailable: 'Cette méthode de connexion n’est pas activée pour votre pilote.', sourceProblem: 'La source n’a pas pu être jointe ou mise à jour. Réessayez plus tard.' } },
  es: { statuses: { import_pending: 'Listo para importar', import_review: 'Requiere revisión', source_missing: 'No está en la fuente', sold: 'Vendido', import_error: 'Error de importación', deleted: 'Eliminado', queued: 'En cola', running: 'En curso', completed: 'Completado', completed_with_warnings: 'Completado con avisos', cancelled: 'Cancelado' }, errors: { rateLimited: 'Demasiados intentos. Espera un momento e inténtalo de nuevo.', permission: 'Se requiere un rol de responsable de empresa para esta acción.', verification: 'Verifica la fuente antes de continuar.', approval: 'Falta una autorización necesaria o la aceptación de las condiciones del piloto.', details: 'Comprueba los datos de la fuente, las URL y el dominio verificado.', unavailable: 'Este método de conexión no está habilitado para tu piloto.', sourceProblem: 'No se pudo acceder a la fuente o actualizarla. Inténtalo más tarde.' } },
  it: { statuses: { import_pending: 'Pronto per l’importazione', import_review: 'Richiede verifica', source_missing: 'Assente dalla fonte', sold: 'Venduto', import_error: 'Errore di importazione', deleted: 'Eliminato', queued: 'In coda', running: 'In esecuzione', completed: 'Completato', completed_with_warnings: 'Completato con avvisi', cancelled: 'Annullato' }, errors: { rateLimited: 'Troppi tentativi. Attendi un momento e riprova.', permission: 'Per questa azione è richiesto un ruolo di responsabile aziendale.', verification: 'Verifica la fonte prima di continuare.', approval: 'Manca un’autorizzazione necessaria o l’accettazione dei termini del pilota.', details: 'Controlla i dati della fonte, gli URL e il dominio verificato.', unavailable: 'Questo metodo di connessione non è abilitato per il tuo pilota.', sourceProblem: 'Non è stato possibile raggiungere o aggiornare la fonte. Riprova più tardi.' } },
  nl: { statuses: { import_pending: 'Klaar voor import', import_review: 'Controle nodig', source_missing: 'Ontbreekt in bron', sold: 'Verkocht', import_error: 'Importfout', deleted: 'Verwijderd', queued: 'In wachtrij', running: 'Wordt uitgevoerd', completed: 'Voltooid', completed_with_warnings: 'Voltooid met waarschuwingen', cancelled: 'Geannuleerd' }, errors: { rateLimited: 'Te veel pogingen. Wacht even en probeer opnieuw.', permission: 'Voor deze actie is een bedrijfsbeheerdersrol vereist.', verification: 'Verifieer de bron voordat u verdergaat.', approval: 'Een vereiste goedkeuring of geaccepteerde pilotvoorwaarden ontbreken.', details: 'Controleer de brongegevens, URL’s en het geverifieerde domein.', unavailable: 'Deze verbindingsmethode is niet ingeschakeld voor uw pilot.', sourceProblem: 'De bron kon niet worden bereikt of bijgewerkt. Probeer het later opnieuw.' } },
  fi: { statuses: { import_pending: 'Valmis tuontiin', import_review: 'Tarkistus vaaditaan', source_missing: 'Puuttuu lähteestä', sold: 'Myyty', import_error: 'Tuontivirhe', deleted: 'Poistettu', queued: 'Jonossa', running: 'Käynnissä', completed: 'Valmis', completed_with_warnings: 'Valmis varoituksin', cancelled: 'Peruutettu' }, errors: { rateLimited: 'Liian monta yritystä. Odottakaa hetki ja yrittäkää uudelleen.', permission: 'Tähän toimintoon tarvitaan yrityksen hallinnoijan rooli.', verification: 'Vahvistakaa lähde ennen jatkamista.', approval: 'Tarvittava hyväksyntä tai hyväksytyt pilottiehdot puuttuvat.', details: 'Tarkistakaa lähteen tiedot, URL-osoitteet ja vahvistettu verkkotunnus.', unavailable: 'Tätä yhteystapaa ei ole otettu käyttöön pilotissanne.', sourceProblem: 'Lähdettä ei voitu tavoittaa tai päivittää. Yrittäkää myöhemmin uudelleen.' } },
  da: { statuses: { import_pending: 'Klar til import', import_review: 'Kræver gennemgang', source_missing: 'Mangler i kilden', sold: 'Solgt', import_error: 'Importfejl', deleted: 'Slettet', queued: 'I kø', running: 'Kører', completed: 'Gennemført', completed_with_warnings: 'Gennemført med advarsler', cancelled: 'Annulleret' }, errors: { rateLimited: 'For mange forsøg. Vent et øjeblik, og prøv igen.', permission: 'Denne handling kræver en virksomhedsadministratorrolle.', verification: 'Verificer kilden, før I fortsætter.', approval: 'En nødvendig godkendelse eller accepterede pilotvilkår mangler.', details: 'Kontrollér kildeoplysninger, URL’er og det verificerede domæne.', unavailable: 'Denne forbindelsesmetode er ikke aktiveret for jeres pilot.', sourceProblem: 'Kilden kunne ikke nås eller opdateres. Prøv igen senere.' } },
  pl: { statuses: { import_pending: 'Gotowe do importu', import_review: 'Wymaga przeglądu', source_missing: 'Brak w źródle', sold: 'Sprzedane', import_error: 'Błąd importu', deleted: 'Usunięte', queued: 'W kolejce', running: 'W toku', completed: 'Zakończone', completed_with_warnings: 'Zakończone z ostrzeżeniami', cancelled: 'Anulowane' }, errors: { rateLimited: 'Zbyt wiele prób. Poczekaj chwilę i spróbuj ponownie.', permission: 'Ta czynność wymaga roli administratora firmy.', verification: 'Zweryfikuj źródło przed kontynuowaniem.', approval: 'Brakuje wymaganej zgody lub zaakceptowanych warunków pilotażu.', details: 'Sprawdź dane źródła, adresy URL i zweryfikowaną domenę.', unavailable: 'Ta metoda połączenia nie jest włączona dla tego pilotażu.', sourceProblem: 'Nie udało się uzyskać dostępu do źródła lub go zaktualizować. Spróbuj ponownie później.' } },
}

export function getInventoryImportCopy(locale: PublicLocale): InventoryImportCopy {
  const normalized = translationLocale(locale)
  const key = normalized as BusinessPilotLocale
  const copy = copies[key] || copies.en
  const extra = extras[key] || extras.en
  const flow = flowCopy[key] || flowCopy.en
  return {
    ...copy,
    publicPage: {
      ...copy.publicPage,
      methods: copy.publicPage.methods.map((method) => ({
        ...method,
        status: method.key === 'website' ? flow.pilotAvailable : method.key === 'dms' ? flow.adminOnboarding : flow.comingSoon,
        selectable: method.key === 'website' || method.key === 'dms',
      })),
    },
    portal: { ...copy.portal, statuses: { ...copy.portal.statuses, ...extra.statuses } },
    wizard: {
      ...copy.wizard,
      success: flow.approvalStarted,
      onboardingSuccess: dmsOnboardingSuccess[key] || dmsOnboardingSuccess.en,
      generateVerificationToken: flow.generateVerificationToken,
      analysisQueued: flow.analysisQueued,
    },
    errors: extra.errors,
  }
}
