import { translationLocale, type PublicLocale } from '@/lib/public-i18n'

export type PilotDashboardCopy = {
  title: string
  active: string
  paused: string
  completed: string
  startDate: string
  endDate: string
  daysRemaining: string
  noAutomaticPayment: string
  contact: string
  resultsTitle: string
  periods: [string, string, string]
  metrics: [string, string, string, string, string, string]
  topVehicles: string
  trafficByCountry: string
  noData: string
  commercialTitle: string
  commercialBody: string
  commercialButton: string
  commercialSent: string
  commercialError: string
}

const copies: Record<string, PilotDashboardCopy> = {
  en: c('Pilot status', 'Pilot active', 'Pilot paused', 'Pilot completed', 'Start date', 'Planned end date', 'Days remaining', 'No automatic payment or subscription', 'Autorell contact', 'Results', ['7 days', '30 days', '90 days'], ['Listing views', 'Listing visits', 'Website clicks', 'Phone clicks', 'Incoming leads', 'Published vehicles'], 'Most viewed vehicles', 'Traffic by country', 'No result data is available for this period.', 'Continued cooperation', 'Ask Autorell’s business team to review the documented results and discuss a separate agreement. No purchase or subscription is created.', 'Discuss continued cooperation', 'Your request has been sent to Autorell.', 'The request could not be sent. Please try again.'),
  sv: c('Pilotstatus', 'Pilot aktiv', 'Pilot pausad', 'Pilot avslutad', 'Startdatum', 'Planerat slutdatum', 'Antal dagar kvar', 'Ingen automatisk betalning eller prenumeration', 'Kontaktperson hos Autorell', 'Resultat', ['7 dagar', '30 dagar', '90 dagar'], ['Annonsvisningar', 'Annonsbesök', 'Klick till webbplats', 'Telefonklick', 'Inkomna leads', 'Publicerade fordon'], 'Mest visade fordon', 'Trafik per land', 'Det finns ingen resultatdata för perioden ännu.', 'Fortsatt samarbete', 'Be Autorells företagsteam granska de dokumenterade resultaten och diskutera ett separat avtal. Inget köp eller abonnemang skapas.', 'Diskutera fortsatt samarbete', 'Er förfrågan har skickats till Autorell.', 'Förfrågan kunde inte skickas. Försök igen.'),
  de: c('Pilotstatus', 'Pilot aktiv', 'Pilot pausiert', 'Pilot abgeschlossen', 'Startdatum', 'Geplantes Enddatum', 'Verbleibende Tage', 'Keine automatische Zahlung oder Abonnement', 'Kontakt bei Autorell', 'Ergebnisse', ['7 Tage', '30 Tage', '90 Tage'], ['Anzeigenaufrufe', 'Anzeigenbesuche', 'Website-Klicks', 'Telefonklicks', 'Eingegangene Leads', 'Veröffentlichte Fahrzeuge'], 'Meistgesehene Fahrzeuge', 'Traffic nach Land', 'Für diesen Zeitraum sind noch keine Ergebnisdaten verfügbar.', 'Weitere Zusammenarbeit', 'Bitten Sie das Autorell-Unternehmensteam, die dokumentierten Ergebnisse zu prüfen und eine separate Vereinbarung zu besprechen. Es wird kein Kauf oder Abonnement erstellt.', 'Weitere Zusammenarbeit besprechen', 'Ihre Anfrage wurde an Autorell gesendet.', 'Die Anfrage konnte nicht gesendet werden. Bitte versuchen Sie es erneut.'),
  fr: c('Statut du pilote', 'Pilote actif', 'Pilote en pause', 'Pilote terminé', 'Date de début', 'Date de fin prévue', 'Jours restants', 'Aucun paiement ni abonnement automatique', 'Contact Autorell', 'Résultats', ['7 jours', '30 jours', '90 jours'], ['Vues des annonces', 'Visites des annonces', 'Clics vers le site', 'Clics téléphone', 'Prospects reçus', 'Véhicules publiés'], 'Véhicules les plus vus', 'Trafic par pays', 'Aucune donnée de résultat n’est encore disponible pour cette période.', 'Poursuite de la coopération', 'Demandez à l’équipe entreprises d’Autorell d’examiner les résultats documentés et de discuter d’un accord distinct. Aucun achat ni abonnement n’est créé.', 'Discuter de la poursuite', 'Votre demande a été envoyée à Autorell.', 'La demande n’a pas pu être envoyée. Réessayez.'),
  es: c('Estado del piloto', 'Piloto activo', 'Piloto en pausa', 'Piloto finalizado', 'Fecha de inicio', 'Fecha prevista de finalización', 'Días restantes', 'Sin pago ni suscripción automáticos', 'Contacto de Autorell', 'Resultados', ['7 días', '30 días', '90 días'], ['Vistas de anuncios', 'Visitas a anuncios', 'Clics al sitio web', 'Clics de teléfono', 'Leads recibidos', 'Vehículos publicados'], 'Vehículos más vistos', 'Tráfico por país', 'Aún no hay datos de resultados para este periodo.', 'Colaboración futura', 'Solicita al equipo de empresas de Autorell que revise los resultados documentados y analice un acuerdo independiente. No se crea ninguna compra ni suscripción.', 'Hablar de colaboración futura', 'La solicitud se ha enviado a Autorell.', 'No se pudo enviar la solicitud. Inténtalo de nuevo.'),
  it: c('Stato del progetto pilota', 'Pilota attivo', 'Pilota in pausa', 'Pilota terminato', 'Data di inizio', 'Data di fine prevista', 'Giorni rimanenti', 'Nessun pagamento o abbonamento automatico', 'Contatto Autorell', 'Risultati', ['7 giorni', '30 giorni', '90 giorni'], ['Visualizzazioni annunci', 'Visite agli annunci', 'Clic al sito web', 'Clic telefono', 'Lead ricevuti', 'Veicoli pubblicati'], 'Veicoli più visualizzati', 'Traffico per paese', 'Non sono ancora disponibili dati per questo periodo.', 'Collaborazione futura', 'Chiedi al team aziende Autorell di esaminare i risultati documentati e discutere un accordo separato. Non viene creato alcun acquisto o abbonamento.', 'Discuti la collaborazione futura', 'La richiesta è stata inviata ad Autorell.', 'Impossibile inviare la richiesta. Riprova.'),
  nl: c('Pilotstatus', 'Pilot actief', 'Pilot gepauzeerd', 'Pilot afgerond', 'Startdatum', 'Geplande einddatum', 'Resterende dagen', 'Geen automatische betaling of abonnement', 'Contact bij Autorell', 'Resultaten', ['7 dagen', '30 dagen', '90 dagen'], ['Advertentieweergaven', 'Advertentiebezoeken', 'Websiteklikken', 'Telefoonklikken', 'Ontvangen leads', 'Gepubliceerde voertuigen'], 'Meest bekeken voertuigen', 'Verkeer per land', 'Er zijn nog geen resultaatgegevens voor deze periode.', 'Verdere samenwerking', 'Vraag het bedrijfsteam van Autorell om de vastgelegde resultaten te beoordelen en een afzonderlijke overeenkomst te bespreken. Er wordt geen aankoop of abonnement aangemaakt.', 'Verdere samenwerking bespreken', 'Uw verzoek is naar Autorell verzonden.', 'Het verzoek kon niet worden verzonden. Probeer het opnieuw.'),
  fi: c('Pilotin tila', 'Pilotti aktiivinen', 'Pilotti keskeytetty', 'Pilotti päättynyt', 'Aloituspäivä', 'Suunniteltu päättymispäivä', 'Päiviä jäljellä', 'Ei automaattista maksua tai tilausta', 'Autorell-yhteyshenkilö', 'Tulokset', ['7 päivää', '30 päivää', '90 päivää'], ['Ilmoitusnäytöt', 'Ilmoituskäynnit', 'Verkkosivuklikkaukset', 'Puhelinklikkaukset', 'Saapuneet leadit', 'Julkaistut ajoneuvot'], 'Katsotuimmat ajoneuvot', 'Liikenne maittain', 'Tälle ajanjaksolle ei ole vielä tulostietoja.', 'Jatkoyhteistyö', 'Pyydä Autorellin yritystiimiä tarkistamaan dokumentoidut tulokset ja keskustelemaan erillisestä sopimuksesta. Ostoa tai tilausta ei luoda.', 'Keskustele jatkoyhteistyöstä', 'Pyyntönne on lähetetty Autorellille.', 'Pyyntöä ei voitu lähettää. Yrittäkää uudelleen.'),
  da: c('Pilotstatus', 'Pilot aktiv', 'Pilot på pause', 'Pilot afsluttet', 'Startdato', 'Planlagt slutdato', 'Dage tilbage', 'Ingen automatisk betaling eller abonnement', 'Kontakt hos Autorell', 'Resultater', ['7 dage', '30 dage', '90 dage'], ['Annoncevisninger', 'Annoncebesøg', 'Klik til hjemmeside', 'Telefonklik', 'Indgående leads', 'Publicerede køretøjer'], 'Mest viste køretøjer', 'Trafik pr. land', 'Der er endnu ingen resultatdata for perioden.', 'Fortsat samarbejde', 'Bed Autorells virksomhedsteam om at gennemgå de dokumenterede resultater og drøfte en separat aftale. Der oprettes intet køb eller abonnement.', 'Drøft fortsat samarbejde', 'Jeres forespørgsel er sendt til Autorell.', 'Forespørgslen kunne ikke sendes. Prøv igen.'),
  pl: c('Status pilotażu', 'Pilotaż aktywny', 'Pilotaż wstrzymany', 'Pilotaż zakończony', 'Data rozpoczęcia', 'Planowana data zakończenia', 'Pozostałe dni', 'Brak automatycznej płatności lub subskrypcji', 'Kontakt w Autorell', 'Wyniki', ['7 dni', '30 dni', '90 dni'], ['Wyświetlenia ogłoszeń', 'Wizyty w ogłoszeniach', 'Kliknięcia witryny', 'Kliknięcia telefonu', 'Otrzymane leady', 'Opublikowane pojazdy'], 'Najczęściej oglądane pojazdy', 'Ruch według kraju', 'Brak danych o wynikach dla tego okresu.', 'Dalsza współpraca', 'Poproś zespół firmowy Autorell o analizę udokumentowanych wyników i omówienie odrębnej umowy. Nie zostanie utworzony zakup ani subskrypcja.', 'Omów dalszą współpracę', 'Wniosek został wysłany do Autorell.', 'Nie udało się wysłać wniosku. Spróbuj ponownie.'),
}

function c(title: string, active: string, paused: string, completed: string, startDate: string, endDate: string, daysRemaining: string, noAutomaticPayment: string, contact: string, resultsTitle: string, periods: PilotDashboardCopy['periods'], metrics: PilotDashboardCopy['metrics'], topVehicles: string, trafficByCountry: string, noData: string, commercialTitle: string, commercialBody: string, commercialButton: string, commercialSent: string, commercialError: string): PilotDashboardCopy {
  return { title, active, paused, completed, startDate, endDate, daysRemaining, noAutomaticPayment, contact, resultsTitle, periods, metrics, topVehicles, trafficByCountry, noData, commercialTitle, commercialBody, commercialButton, commercialSent, commercialError }
}

export function getPilotDashboardCopy(locale: PublicLocale) { return copies[translationLocale(locale)] || copies.en }
